export const PropertyBarComponents = {
  PropertyBar: "propertyBar",
  FirstLevelNode: "firstLevelNode",
  SecondLevelNode: "secondLevelNode",
  ThirdLevelNode: "thirdLevelNode",
  FloatItem: "floatItem",
  RadioButton: "radioButton",
  LengthInput: "lengthInput",
  SliderInput: "sliderInput",
  SliderInputGroup: "sliderInputGroup",
  ImageButton: "imageButton",
  Switch: "switch",
  TabsSelect: "tabsSelect",
  ColorPicker: "colorPicker",
  Dropdownroomtypelist: "dropdownroomtypelist",
  DropdownList: "dropdownlist",
  DropdownInput: "dropdowninput",
  DropdownAreaList: "dropdownarealist",
  CheckBox: "checkbox",
  Button: "button",
  LabelRadioButton: "labelRadioButton",
  ImageTextButton: "imageTextButton",
  BlockAlign: "blockAlign",
  LabelButton: "labelButton",
  NoChoice: "noChoice",
  CheckBlock: "checkBlock",
  TpzzLabelRadioInput: "tpzz-labelradioinput",
  TpzzLengthInput: "tpzz-lengthinput",
  LabelButtons: "tpzz-labelbuttons",
  LabelInput: "labelinput",
  RotateButton: "rotatebutton",
  AxialRotation: "axialRotation",
  MultiSelectButton: "MultiSelectButton",
  SchematicDiagram: "schematicdiagram"
} as const;

export type PropertyBarComponentType = typeof PropertyBarComponents[keyof typeof PropertyBarComponents];