export enum LogGroupTypes {
  WallOperation = "wallOperation",
  SlabOperation = "slabOperation",
  SpaceOperation = "spaceOperation",
  LayerOperation = "layerOperation",
  ContentOperation = "contentOperation",
  CatalogOperation = "catalogOperation",
  TemplateDesign = "templateDesign",
  SmartCollocation = "smartCollocation",
  ViewOperation = "viewOperation",
  OpenDesign = "openDesign",
  SaveDesign = "saveDesign",
  ImportOperation = "importOperation",
  ExportOperation = "exportOperation",
  FaceOperation = "faceOperation",
  HardOperation = "hardOperation",
  SparkPic = "SparkPicOperation",
  SparkPicAlbum = "sparkPicAlbumOperation",
  ContentPropertiesOperation = "contentPropertiesOperation",
  StyleOperation = "styleOperation",
  LightPositionOperation = "lightPositionOperation",
  LightPropertyOperation = "lightPropertyOperation",
  LightTemplate = "lightTemplateOperation",
  Render = "renderOperation",
  Album = "albumOperation",
  EditImage = "editImage",
  LightMix = "lightMixOperation",
  VideoRender = "videoRenderOperation",
  Category = "categoryCatalog",
  Favorite = "favoriteCatalog",
  Filter = "filterCatalog",
  Search = "searchCatalog",
  ScrollPage = "scrollPageCatalog",
  PlaceToCanvas = "placeToCanvasCatalog",
  ConcealedWorkV2 = "concealedWorkV2",
  AutoPlaceContent = "autoPlaceContent",
  AutoPowerSetting = "autoPowerSetting",
  ConfigurePowerSetting = "configurePowerSetting",
  AutoCircuit = "autoCircuit",
  ConfigureCircuit = "configureCircuit",
  AutoLightCtrl = "autoLightControl",
  ConfigureLightCtrl = "configureLightCtrl",
  ManualPlaceTube = "manualPlaceTube",
  ManualPlaceTube3D = "manualPlaceTube3D",
  AutoPlaceTube = "autoPlaceTube",
  ParametricBackgroundWall = "parametricBackgroundWall",
  Sketch = "sketch",
  ExtraordinarySketch2d = "extraordinarySketch2d",
  Section = "section",
  Elevation = "elevation",
  ParametricBackgroundWallUnit = "parametricBackgroundWallUnit",
  ParametricCurtain = "parametricCurtain",
  ParametricBathroomCabinet = "parametricBathroomCabinet",
  ParametricContentBase = "parametricContentBase",
  ParametricModel = "parametricModel",
  SlabEdit = "slabEdit",
  ThumbnaiView = "thumbnaiView",
  RoofsDrawing = "roofsDrawing",
  OutdoorDrawing = "outdoorDrawing"
}

export const LogGroupTypesName: Record<LogGroupTypes, string> = {
  [LogGroupTypes.WallOperation]: "画墙操作",
  [LogGroupTypes.SlabOperation]: "楼板编辑操作",
  [LogGroupTypes.SpaceOperation]: "空间操作",
  [LogGroupTypes.LayerOperation]: "层操作",
  [LogGroupTypes.ContentOperation]: "模型操作",
  [LogGroupTypes.CatalogOperation]: "找模型",
  [LogGroupTypes.TemplateDesign]: "速搭工作流",
  [LogGroupTypes.SmartCollocation]: "智能搭配",
  [LogGroupTypes.ViewOperation]: "视图操作",
  [LogGroupTypes.OpenDesign]: "打开设计",
  [LogGroupTypes.SaveDesign]: "保存设计",
  [LogGroupTypes.ImportOperation]: "导入操作",
  [LogGroupTypes.ExportOperation]: "导出操作",
  [LogGroupTypes.FaceOperation]: "墙面操作",
  [LogGroupTypes.HardOperation]: "硬装操作",
  [LogGroupTypes.SparkPic]: "灵图面板操作",
  [LogGroupTypes.SparkPicAlbum]: "图册集操作",
  [LogGroupTypes.ContentPropertiesOperation]: "修改柜子属性",
  [LogGroupTypes.StyleOperation]: "修改风格",
  [LogGroupTypes.LightPositionOperation]: "灯光位置操作",
  [LogGroupTypes.LightPropertyOperation]: "灯光属性操作",
  [LogGroupTypes.LightTemplate]: "灯光模板操作",
  [LogGroupTypes.Render]: "渲染面板操作",
  [LogGroupTypes.Album]: "图册操作",
  [LogGroupTypes.EditImage]: "美图",
  [LogGroupTypes.LightMix]: "调光操作",
  [LogGroupTypes.VideoRender]: "视频+路径编辑相关",
  [LogGroupTypes.Category]: "切换目录节点",
  [LogGroupTypes.Favorite]: "收藏功能",
  [LogGroupTypes.Filter]: "筛选项",
  [LogGroupTypes.Search]: "搜索功能",
  [LogGroupTypes.ScrollPage]: "滚动条",
  [LogGroupTypes.PlaceToCanvas]: "放置模型至画布",
  [LogGroupTypes.ConcealedWorkV2]: "水电2.0",
  [LogGroupTypes.AutoPlaceContent]: "自动布点",
  [LogGroupTypes.AutoPowerSetting]: "自动配电",
  [LogGroupTypes.ConfigurePowerSetting]: "配电设置",
  [LogGroupTypes.AutoCircuit]: "自动设置回路点位",
  [LogGroupTypes.ConfigureCircuit]: "回路设置",
  [LogGroupTypes.AutoLightCtrl]: "自动设置灯控关系及点位",
  [LogGroupTypes.ConfigureLightCtrl]: "灯控设置",
  [LogGroupTypes.ManualPlaceTube]: "手动布管",
  [LogGroupTypes.ManualPlaceTube3D]: "手动布管3D",
  [LogGroupTypes.AutoPlaceTube]: "自动布管",
  [LogGroupTypes.ParametricBackgroundWall]: "参数化背景墙",
  [LogGroupTypes.Sketch]: "画区域",
  [LogGroupTypes.ExtraordinarySketch2d]: "ExtraordinarySketch2d",
  [LogGroupTypes.Section]: "剖面",
  [LogGroupTypes.Elevation]: "立面",
  [LogGroupTypes.ParametricBackgroundWallUnit]: "参数化背景墙单元",
  [LogGroupTypes.ParametricCurtain]: "参数化窗帘",
  [LogGroupTypes.ParametricBathroomCabinet]: "参数化浴室柜",
  [LogGroupTypes.ParametricContentBase]: "参数化软装",
  [LogGroupTypes.ParametricModel]: "参数化模型",
  [LogGroupTypes.SlabEdit]: "楼板编辑",
  [LogGroupTypes.ThumbnaiView]: "小窗口",
  [LogGroupTypes.RoofsDrawing]: "roofsDrawing",
  [LogGroupTypes.OutdoorDrawing]: "outdoorDrawing"
};