/**
 * Asset module that exports the path to the recent icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static assets like images and SVG files.
 * 
 * @module RecentIconAsset
 */

/**
 * The public path to the recent.svg icon asset.
 * This path is resolved at build time and includes cache-busting hash (af3cc233).
 * 
 * @example
 *