/**
 * Webpack asset module that exports the URL path to a static SVG asset.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module AssetModule
 * @description Exports the public path to the 'list.svg' icon asset
 */

/**
 * The public URL path to the list icon SVG asset.
 * This path is resolved at build time by Webpack and includes the content hash for cache busting.
 * 
 * @example
 *