/**
 * Webpack asset module that exports the public URL path for the default water symbol SVG asset.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DefaultWaterSymbolAsset
 */

/**
 * The public URL path to the default water symbol SVG file.
 * This path is resolved by the bundler and points to the hashed asset file.
 * 
 * @example
 *