/**
 * Asset module that exports the URL path to the help icon SVG file.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module HelpIconAsset
 */

/**
 * The public URL path to the help.svg icon asset.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *