/**
 * CSS Module loader type definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack's style-loader + css-loader for modular stylesheets.
 */

/**
 * Configuration options for style injection
 */
interface StyleLoaderOptions {
  /**
   * Transform function that processes style tags before insertion
   */
  styleTagTransform: () => void;

  /**
   * Function to set custom attributes on style elements
   */
  setAttributes: () => void;

  /**
   * DOM insertion function, bound to insert into specified container
   * @param target - The DOM element selector to insert styles into (e.g., "head")
   */
  insert: (target: string) => void;

  /**
   * DOM API interface for style manipulation
   */
  domAPI: () => void;

  /**
   * Function to create and insert style elements into the DOM
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports containing local class name mappings
 * 
 * Maps CSS class names to their hashed/scoped equivalents.
 * Example: { button: "button_a1b2c3", container: "container_d4e5f6" }
 */
type CSSModuleClasses = Record<string, string> | undefined;

/**
 * CSS module with metadata and class name exports
 */
interface CSSModule {
  /**
   * Local class name mappings exported by the CSS module
   */
  locals?: Record<string, string>;

  /**
   * Additional module metadata or exports
   */
  [key: string]: unknown;
}

/**
 * Re-exported members from the CSS module (excluding 'default')
 * All named exports from the original CSS module are available here
 */
export * from './css-module';

/**
 * Default export containing the CSS module's local class names
 * 
 * @example
 *