/**
 * Asset module that exports the URL path to a hatch image asset.
 * This module is typically generated by webpack's asset/resource loader
 * which processes image files and outputs them with content hashes.
 */

/**
 * The resolved URL path to the hatch image asset.
 * The path includes a content hash (861ca6c7) for cache busting.
 * 
 * @example
 *