/**
 * Asset module that exports the URL path to the preview list SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module PreviewListAsset
 */

/**
 * The public URL path to the previewlist.92bce88e.svg asset.
 * This path is resolved relative to the application's public path.
 * 
 * @example
 *