/**
 * Asset module that exports the path to a solid point SVG icon.
 * This is typically generated by a bundler's asset/resource module type.
 * 
 * @module SolidPointAsset
 */

/**
 * The public path to the solid point SVG asset.
 * This path is resolved at build time and points to the location
 * where the SVG file will be served from.
 * 
 * @example
 *