/**
 * Asset module that exports the URL path to the mini preview image.
 * This module is typically generated by Webpack's asset module system.
 * 
 * @module MiniPreviewAsset
 */

/**
 * The public URL path to the mini preview PNG image asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *