/**
 * Asset module that exports the URL path to the sun image asset.
 * This module is typically generated by Webpack's asset/resource loader
 * for static image files.
 * 
 * @module SunAssetModule
 */

/**
 * The URL path to the sun.png image asset.
 * This path is resolved at build time by the bundler and points to
 * the final location of the asset in the output directory.
 * 
 * Format: "assets/sun.[contenthash].png"
 * where [contenthash] is a hash generated from the file contents for cache busting.
 * 
 * @example
 *