/**
 * Asset module that exports the URL path to a brick wall loadbearing pattern SVG asset.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module BrickWallLoadbearingPattern
 */

/**
 * The public URL path to the brick wall loadbearing pattern SVG file.
 * This path is resolved relative to the application's public path at build time.
 * 
 * @example
 *