/**
 * Asset module that exports the URL path to a left arrow PNG image.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module LeftArrowAsset
 */

/**
 * The URL path to the left arrow image asset.
 * Points to the compiled/hashed image file in the assets directory.
 * 
 * @example
 *