/**
 * Asset module that exports the URL path to the close button hover state SVG icon.
 * This file is typically auto-generated by build tools during asset processing.
 * 
 * @module CloseHoverAsset
 */

/**
 * The public URL path to the close_hover.svg asset.
 * This path is resolved relative to the application's public asset directory.
 * 
 * @example
 *