/**
 * Webpack asset module for spinner animation GIF.
 * 
 * This module exports the public URL path to a spinner animation asset.
 * The hash '431953af' is typically generated by webpack for cache busting.
 * 
 * @module SpinnerAnimationAsset
 */

/**
 * The public URL path to the spinner animation GIF asset.
 * 
 * This path is resolved at build time by webpack and includes:
 * - The configured public path prefix
 * - The asset filename with content hash for cache invalidation
 * 
 * @example
 *