/**
 * CSS Module type definitions
 * This module represents a CSS module loader configuration and export pattern
 */

/**
 * CSS Module class names mapping
 * Contains all exported class names from the CSS module
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style injection options for CSS modules
 */
export interface StyleInjectionOptions {
  /**
   * Transform function applied to style tags before insertion
   */
  styleTagTransform: () => void;

  /**
   * Function to set attributes on injected style elements
   */
  setAttributes: () => void;

  /**
   * DOM insertion function, typically bound to a specific target element
   * @param target - The target element selector (e.g., "head")
   */
  insert: (target: string) => void;

  /**
   * DOM manipulation API used for style injection
   */
  domAPI: () => void;

  /**
   * Function to create and insert style elements into the DOM
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports
 * Re-exports all named exports from the underlying CSS module
 */
export * from './css-module-source';

/**
 * Default export: CSS module class names
 * Contains the locally scoped class names generated by the CSS module system
 * Returns undefined if no local classes are defined
 */
declare const cssModuleLocals: CSSModuleClasses | undefined;

export default cssModuleLocals;