/**
 * Webpack asset module that exports the URL path to an SVG array icon.
 * This module represents a static asset reference generated by Webpack's asset module system.
 * 
 * @module ArrayIconAsset
 * @description Exports the public path URL for the array.svg icon asset
 */

/**
 * The public URL path to the array SVG icon asset.
 * This path is resolved at build time by Webpack and points to the hashed asset file.
 * 
 * @example
 *