/**
 * Webpack asset module that exports the URL path to the spotlight_normal SVG asset.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module SpotlightNormalAsset
 */

/**
 * The public URL path to the spotlight_normal.svg asset file.
 * This path is resolved at build time by Webpack and includes the content hash
 * for cache busting purposes.
 * 
 * @remarks
 * The actual file hash (bfea9251) may change when the asset content is modified.
 * Webpack's publicPath configuration determines the base URL for this asset.
 */
declare const spotlightNormalAssetUrl: string;

export default spotlightNormalAssetUrl;