/**
 * Asset module that exports the path to the return_all SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for static file imports.
 * 
 * @module ReturnAllAsset
 */

/**
 * The file path to the return_all.svg asset.
 * This path is resolved relative to the application's public path
 * and includes a content hash for cache busting.
 * 
 * @example
 *