/**
 * Webpack asset module that exports the URL path to the warning SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for handling static file imports.
 * 
 * @module WarningIconAsset
 */

/**
 * The public URL path to the warning icon SVG file.
 * This path is resolved at build time by Webpack and includes
 * the configured public path prefix and the asset's hashed filename.
 * 
 * @example
 *