/**
 * Webpack asset module that exports the Korean (ko_KR) resource file path.
 * This module provides the URL to a JSON resource file for Korean localization.
 * 
 * @module ResourceKoKR
 */

/**
 * The public path to the Korean language resource JSON file.
 * This path is dynamically generated by Webpack during the build process
 * and points to the hashed asset file for cache busting.
 * 
 * @constant {string} RESOURCE_KO_KR_PATH - The URL path to the Korean resource JSON file
 * @example
 *