/**
 * Asset module that exports the path to the default window symbol SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DefaultWindowSymbol
 */

/**
 * The public path to the default window symbol SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @type {string}
 * @example "assets/default_window_symbol.e4b4576c.svg"
 */
declare const defaultWindowSymbolPath: string;

export default defaultWindowSymbolPath;