/**
 * CSS Module Definition
 * 
 * This module exports CSS-in-JS functionality with dynamic style injection.
 * Provides type-safe access to CSS module class names and style injection utilities.
 * 
 * @module CSSStyleModule
 */

/**
 * Style loader API configuration options
 */
export interface StyleLoaderOptions {
  /** Transform function to modify style tags before insertion */
  styleTagTransform: () => void;
  /** Function to set attributes on style elements */
  setAttributes: () => void;
  /** DOM insertion strategy function */
  insert: (target: string) => void;
  /** DOM manipulation API */
  domAPI: () => void;
  /** Function to create and insert style elements */
  insertStyleElement: () => void;
}

/**
 * CSS Module locals mapping
 * Maps CSS class names to their transformed equivalents
 */
export type CSSModuleLocals = Record<string, string> | undefined;

/**
 * Default export - CSS module class names
 * Contains the scoped class names generated by CSS modules
 */
declare const cssModuleExport: CSSModuleLocals;
export default cssModuleExport;

/**
 * Re-exported utilities from the style injection library
 * Provides access to all non-default exports from the original module
 */
export * from 'style-injection-library';