/**
 * Asset module that exports the URL path to the hatch_3 image asset.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module HatchAsset
 */

/**
 * The URL path to the hatch_3.jpg image asset.
 * The actual path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *