/**
 * Asset module that exports the file path for the mail SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module MailAsset
 */

/**
 * The public path to the mail icon SVG file.
 * This path is constructed by Webpack during the build process and includes
 * content hash for cache busting.
 * 
 * @constant
 * @type {string}
 * @example
 * // Usage in components
 * import mailIconPath from './mail-asset';
 * <img src={mailIconPath} alt="Mail icon" />
 */
declare const mailAssetPath: string;

export default mailAssetPath;