/**
 * CSS Module loader configuration and exports
 * Handles style injection and CSS module class name mapping
 */

/**
 * CSS Modules class name mapping
 * Maps local class names to generated scoped class names
 */
export interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Style loader options configuration
 */
export interface StyleLoaderOptions {
  /**
   * Function to transform and inject style tags into the DOM
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into a specific DOM location
   * @param target - DOM insertion target (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM manipulation API for style injection
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports type
 */
export interface CSSModuleExports {
  /**
   * Local class name mappings for CSS modules
   * Returns undefined if no local classes are defined
   */
  locals?: CSSModuleClasses;
}

/**
 * Default export: CSS Module class name mappings
 * Contains the locally scoped class names generated by CSS Modules
 */
declare const cssModuleClasses: CSSModuleClasses | undefined;

export default cssModuleClasses;

/**
 * Re-exported named exports from the CSS module
 * Allows importing specific class names directly
 */
export * from './css-module-exports';