/**
 * Asset module that exports the path to the DIY material SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * to handle static file imports with content hashing for cache busting.
 * 
 * @module DiyMaterialAsset
 */

/**
 * The public path to the DIY material SVG asset.
 * The filename includes a content hash (e3c4179a) for cache invalidation.
 * 
 * @example
 *