/**
 * Asset module that exports the URL path to the center SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module CenterIconAsset
 */

/**
 * The public URL path to the center.svg icon asset.
 * The hash (ed719abe) in the filename is used for cache busting.
 * 
 * @example
 *