/**
 * Asset module that exports the path to the cancel icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module CancelIconAsset
 */

/**
 * The public path to the cancel icon SVG asset.
 * This path is resolved relative to the application's public directory.
 * 
 * @example
 *