/**
 * Asset module that exports the path to the hide icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module HideIconAsset
 */

/**
 * The public path to the hide icon SVG asset.
 * This path is resolved by the bundler and points to the compiled asset location.
 * 
 * @example
 *