/**
 * Webpack asset module that exports the URL path to a flatlight normal SVG asset.
 * This is typically auto-generated by Webpack's asset/resource module loader.
 * 
 * @module FlatLightNormalAsset
 */

/**
 * The public URL path to the flatlight_normal.svg asset.
 * This path is resolved at build time by Webpack and includes the content hash for cache busting.
 * 
 * @example
 *