/**
 * Asset module that exports the path to the merge wall SVG image.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module MergeWallAsset
 */

/**
 * The public path URL to the merge wall SVG asset.
 * The actual path is resolved at build time by the bundler.
 * 
 * @example
 *