/**
 * Asset module that exports the path to the closed_normal SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module ClosedNormalIcon
 */

/**
 * The public URL path to the closed_normal.svg asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *