/**
 * Asset module that exports the URL path to a triangle SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module TriangleAsset
 */

/**
 * The public URL path to the triangle SVG asset.
 * This path is resolved relative to the application's public path at build time.
 * 
 * @example
 *