/**
 * Asset module that exports the path to a gypsum wall load-bearing pattern SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module GypsumWallLoadBearingPattern
 */

/**
 * The relative or absolute URL path to the gypsum wall load-bearing pattern SVG asset.
 * This path is resolved at build time by the bundler and includes content hash for cache busting.
 * 
 * @example
 *