/**
 * Asset module that exports the URL path to the Homestyler SVG logo.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module homestyler-logo
 */

/**
 * The public URL path to the Homestyler logo SVG file.
 * The file is served from the assets directory with a content hash for cache busting.
 * 
 * @example
 *