/**
 * Asset module that exports the path to the default electrical box symbol SVG.
 * This is typically generated by Webpack's asset/resource module type.
 * 
 * @module DefaultElecboxSymbol
 */

/**
 * The public path to the default electrical box symbol SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *