/**
 * Asset module that exports the path to the close icon SVG file.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module CloseIconAsset
 */

/**
 * The public path to the close icon SVG asset.
 * This path is resolved at build time and points to the optimized asset location.
 * 
 * @example
 *