/**
 * Asset module that exports the path to the ceiling cursor file.
 * This module represents a static asset import that Webpack processes
 * and returns the public URL path to the cursor resource.
 */

/**
 * The public URL path to the ceiling cursor asset file.
 * This is automatically generated by the build system and points to
 * the hashed asset file in the output directory.
 * 
 * @example
 *