/**
 * Asset module that exports the URL path to a private icon SVG file.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 * 
 * @module PrivateIconAsset
 */

/**
 * The public URL path to the private.svg icon asset.
 * This path is resolved relative to the application's public path at build time.
 * 
 * @example
 *