/**
 * Asset module that exports the path to a normal state SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for handling static image files.
 * 
 * @module NormalIconAsset
 */

/**
 * The public path to the normal state SVG icon asset.
 * This path is resolved at build time and includes the content hash
 * for cache busting purposes.
 * 
 * @example
 *