/**
 * Asset module that exports the URL path to the arrow-up SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for static file imports.
 * 
 * @module ArrowUpAsset
 */

/**
 * The public URL path to the arrow-up SVG icon asset.
 * 
 * The path is resolved at build time by the bundler and points to
 * the optimized/hashed asset file in the output directory.
 * 
 * @example
 *