/**
 * SVG asset module export
 * @description Exports the URL path to the upload cloud blue SVG icon asset.
 * This is typically generated by Webpack's asset/resource module type.
 */

/**
 * The public URL path to the upload_cloud_blue.svg asset
 * @remarks
 * The actual path is resolved at build time by the bundler and includes:
 * - The configured public path
 * - The assets directory
 * - The filename with content hash for cache busting
 */
declare const assetUrl: string;

export default assetUrl;