/**
 * Asset module that exports the file path for the zoom-in SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module ZoomInAsset
 */

/**
 * The public URL path to the zoom-in SVG icon asset.
 * This path is resolved relative to the application's public path and can be used
 * directly in img src attributes or as a CSS background-image.
 * 
 * @example
 *