/**
 * Asset module that exports the path to a dropdown SVG icon.
 * This file is typically generated by a bundler's asset handling system.
 * 
 * @module DropDownAsset
 */

/**
 * The public path to the dropdown SVG asset.
 * This path is resolved at build time and includes cache-busting hash.
 * 
 * @example
 *