/**
 * Asset module that exports the path to a question icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module QuestionIconAsset
 * @description Provides the public URL path for the question mark icon used in the UI
 */

/**
 * The public URL path to the question icon SVG asset.
 * This path is resolved relative to the application's public asset directory.
 * 
 * @example
 * import questionIconUrl from './questionIcon';
 * <img src={questionIconUrl} alt="Question mark icon" />
 */
declare const questionIconUrl: string;

export default questionIconUrl;