/**
 * Asset module that exports the path to the delete icon SVG file.
 * This module is generated by webpack's asset/resource module type.
 * 
 * @module DeleteIconAsset
 */

/**
 * The public URL path to the delete icon SVG asset.
 * This path is resolved at build time by webpack and points to the
 * optimized asset in the output directory.
 * 
 * @example
 *