const CommandTypes = {
    ActiveLayer: "hsw.cmd.layer.CmdActiveLayer",
    AddNewLayer: "hsw.cmd.layer.CmdAddLayer",
    InsertLayer: "hsw.cmd.layer.CmdInsertLayer",
    ResetLayerIndex: "hsw.cmd.layer.CmdResetLayerIndex",
    DeleteLayer: "hsw.cmd.layer.CmdDeleteLayer",
    DeleteLayers: "hsw.cmd.layer.CmdDeleteLayers",
    ChangeLayerVisibility3d: "hsw.cmd.layer.CmdChangeLayerVisibility3d",
    CleanupLayer: "hsw.cmd.layer.CmdCleanupLayer",
    CleanupAllLayer: "hsw.cmd.layer.CmdCleanupAllLayer",
    ToggleLayerVisibility: "hsw.cmd.layer.CmdToggleLayerVisibility",
    ChangeLayerHeight: "hsw.cmd.layer.CmdChangeLayerHeight",
    ExportImage: "hsw.plugin.export.CmdExportImage",
    DeleteSelection: "hsw.cmd.selection.CmdDelete",
    DuplicateSelection: "hsw.cmd.selection.CmdDuplicate",
    PointSelect: "hsw.cmd.selection.CmdPointSelect",
    ElevationSelect: "hsw.cmd.selection.CmdElevationSelect",
    WindowSelect: "hsw.cmd.selection.CmdWindowSelect",
    MoveUnderlay: "hsw.cmd.underlay.CmdMoveUnderlay",
    UpdateUnderlay: "hsw.cmd.underlay.CmdUpdateUnderlay",
    Copy: "hsw.plugin.editor.CmdCopy",
    Paste: "hsw.plugin.editor.CmdPaste",
    Duplicate: "hsw.plugin.editor.CmdDuplicate",
    PasteSequence: "hsw.plugin.editor.CmdPasteSequence",
    DuplicateSequence: "hsw.plugin.editor.CmdDuplicateSequence",
    Cut: "hsw.plugin.editor.CmdCut",
    CreateStylerTemplate: "hsw.plugin.autostyler.CmdCreateStylerTemplate",
    ImportStylerTemplate: "hsw.plugin.autostyler.CmdImportStylerTemplate",
    EditStylerTemplate: "hsw.plugin.autostyler.CmdEditStylerTemplate",
    CmdRestoreTemplate: "hsw.plugin.autostyler.CmdRestoreTemplate",
    AddMultiProducts: "hsw.plugin.autostyler.AddMultiProducts",
    CmdAddProducts: "hsw.plugin.autostyler.CmdAddProducts",
    MeasureTool: "hsw.plugin.measuretool.CmdMeasureTool",
    MeasureTool3D: "hsw.plugin.measuretool.CmdMeasureTool3d",
    EnterCabinetApp: "hsw.plugin.customizedcabinet.CmdEnterCabinetApp",
    CmdChangeComponentPosition: "hsw.plugin.customizedcabinet.CmdChangeComponentPosition",
    CmdChangeDrawerPosition: "hsw.plugin.customizedcabinet.CmdChangeDrawerPosition",
    MaterialBrush: "hsw.plugin.materialbrush.MaterialBrush",
    FloorplanMirror: "hsw.plugin.floorplanmirror.CmdMirror",
    CreateOutdoorSpace: "hsw.cmd.layer.CmdCreateOutdoorSpace",
    DeleteOutdoorSpace: "hsw.cmd.layer.CmdDeleteOutdoorSpace",
    DivideSpace: "hsw.cmd.layer.CmdDivideSpace",
    AlignLayers: "hsw.cmd.layer.CmdAlignLayers",
    RenameLayer: "hsw.cmd.layer.RenameLayer",
    CopyPasteRooms: "hsw.cmd.layer.CmdCopyPasteRooms",
    ReplaceProductStyleChange: "hsw.plugin.customization.CmdReplaceProductStyleChange",
    AutoSelect: "hsw.plugin.customization.AutoSelect",
    SelectLines: "hsw.plugin.customization.SelectLines",
    CreateAuxiliaryLine: "hsw.plugin.auxiliaryline.CmdCreateAuxiliaryLine",
    RemoveAuxiliaryLines: "hsw.plugin.auxiliaryline.CmdRemoveAuxiliaryLines",
    Guideline: "hsw.plugin.layeredit.CmdSlabEditGuideLine",
    HomeGptSmartLayout: "hsw.plugin.layeredit.CmdHomeGptSmartLayout",
    ApplyMoodBoardLayout: "hsw.plugin.constraintlayout.CmdApplyMoodBoardLayout"
} as const;

export type CommandType = typeof CommandTypes[keyof typeof CommandTypes];

export default CommandTypes;