/**
 * Asset module that exports the URL path to the readonly icon SVG file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static assets like images and SVG files.
 */

/**
 * The public URL path to the readonly icon SVG asset.
 * This path is resolved at build time and includes the content hash
 * for cache busting (7afd3c93).
 * 
 * @example
 *