/**
 * Asset module that exports the resolved path to the logo SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module AssetModule
 */

/**
 * The resolved public path to the logo SVG asset.
 * The path is constructed by combining the Webpack public path with the asset filename.
 * 
 * @example
 *