const ContentCommands = {
    AddProduct: "hsw.cmd.content.CmdAddProduct",
    DeleteContent: "hsw.cmd.content.CmdDeleteContent",
    DisplayAllContent: "hsw.cmd.content.CmdDisplayAllContent",
    DisplayContent: "hsw.cmd.content.CmdDisplayContent",
    DisplayContents: "hsw.cmd.content.CmdDisplayContents",
    DuplicateContent: "hsw.cmd.content.CmdDuplicateContent",
    MoveContent: "hsw.cmd.content.CmdMoveContent",
    MoveContents: "hsw.cmd.content.CmdMoveContents",
    MoveOpening: "hsw.cmd.content.CmdMoveOpening",
    RotateHole: "hsw.cmd.content.CmdRotateHole",
    MoveParametricBackgroundWall: "hsw.cmd.content.CmdMoveParametricBackgroundWall",
    MoveNCPBackgroundWallUnit: "hsw.cmd.content.CmdMoveNCPBackgroundWallUnit",
    ReplaceContent: "hsw.cmd.content.CmdReplaceContent",
    SmartReplaceContent: "hsw.plugin.contextualtools.CmdSmartReplaceContent",
    FlipContent: "hsw.cmd.content.CmdFlipContent",
    CreateParametricCeiling: "hsw.plugin.content.CmdCreateParametricCeiling",
    CmdContentArray: "hsw.plugin.content.CmdContentArray",
    EditParametricBackgroundWallIsAutoFit: "hsw.cmd.content.CmdEditParametricBackgroundWallIsAutoFit",
    CmdContentArcArray: "hsw.plugin.content.CmdContentArcArray",
    MoveInHardDecoration: "hsw.cmd.harddecoration.MoveInHardDecoration",
    MoveNCPBgWallInWFA: "hsw.cmd.harddecoration.MoveNCPBgWallInWFA",
    RotateInHardDecoration: "hsw.cmd.harddecoration.RotateInHardDecoration",
    ResizeInHardDecoration: "hsw.cmd.harddecoration.ResizeInHardDecoration",
    FlipOpening: "hsw.cmd.content.CmdFlipOpening",
    NudgeContent: "hsw.plugin.contentmanipulation.CmdNudgeContent",
    ResizeContent: "hsw.plugin.contentmanipulation.CmdResizeContent",
    Resize3DContent: "hsw.plugin.contentmanipulation.CmdResize3DContent",
    ResizeContents: "hsw.plugin.contentmanipulation.CmdResizeContents",
    RotateContent: "hsw.cmd.content.CmdRotateContent",
    RotateContents: "hsw.cmd.content.CmdRotateContents",
    ApplyToWholeWall: "hsw.plugin.wallboard.CmdApplyToWholeWall",
    ApplyToEntireRoom: "hsw.plugin.wallboard.CmdApplyToEntireRoom",
    ResizeWallBoard: "hsw.plugin.wallboard.CmdResizeWallBoard",
    ChangeNCPBackgroundWallBase: "hsw.plugin.contentmanipulation.CmdChangeNCPBackgroundWallBase",
    ChangeParametricContentBase: "hsw.plugin.contentmanipulation.CmdChangeParametricContentBase",
    PlaceProduct: "hsw.plugin.catalog.CmdPlaceProduct",
    OpenIndependentPanel: "hsw.plugin.catalog.CmdOpenIndependentPanel",
    CreateWallAttachedCustomizedModel: "hsw.plugin.customizedmodeling.CmdCreateWallAttachedCustomizedModel",
    CreateRoomAttachedCustomizedModel: "hsw.plugin.customizedmodeling.CmdCreateRoomAttachedCustomizedModel",
    EditCustomizedModel: "hsw.plugin.customizedmodeling.CmdEditCustomizedModel",
    EditCustomizedModelType: "hsw.plugin.customizedmodeling.CmdEditCustomizedModelType",
    EditParametricCeiling: "hsw.plugin.customizedmodeling.CmdEditParametricCeiling",
    EditCustomizedMolding: "hsw.plugin.customizedmodeling.CmdEditCustomizedMolding",
    CreateRoomAttachedCustomizedPModel: "hsw.plugin.customizedpm.CmdCreateRoomAttachedCustomizedPModel",
    EditCustomizedPModel: "hsw.plugin.customizedpm.CmdEditCustomizedPModel",
    EditCustomizedPModelType: "hsw.plugin.customizedpm.CmdEditCustomizedPModelType",
    EditDoorStone: "hsw.plugin.doorstone.CmdEditDoorStone",
    DoorStonesStatus: "hsw.plugin.doorstone.CmdDoorStonesStatus",
    ToggleDoorStoneAlign: "hsw.plugin.doorstone.CmdToggleDoorStoneAlign",
    ApplyDoorStoneToAllDoors: "hsw.plugin.doorstone.CmdApplyDoorStoneToAllDoors",
    EditCurtainCloth: "hsw.plugin.curtain.CmdEditCurtainCloth",
    EditCurtain: "hsw.plugin.curtain.CmdEditCurtain",
    AddCustomizationProduct: "hsw.plugin.customization.AddCustomizationProduct",
    SelectCustomizationInnerSpace: "hsw.plugin.customization.InnerSpace",
    ResizeCustomizationProduct: "hsw.plugin.customization.ResizeCustomization",
    EditCornerWindow: "hsw.cmd.content.CmdEditCornerWindow",
    ChangeCornerWindow: "hsw.cmd.content.CmdChangeCornerWindow",
    ApplyParamsToAllCornerWindow: "hsw.cmd.content.CmdApplyParamsToAllCornerWindow",
    CmdAlign: "hsw.cmd.content.CmdAlign"
} as const;

export type ContentCommandKey = keyof typeof ContentCommands;
export type ContentCommandValue = typeof ContentCommands[ContentCommandKey];

export default ContentCommands;