/**
 * Webpack asset module that exports the URL path to a cursor file.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling .cur (cursor) files.
 */

/**
 * The resolved public path URL to the forbidden cursor asset.
 * This path is generated at build time by Webpack and points to the
 * hashed cursor file in the assets directory.
 * 
 * @example
 * // Usage in application code:
 * // import cursorPath from './assets/forbiden.cur';
 * // element.style.cursor = `url(${cursorPath}), auto`;
 */
declare const cursorAssetPath: string;

export default cursorAssetPath;