/**
 * Asset module that exports the URL path to a normal state SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module NormalIconAsset
 */

/**
 * The public URL path to the normal.svg icon asset.
 * This path is resolved by the bundler and points to the location
 * where the SVG file is served in the production build.
 * 
 * Format: "assets/normal.85f1a1be.svg"
 * The hash (85f1a1be) is typically generated during build for cache busting.
 */
declare const normalIconPath: string;

export default normalIconPath;