/**
 * Webpack asset module that exports the public URL path to the orbit camera SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module OrbitCameraSVG
 */

/**
 * The public URL path to the orbit camera SVG asset.
 * This path is resolved at build time by Webpack and includes the content hash
 * for cache busting (dc70c90b).
 * 
 * @example
 *