/**
 * Asset module that exports the URL path to a mask SVG file.
 * This module is typically auto-generated by Webpack's asset/resource module type.
 * 
 * @module AssetMaskSVG
 */

/**
 * The public URL path to the mask.svg asset file.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *