/**
 * Asset module that exports the URL path to the Handle4 image asset.
 * This module is typically generated by Webpack's asset/resource loader
 * for static image files.
 * 
 * @module Handle4Asset
 */

/**
 * The public URL path to the Handle4.png image asset.
 * The hash 'ed858116' is used for cache busting.
 * 
 * @example
 *