/**
 * Iterator cleanup helper function
 * Ensures proper cleanup of iterators by calling their return method if available
 * This is typically generated by TypeScript for for-of loops and similar constructs
 */

/**
 * Cleans up an iterator by calling its return method
 * @param iterator - The iterator object to clean up
 * @param shouldSkip - Flag to skip cleanup if true
 * @param hasError - Flag indicating if an error occurred
 * @param error - The error to be re-thrown after cleanup
 * @throws Re-throws the provided error after cleanup if hasError is true
 */
declare function cleanupIterator(
  iterator: Iterator<unknown> | null | undefined,
  shouldSkip: boolean,
  hasError: boolean,
  error: unknown
): void;

/**
 * Type definition for an iterator with an optional return method
 */
interface IteratorWithReturn<T = unknown> extends Iterator<T> {
  return?(): IteratorResult<T>;
}

/**
 * Iterator result type
 */
interface IteratorResult<T> {
  done: boolean;
  value: T;
}

/**
 * Basic iterator interface
 */
interface Iterator<T> {
  next(value?: unknown): IteratorResult<T>;
  return?(value?: unknown): IteratorResult<T>;
  throw?(e?: unknown): IteratorResult<T>;
}