/**
 * Webpack asset module that exports the URL path to the measuring SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module MeasuringSvgAsset
 */

/**
 * The public URL path to the measuring.svg asset file.
 * This path is resolved at build time by webpack and includes the content hash
 * for cache busting (766af82d).
 * 
 * @example
 *