/**
 * Webpack asset module that exports the URL path to a wall settings SVG icon.
 * This module represents a static asset reference that would typically be processed
 * by Webpack's asset/resource module type.
 * 
 * @module WallSettingSvgAsset
 */

/**
 * The public URL path to the wall_setting.svg asset.
 * In a production build, this would be resolved to the full path including
 * the public path configured in Webpack (e.g., "/assets/wall_setting.d5997475.svg").
 * 
 * The hash (d5997475) in the filename is typically generated by Webpack for cache-busting purposes.
 */
declare const wallSettingSvgUrl: string;

export default wallSettingSvgUrl;