/**
 * Asset module that exports the URL path to the report SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module ReportAsset
 */

/**
 * The public URL path to the report.svg asset file.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *