/**
 * Asset module that exports the URL path to a handler SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for static file imports.
 * 
 * @module HandlerAsset
 */

/**
 * The public URL path to the handler_90 SVG asset.
 * This path is resolved at build time and includes the content hash
 * for cache busting.
 * 
 * @example
 *