/**
 * Webpack asset module that exports the URL path to the splitWall SVG asset.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module SplitWallAsset
 */

/**
 * The public URL path to the splitWall.svg asset.
 * This path is resolved at build time by Webpack and includes the content hash
 * for cache busting (c85e6b5a).
 * 
 * @example
 *