/**
 * Webpack asset module that exports the URL path to the toolbar import SVG icon.
 * 
 * This module provides access to a static asset (SVG file) used in the application's toolbar.
 * The path is automatically generated by Webpack's asset bundling system.
 * 
 * @module ToolbarImportAsset
 */

/**
 * The public URL path to the toolbar import SVG icon.
 * 
 * This path is resolved at build time by Webpack and points to the bundled
 * location of the 'toolbarimport.7776a36b.svg' asset file.
 * 
 * @example
 *