/**
 * CSS Module loader type definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack css-loader with modules enabled.
 */

/**
 * CSS Module class names mapping
 * Maps CSS class names to their hashed/scoped equivalents
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader options configuration
 */
export interface StyleLoaderOptions {
  /**
   * Transforms style tag before insertion into DOM
   */
  styleTagTransform: () => void;
  
  /**
   * Sets attributes on the style element
   */
  setAttributes: () => void;
  
  /**
   * Inserts style element into specified DOM location
   * Bound to "head" element by default
   */
  insert: (target: string) => void;
  
  /**
   * DOM manipulation API adapter
   */
  domAPI: () => void;
  
  /**
   * Creates and configures the style element
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports
 * Contains the scoped class name mappings from the CSS file
 * Returns undefined if no locals (class names) are defined
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-exported named exports from the CSS module
 * Allows importing specific class names directly
 */
export * from './style-module';