/**
 * Asset module that exports the path to the new cabinet SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for handling static SVG files.
 * 
 * @module NewCabinetAsset
 */

/**
 * The public URL path to the new cabinet SVG asset.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *