/**
 * Asset module that exports the URL path to a preview SVG image.
 * This module is typically generated by webpack's asset/resource module type.
 * @module PreviewAsset
 */

/**
 * The public URL path to the preview.svg asset.
 * This path is resolved relative to the application's public path at build time.
 * @example
 * // Usage in a component:
 * import previewUrl from './preview-asset';
 * <img src={previewUrl} alt="Preview" />
 */
declare const previewAssetUrl: string;

export default previewAssetUrl;