/**
 * CSS Module Type Definitions
 * 
 * This module represents a CSS-in-JS module that exports class name mappings.
 * It uses style-loader to inject styles and exports the resulting CSS module locals.
 */

/**
 * CSS module class name mappings exported by this module.
 * Contains the locally scoped class names generated by CSS Modules.
 */
export type CSSModuleLocals = Record<string, string> | undefined;

/**
 * Configuration options for style injection.
 */
export interface StyleLoaderOptions {
  /**
   * Function to transform and insert style tags into the DOM
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into a specific DOM location
   * @param target - The DOM selector or element to insert into (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM API utilities for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * Re-exported members from the CSS module (excluding 'default')
 */
export * from './styles.module.css';

/**
 * Default export: CSS Module class name mappings.
 * Returns an object mapping CSS class names to their scoped equivalents,
 * or undefined if no locals are defined.
 */
declare const cssModuleLocals: CSSModuleLocals;
export default cssModuleLocals;