/**
 * CSS Module type definitions
 * 
 * This module handles CSS-in-JS module loading with style injection.
 * Typically generated by webpack's style-loader and css-loader chain.
 */

/**
 * CSS Module class names mapping
 * Maps semantic class name keys to generated/hashed class name values
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader options for runtime style injection
 */
export interface StyleLoaderOptions {
  /**
   * Transform function to manipulate style tag before insertion
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set custom attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * DOM insertion strategy - specifies where to inject style tags
   * @param target - Target element selector (e.g., "head", "body")
   */
  insert: (target: string) => void;
  
  /**
   * DOM API adapter for style manipulation operations
   */
  domAPI: () => void;
  
  /**
   * Factory function to create style DOM elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS module export with optional locals (class name mappings)
 */
export interface CSSModuleExport {
  /**
   * Locale class name mappings for CSS modules
   * Contains the actual CSS class names that can be used in components
   */
  locals?: CSSModuleClasses;
}

/**
 * Default export: CSS module class names or undefined
 * 
 * Use this to access CSS module class names in your components:
 * @example
 * import styles from './styles.module.css';
 * <div className={styles.container} />
 */
declare const cssModuleClasses: CSSModuleClasses | undefined;

export default cssModuleClasses;