/**
 * Asset module that exports the path to a render SVG file.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static assets like images and SVGs.
 * 
 * @module render-asset
 */

/**
 * The public path to the render.svg asset file.
 * This path is resolved relative to the application's public URL
 * and includes a content hash (58f2d7a6) for cache busting.
 * 
 * @example
 *