/**
 * Webpack asset module that exports the URL path to a zoom-in SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module ZoomInAsset
 */

/**
 * The public URL path to the zoom-in SVG icon asset.
 * This path is resolved by the Webpack bundler at build time and includes
 * the public path prefix configured in webpack.config.
 * 
 * @example
 *