/**
 * Webpack asset module export
 * Exports the public URL path for the fliproom hover SVG asset.
 * This module is typically generated by webpack's asset/resource loader.
 */

/**
 * Public URL path to the fliproom hover SVG asset.
 * The path is resolved relative to the webpack public path configuration.
 * 
 * @example
 *