/**
 * Webpack asset module that exports the URL path to a material SVG file.
 * This module is typically generated by Webpack's asset/resource loader
 * for static file imports.
 * 
 * @module MaterialAsset
 */

/**
 * The public URL path to the material.svg asset file.
 * This path is resolved by the bundler and points to the hashed asset
 * in the output directory (e.g., "assets/material.0b1ea42b.svg").
 * 
 * @example
 *