/**
 * CSS Module loader type definitions
 * 
 * This module handles CSS-in-JS style injection and provides typed access to CSS module class names.
 * Typically generated by webpack's style-loader + css-loader with modules enabled.
 */

/**
 * CSS Modules class name mapping
 * Maps semantic class identifiers to their hashed/scoped counterparts
 * 
 * @example
 *