/**
 * CSS Module Loader Type Definitions
 * 
 * This module defines types for dynamically loaded CSS modules with style injection.
 * Typically generated by webpack's css-loader and style-loader chain.
 */

/**
 * CSS Module class name mappings.
 * Maps CSS class names to their scoped/hashed equivalents.
 * 
 * @example
 *