/**
 * CSS Module type definitions
 * 
 * This module represents a CSS-in-JS module that exports class name mappings
 * and style injection utilities for use in TypeScript applications.
 */

/**
 * CSS Module class name mappings
 * 
 * Contains the locally scoped CSS class names generated by CSS Modules.
 * Each property key corresponds to a class name in the source CSS file,
 * and the value is the transformed/hashed class name.
 */
export interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Style injection configuration options
 * 
 * Configuration object for controlling how styles are injected into the DOM.
 */
export interface StyleInjectionOptions {
  /**
   * Transform function applied to style tags before insertion
   */
  styleTagTransform?: (css: string, style: HTMLStyleElement) => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes?: (element: HTMLStyleElement) => void;
  
  /**
   * DOM insertion function
   * @param target - Target element selector (e.g., "head", "body")
   * @param element - Style element to insert
   */
  insert?: (target: string, element: HTMLStyleElement) => void;
  
  /**
   * DOM API implementation for style manipulation
   */
  domAPI?: {
    update: (element: HTMLStyleElement) => void;
    remove: (element: HTMLStyleElement) => void;
  };
  
  /**
   * Factory function to create style elements
   */
  insertStyleElement?: (options: StyleInjectionOptions) => HTMLStyleElement;
}

/**
 * CSS Module export
 * 
 * The default export is either:
 * - An object mapping CSS class names to their scoped identifiers
 * - undefined if no locals are defined
 */
declare const cssModuleLocals: CSSModuleClasses | undefined;

export default cssModuleLocals;

/**
 * Re-exported utilities from the style loader module
 * 
 * These exports provide access to the underlying style injection utilities
 * for advanced use cases where manual control over style loading is needed.
 */
export * from './style-loader-utilities';