/**
 * Asset module that exports the path to a delete icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DeleteIconAsset
 */

/**
 * The public path to the delete icon SVG asset.
 * This path is resolved at build time and points to the bundled asset location.
 * 
 * @example
 *