/**
 * CSS Module Type Definitions
 * 
 * This module represents a CSS module loader configuration with style injection utilities.
 * Typically generated by webpack css-loader + style-loader for CSS Modules.
 */

/**
 * Style injection configuration object
 * Contains methods for DOM manipulation and style tag management
 */
interface StyleLoaderConfig {
  /**
   * Transform function applied to style tags before insertion
   */
  styleTagTransform: StyleTagTransformFunction;
  
  /**
   * Sets attributes on the style element
   */
  setAttributes: SetAttributesFunction;
  
  /**
   * Inserts the style element into the specified DOM location
   * Bound to insert into <head> by default
   */
  insert: InsertFunction;
  
  /**
   * DOM API implementation for style manipulation
   */
  domAPI: DOMAPIFunction;
  
  /**
   * Creates and returns a style element
   */
  insertStyleElement: InsertStyleElementFunction;
}

/**
 * Function that transforms style content before injection
 */
type StyleTagTransformFunction = () => void;

/**
 * Function that sets custom attributes on style elements
 */
type SetAttributesFunction = () => void;

/**
 * Function that inserts style elements into the DOM
 * @param target - The DOM location to insert into (e.g., "head")
 */
type InsertFunction = (target: string) => void;

/**
 * DOM API wrapper for style manipulation operations
 */
type DOMAPIFunction = () => void;

/**
 * Function that creates a <style> element
 */
type InsertStyleElementFunction = () => void;

/**
 * CSS Module exports
 * Maps CSS class names to their hashed equivalents
 */
interface CSSModuleClasses {
  readonly [key: string]: string;
}

/**
 * CSS Module with metadata
 */
interface CSSModule {
  /**
   * Exported CSS class name mappings
   */
  locals?: CSSModuleClasses;
  
  [key: string]: unknown;
}

/**
 * Default export: CSS class name mappings for this module
 * Returns undefined if no locals are defined
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-export all named exports from the CSS module
 * (Preserves any additional metadata or functions exported by the CSS loader)
 */
export * from './source-css-module';