/**
 * Asset module that exports the path to a loading spinner SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module LoadingSVGAsset
 */

/**
 * The public URL path to the loading spinner SVG asset.
 * This path is resolved by the bundler and points to the optimized asset location.
 * 
 * @example
 *