/**
 * Asset module that exports the URL path to the snapshot SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for static file imports.
 * 
 * @module SnapshotAsset
 */

/**
 * The public URL path to the snapshot.svg asset file.
 * This path is resolved at build time and includes the content hash
 * for cache busting (428f0df0).
 * 
 * @example
 *