/**
 * Asset module that exports the URL path to the saveas SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for static file imports.
 * 
 * @module SaveAsAsset
 */

/**
 * The public URL path to the saveas.svg icon asset.
 * This path is resolved by the bundler and points to the hashed asset file
 * in the output directory (e.g., "assets/saveas.5641b7f7.svg").
 * 
 * @type {string}
 */
declare const saveAsIconPath: string;

export default saveAsIconPath;