/**
 * Asset module that exports the URL path to the watermarked image asset.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module WatermarkAsset
 */

/**
 * The public URL path to the fingerprint watermark image (after processing).
 * This path is resolved at build time by the bundler and points to the
 * optimized asset in the output directory.
 * 
 * @example
 *