/**
 * Asset module that exports the file path for the fingerprint watermark image (before state).
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module fp_watermark_before
 * @description Provides the public URL path to the watermark image asset used for fingerprint visualization
 */

/**
 * The public URL path to the fingerprint watermark "before" state image asset.
 * This path is resolved by the build system and includes content hash for cache busting.
 * 
 * @example
 *