/**
 * Asset module that exports the URL path to the new icon SVG file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static assets like images and SVG files.
 * 
 * @module NewIconAsset
 */

/**
 * The public URL path to the new icon SVG asset.
 * This path is resolved at build time and includes the content hash
 * for cache busting purposes.
 * 
 * @example
 *