/**
 * Asset module that exports the URL path to the help SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module HelpIconAsset
 */

/**
 * The public URL path to the help icon SVG asset.
 * This path is resolved at build time and points to the bundled asset location.
 * 
 * @example
 *