/**
 * Asset module that exports the path to an info icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module InfoIconAsset
 */

/**
 * The public path to the info icon SVG asset.
 * This path is resolved at build time and points to the bundled asset location.
 * 
 * @example
 *