/**
 * Asset module that exports the path to the ruler hover SVG icon.
 * This file is typically auto-generated by build tools to handle static asset imports.
 * 
 * @module RulerHoverAsset
 */

/**
 * The public URL path to the ruler hover SVG asset.
 * This path is resolved at build time and points to the versioned asset file.
 * 
 * @example
 *