/**
 * Asset module that exports the path to the replace material SVG icon.
 * This module is typically generated by Webpack's asset/resource module type,
 * which handles importing files and returns their public URL.
 * 
 * @module ReplaceMaterialAsset
 */

/**
 * The public URL path to the replace material SVG asset.
 * This path is resolved relative to the application's public path and
 * can be used directly in img src attributes or as a reference to the SVG file.
 * 
 * @constant {string} REPLACE_MATERIAL_ICON_PATH
 * @example
 *