/**
 * Asset module that exports the URL path to the temproom3 SVG image.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 * 
 * @module temproom3Asset
 */

/**
 * The public URL path to the temproom3.svg asset file.
 * This string can be used directly in img src attributes or as a background-image URL.
 * 
 * @example
 *