/**
 * Webpack asset module that exports the URL path to a static SVG file.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static file imports.
 * 
 * Original Module ID: 884666
 * Asset: temproom5.svg
 */

/**
 * The public URL path to the temproom5 SVG asset.
 * This path is resolved by the bundler and points to the processed asset
 * with a content hash (3d27cbe9) in the filename for cache busting.
 * 
 * @example
 *