/**
 * CSS Module type definitions
 * 
 * This module handles CSS-in-JS style injection and exports typed CSS class names.
 * Typically generated by Webpack css-loader with modules enabled.
 */

/**
 * CSS class name mappings exported by the CSS module.
 * Maps local class names to their hashed/scoped equivalents.
 * 
 * @example
 *