/**
 * Share icon asset module
 * 
 * This module provides the path to the share icon SVG asset.
 * The asset is processed by the build system and the path includes a content hash
 * for cache busting purposes.
 * 
 * @module ShareAsset
 */

/**
 * Path to the share icon SVG asset
 * 
 * This path is automatically generated by the build system and includes:
 * - The configured public path
 * - The asset filename with content hash (share.419cf552.svg)
 * 
 * @example
 *