/**
 * Asset module that exports the URL path to the lock SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for static file imports.
 * 
 * @module LockIconAsset
 */

/**
 * The public URL path to the lock.svg icon asset.
 * Points to the bundled SVG file in the assets directory.
 * 
 * @example
 *