/**
 * Webpack asset module that exports the URL path to a static SVG resource.
 * This module is typically generated by Webpack's asset/resource loader for image files.
 * 
 * @module ReplaceIconAsset
 */

/**
 * The public URL path to the replace icon SVG asset.
 * This path is resolved by the Webpack bundler and points to the final location
 * of the asset in the build output directory.
 * 
 * @example
 *