/**
 * SVG asset module that exports the path to the room templates illustration.
 * This file is typically generated by a bundler's asset handling system.
 * 
 * @module RoomTemplatesAsset
 */

/**
 * The URL path to the room templates SVG asset.
 * Points to a hashed SVG file in the assets directory for cache busting.
 * 
 * @example
 *