/**
 * Asset module that exports the URL path to a loading GIF image.
 * This module is typically generated by webpack's asset/resource module type
 * when processing image files.
 * 
 * @module LoadingAsset
 */

/**
 * The public URL path to the loading spinner GIF image.
 * This path is resolved relative to the application's public path
 * and can be used directly in img src attributes or CSS background-image properties.
 * 
 * @example
 *