/**
 * Static asset module that exports the URL path to the replace material SVG icon.
 * This file is typically auto-generated by build tools to handle static asset imports.
 * 
 * @module ReplaceMaterialAsset
 */

/**
 * The public URL path to the replace_material SVG asset.
 * Points to the bundled and hashed SVG file in the assets directory.
 * 
 * @example
 *