/**
 * Asset module that exports the URL path to the temproom2 SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module TempRoom2Asset
 */

/**
 * The public URL path to the temproom2 SVG asset.
 * This path is constructed by combining the webpack public path with the hashed filename.
 * 
 * @example
 *