/**
 * Asset module that exports the path to the settings icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static assets like images and SVG files.
 * 
 * @module SettingIcon
 */

/**
 * The public path to the setting icon SVG asset.
 * This path is resolved at build time by the bundler and points to
 * the processed asset in the output directory.
 * 
 * @type {string}
 * @example
 *