/**
 * Asset module that exports the path to the fliproom SVG icon.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static assets like images and fonts.
 */

/**
 * The public path to the fliproom SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *