/**
 * Webpack asset module that exports the URL path to a duplicate icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DuplicateIconAsset
 */

/**
 * The URL path to the duplicate icon SVG asset.
 * This path is resolved by the Webpack bundler and includes the content hash
 * for cache busting (40dab905).
 * 
 * @example
 *