/**
 * CSS Module loader type definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack's css-loader with modules enabled.
 */

/**
 * CSS Module class names mapping
 * Maps semantic class names to their hashed/scoped equivalents
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader options configuration
 */
interface StyleLoaderOptions {
  /**
   * Function to transform and inject style tags into DOM
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into specified DOM location
   * @param target - DOM insertion target (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM API interface for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * Default export: CSS module class names
 * Contains the locally scoped class names for this CSS module
 */
declare const cssModuleClasses: CSSModuleClasses | undefined;

export default cssModuleClasses;

/**
 * Re-exported utilities from the underlying CSS module loader
 * (All named exports except 'default' from the source module)
 */
export * from './css-module-loader';