/**
 * CSS Module loader configuration and exports
 * Handles style injection and CSS module class name exports
 */

/**
 * CSS Module class names mapping
 * Contains locally scoped class names generated by CSS Modules
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader options configuration
 */
export interface StyleLoaderOptions {
  /**
   * Transform function to apply to style tags before insertion
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into the DOM
   * Bound to insert into 'head' element
   */
  insert: (target: string) => void;
  
  /**
   * DOM API implementation for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * Default export: CSS Module class names
 * Returns the locally scoped class names from the CSS module,
 * or undefined if no locals are available
 */
declare const cssModuleExport: CSSModuleClasses | undefined;

export default cssModuleExport;

/**
 * Re-exported members from the underlying CSS module
 * Includes all named exports except 'default'
 */
export * from './css-module-source';