/**
 * Asset module that exports the URL path to the recommend decorations hover SVG icon.
 * This file is typically generated by a bundler's asset loader (e.g., Webpack file-loader).
 * 
 * @module RecommendDecorationsHoverAsset
 */

/**
 * The public URL path to the recommend-decorations-hover SVG asset.
 * This path is resolved relative to the application's public directory at build time.
 * 
 * @example
 *