/**
 * CryptoJS OFB (Output Feedback) Mode Implementation
 * 
 * OFB (Output Feedback) mode is a block cipher mode of operation that turns a block cipher
 * into a synchronous stream cipher. It generates keystream blocks, which are then XORed with
 * the plaintext blocks to get the ciphertext.
 * 
 * @module CryptoJS.mode.OFB
 */

declare namespace CryptoJS {
  namespace lib {
    /**
     * Base class for block cipher modes
     */
    interface BlockCipherMode {
      /**
       * Creates a new instance of this mode
       */
      create(): this;
      
      /**
       * Extends this mode with additional functionality
       * @template T - The type of the extension object
       */
      extend<T>(overrides: T): T & this;
    }
  }

  namespace mode {
    /**
     * OFB (Output Feedback) mode implementation for block ciphers
     * 
     * In OFB mode, the cipher is used to generate a keystream by repeatedly encrypting
     * an initialization vector. The keystream is then XORed with the plaintext/ciphertext.
     */
    interface OFB extends lib.BlockCipherMode {
      /**
       * OFB encryptor
       */
      Encryptor: OFBEncryptor;
      
      /**
       * OFB decryptor (identical to encryptor in OFB mode)
       */
      Decryptor: OFBEncryptor;
    }

    /**
     * OFB mode encryptor/decryptor
     * 
     * Note: In OFB mode, encryption and decryption use the same operation
     * because XOR is its own inverse.
     */
    interface OFBEncryptor {
      /**
       * The block cipher instance used for encryption
       * @private
       */
      _cipher: {
        /**
         * Size of the cipher block in 32-bit words
         */
        blockSize: number;
        
        /**
         * Encrypts a block of data in-place
         * @param words - The data words array to encrypt
         * @param offset - The offset into the words array
         */
        encryptBlock(words: number[], offset: number): void;
      };

      /**
       * Initialization vector (IV) used for the first block
       * After first use, this is set to undefined and _keystream is used instead
       * @private
       */
      _iv?: number[];

      /**
       * The keystream generated by encrypting the IV or previous keystream block
       * @private
       */
      _keystream?: number[];

      /**
       * Processes a single block of data by XORing it with the keystream
       * 
       * This method:
       * 1. Initializes the keystream from IV on first call
       * 2. Encrypts the keystream to generate the next keystream block
       * 3. XORs each word of the data block with the corresponding keystream word
       * 
       * @param words - Array of 32-bit words representing the data block
       * @param offset - Starting position in the words array for this block
       */
      processBlock(words: number[], offset: number): void;
    }

    /**
     * The OFB mode singleton instance
     */
    const OFB: OFB;
  }
}

export = CryptoJS;
export as namespace CryptoJS;