export enum ENV {
  WEBGL_LEGACY = 0,
  WEBGL = 1,
  WEBGL2 = 2
}

export enum RENDERER_TYPE {
  UNKNOWN = 0,
  WEBGL = 1,
  CANVAS = 2
}

export enum BLEND_MODES {
  NORMAL = 0,
  ADD = 1,
  MULTIPLY = 2,
  SCREEN = 3,
  OVERLAY = 4,
  DARKEN = 5,
  LIGHTEN = 6,
  COLOR_DODGE = 7,
  COLOR_BURN = 8,
  HARD_LIGHT = 9,
  SOFT_LIGHT = 10,
  DIFFERENCE = 11,
  EXCLUSION = 12,
  HUE = 13,
  SATURATION = 14,
  COLOR = 15,
  LUMINOSITY = 16,
  NORMAL_NPM = 17,
  ADD_NPM = 18,
  SCREEN_NPM = 19,
  NONE = 20,
  SRC_OVER = 0,
  SRC_IN = 21,
  SRC_OUT = 22,
  SRC_ATOP = 23,
  DST_OVER = 24,
  DST_IN = 25,
  DST_OUT = 26,
  DST_ATOP = 27,
  ERASE = 26,
  SUBTRACT = 28,
  XOR = 29
}

export enum DRAW_MODES {
  POINTS = 0,
  LINES = 1,
  LINE_LOOP = 2,
  LINE_STRIP = 3,
  TRIANGLES = 4,
  TRIANGLE_STRIP = 5,
  TRIANGLE_FAN = 6
}

export enum FORMATS {
  RGBA = 6408,
  RGB = 6407,
  ALPHA = 6406,
  LUMINANCE = 6409,
  LUMINANCE_ALPHA = 6410,
  DEPTH_COMPONENT = 6402,
  DEPTH_STENCIL = 34041
}

export enum TARGETS {
  TEXTURE_2D = 3553,
  TEXTURE_CUBE_MAP = 34067,
  TEXTURE_2D_ARRAY = 35866,
  TEXTURE_CUBE_MAP_POSITIVE_X = 34069,
  TEXTURE_CUBE_MAP_NEGATIVE_X = 34070,
  TEXTURE_CUBE_MAP_POSITIVE_Y = 34071,
  TEXTURE_CUBE_MAP_NEGATIVE_Y = 34072,
  TEXTURE_CUBE_MAP_POSITIVE_Z = 34073,
  TEXTURE_CUBE_MAP_NEGATIVE_Z = 34074
}

export enum TYPES {
  UNSIGNED_BYTE = 5121,
  UNSIGNED_SHORT = 5123,
  UNSIGNED_SHORT_5_6_5 = 33635,
  UNSIGNED_SHORT_4_4_4_4 = 32819,
  UNSIGNED_SHORT_5_5_5_1 = 32820,
  FLOAT = 5126,
  HALF_FLOAT = 36193
}

export enum SCALE_MODES {
  NEAREST = 0,
  LINEAR = 1
}

export enum WRAP_MODES {
  CLAMP = 33071,
  REPEAT = 10497,
  MIRRORED_REPEAT = 33648
}

export enum MIPMAP_MODES {
  OFF = 0,
  POW2 = 1,
  ON = 2
}

export enum ALPHA_MODES {
  NPM = 0,
  UNPACK = 1,
  PMA = 2,
  NO_PREMULTIPLIED_ALPHA = 0,
  PREMULTIPLY_ON_UPLOAD = 1,
  PREMULTIPLY_ALPHA = 2
}

export enum GC_MODES {
  AUTO = 0,
  MANUAL = 1
}

export const PRECISION = {
  LOW: 'lowp' as const,
  MEDIUM: 'mediump' as const,
  HIGH: 'highp' as const
};

export enum MASK_TYPES {
  NONE = 0,
  SCISSOR = 1,
  STENCIL = 2,
  SPRITE = 3
}

export const {
  WEBGL_LEGACY,
  WEBGL,
  WEBGL2
} = ENV;

export const {
  UNKNOWN,
  CANVAS
} = RENDERER_TYPE;

export const {
  NORMAL,
  ADD,
  MULTIPLY,
  SCREEN,
  OVERLAY,
  DARKEN,
  LIGHTEN,
  COLOR_DODGE,
  COLOR_BURN,
  HARD_LIGHT,
  SOFT_LIGHT,
  DIFFERENCE,
  EXCLUSION,
  HUE,
  SATURATION,
  COLOR,
  LUMINOSITY,
  NORMAL_NPM,
  ADD_NPM,
  SCREEN_NPM,
  NONE,
  SRC_OVER,
  SRC_IN,
  SRC_OUT,
  SRC_ATOP,
  DST_OVER,
  DST_IN,
  DST_OUT,
  DST_ATOP,
  ERASE,
  SUBTRACT,
  XOR
} = BLEND_MODES;

export const {
  POINTS,
  LINES,
  LINE_LOOP,
  LINE_STRIP,
  TRIANGLES,
  TRIANGLE_STRIP,
  TRIANGLE_FAN
} = DRAW_MODES;

export const {
  RGBA,
  RGB,
  ALPHA,
  LUMINANCE,
  LUMINANCE_ALPHA,
  DEPTH_COMPONENT,
  DEPTH_STENCIL
} = FORMATS;

export const {
  TEXTURE_2D,
  TEXTURE_CUBE_MAP,
  TEXTURE_2D_ARRAY,
  TEXTURE_CUBE_MAP_POSITIVE_X,
  TEXTURE_CUBE_MAP_NEGATIVE_X,
  TEXTURE_CUBE_MAP_POSITIVE_Y,
  TEXTURE_CUBE_MAP_NEGATIVE_Y,
  TEXTURE_CUBE_MAP_POSITIVE_Z,
  TEXTURE_CUBE_MAP_NEGATIVE_Z
} = TARGETS;

export const {
  UNSIGNED_BYTE,
  UNSIGNED_SHORT,
  UNSIGNED_SHORT_5_6_5,
  UNSIGNED_SHORT_4_4_4_4,
  UNSIGNED_SHORT_5_5_5_1,
  FLOAT,
  HALF_FLOAT
} = TYPES;

export const {
  NEAREST,
  LINEAR
} = SCALE_MODES;

export const {
  CLAMP,
  REPEAT,
  MIRRORED_REPEAT
} = WRAP_MODES;

export const {
  OFF,
  POW2,
  ON
} = MIPMAP_MODES;

export const {
  NPM,
  UNPACK,
  PMA,
  NO_PREMULTIPLIED_ALPHA,
  PREMULTIPLY_ON_UPLOAD,
  PREMULTIPLY_ALPHA
} = ALPHA_MODES;

export const {
  AUTO,
  MANUAL
} = GC_MODES;

export const {
  LOW,
  MEDIUM,
  HIGH
} = PRECISION;

export const {
  SCISSOR,
  STENCIL,
  SPRITE
} = MASK_TYPES;