/**
 * Webpack asset module that exports the URL path to a trumpet SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module TrumpetAsset
 */

/**
 * The public URL path to the trumpet SVG asset.
 * This path is resolved by the webpack bundler and includes the content hash
 * for cache busting purposes.
 * 
 * @example
 *