/**
 * Asset module that exports the path to the sewer pipe round SVG image.
 * This module is typically auto-generated by bundlers for static asset imports.
 * 
 * @module SewerPipeRoundAsset
 */

/**
 * The public URL path to the sewer pipe round SVG asset.
 * This path is resolved by the bundler and points to the optimized asset in the build output.
 * 
 * @example
 *