/**
 * Webpack asset module that exports the public URL path for a blue star icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module StarIconBlueAsset
 */

/**
 * The public URL path to the blue star icon SVG asset.
 * This path is resolved at build time by Webpack and includes the content hash for cache busting.
 * 
 * @example
 *