/**
 * Asset module that exports the URL path to the delete_normal SVG icon.
 * This module is typically auto-generated by Webpack's asset/resource module type.
 * 
 * @module DeleteNormalIcon
 */

/**
 * The URL path to the delete_normal.svg icon asset.
 * The hash in the filename (a74629cb) ensures cache busting when the asset changes.
 * 
 * @example
 *