/**
 * Webpack asset module that exports the URL path to the pen cursor SVG asset.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module PenCursorAsset
 */

/**
 * The public URL path to the pen cursor SVG asset.
 * This path is resolved by webpack at build time and includes the content hash
 * for cache busting (a32a0568).
 * 
 * @example
 *