/**
 * Asset module that exports the URL path to the delete_selected SVG icon.
 * This file is typically auto-generated by build tools (webpack/vite) for static asset imports.
 * 
 * @module DeleteSelectedAsset
 */

/**
 * The resolved public URL path to the delete_selected SVG icon asset.
 * This path is computed by the bundler based on the public path configuration
 * and content hash for cache-busting.
 * 
 * @example
 *