/**
 * Asset module that exports the path to the cancel icon SVG file.
 * This module is typically generated by a bundler's asset handling system.
 * 
 * @module CancelIconAsset
 */

/**
 * The URL path to the cancel icon SVG asset.
 * This path is relative to the application's public assets directory.
 * 
 * @example
 *