/**
 * Asset module that exports the path to the material brush GIF image.
 * This module is typically generated by Webpack's asset modules feature.
 * 
 * @module MaterialBrushAsset
 */

/**
 * The public URL path to the material brush animated GIF asset.
 * This path is resolved relative to the application's public path and
 * points to the compiled/hashed asset file.
 * 
 * @example
 *