/**
 * Asset module that exports the path to the tpicon SVG file.
 * This module is typically generated by Webpack's asset/resource module type,
 * which emits the file to the output directory and exports its public URL.
 * 
 * @module TpIconAsset
 */

/**
 * The public URL path to the tpicon SVG asset.
 * The path is constructed using the webpack public path configuration
 * and the hashed filename for cache busting.
 * 
 * @example
 *