/**
 * Asset module that exports the URL path to the nocopywall SVG asset.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module NoCopywallAsset
 */

/**
 * The public URL path to the nocopywall SVG asset.
 * This path is resolved at build time by the bundler and points to the
 * final location of the asset in the output directory.
 * 
 * @example
 *