/**
 * Asset module that exports the URL path to the 'choose_hover' SVG image.
 * This module is generated by Webpack's asset/resource module type.
 * 
 * @module ChooseHoverAsset
 */

/**
 * The URL path to the choose_hover SVG asset.
 * The path is resolved relative to the application's public path.
 * 
 * @example
 *