/**
 * SVG asset module that exports the path to the help icon.
 * This module is typically generated by a bundler's asset handling system.
 */

/**
 * The relative or absolute URL path to the help.svg icon asset.
 * The hash (24f18073) in the filename is used for cache busting.
 * 
 * @example
 *