/**
 * VProgressCircular component styles module
 * 
 * This module imports and registers the styles for the VProgressCircular component.
 * It's typically auto-generated by webpack during the build process and has no runtime exports.
 * 
 * @module VProgressCircularStyles
 * @packageDocumentation
 */

/**
 * Style module loader function (side-effect only)
 * 
 * This function is called by webpack's module system to load and inject
 * the component's SASS styles into the document. It performs no operations
 * at runtime and exports nothing.
 * 
 * @param module - The webpack module object
 * @param exports - The module's exports object
 * @param require - The webpack require function for loading dependencies
 * @returns void - This module has no exports
 * 
 * @remarks
 * In production TypeScript code, this would typically be replaced with:
 *