/**
 * Runtime helper that throws an error when attempting to destructure a non-iterable value.
 * 
 * This helper is typically generated by TypeScript/Babel when compiling destructuring assignments
 * for non-iterable objects that don't implement the iterable protocol.
 * 
 * @throws {TypeError} Always throws a TypeError indicating invalid destructuring attempt
 * 
 * @example
 * // This would trigger the error:
 * const [a, b] = nonIterableObject;
 */
export default function nonIterableSpread(): never;

/**
 * Runtime helper that throws an error when attempting to destructure a non-iterable value.
 * 
 * @throws {TypeError} Always throws a TypeError with a descriptive message
 */
export function nonIterableSpread(): never;