/**
 * Webpack asset module that exports the URL path to the zoomout SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module ZoomOutIcon
 */

/**
 * The public URL path to the zoomout SVG asset.
 * This path is resolved by the webpack bundler and points to the final
 * location of the asset in the build output directory.
 * 
 * @constant {string}
 * @default "assets/zoomout.98a769ed.svg"
 */
declare const zoomOutIconPath: string;

export default zoomOutIconPath;