/**
 * Static asset module that exports the URL path to a picture SVG file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static file imports.
 * 
 * @module PictureAsset
 */

/**
 * The public URL path to the picture.svg asset.
 * This path is relative to the application's public directory and includes
 * a content hash (b0c323d7) for cache busting.
 * 
 * @example
 *