/**
 * Asset module that exports the URL path to a high commission pool image.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module HighCommissionPoolAsset
 */

/**
 * The public URL path to the high commission pool image asset.
 * Points to the compiled/hashed image file in the assets directory.
 * 
 * @type {string}
 * @example
 *