/**
 * Asset module that exports the path to the room scan image asset.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module RoomScanAsset
 */

/**
 * The public URL path to the room scan image asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @remarks
 * - Original filename: hs_huahuxing_roomscan.png
 * - Content hash: bb840400
 * - This is typically used for importing image assets in the application
 * 
 * @example
 *