/**
 * Webpack asset module that exports the URL path to the duplicate icon SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module DuplicateIconAsset
 */

/**
 * The public URL path to the duplicate.svg icon asset.
 * This path is resolved by the Webpack build process and includes the content hash
 * (40dab905) for cache-busting purposes.
 * 
 * @example
 *