/**
 * Asset module that exports the URL path to a context menu room type SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module ContextMenuRoomTypeAsset
 */

/**
 * The URL path to the context menu room type SVG asset.
 * This path is resolved by the bundler and points to the asset in the distribution folder.
 * 
 * @example
 *