/**
 * Asset module that exports the path to the unselect SVG icon.
 * This file is typically auto-generated by bundlers for static asset imports.
 */

/**
 * The public path to the unselect.svg icon asset.
 * @remarks
 * This path is resolved at build time and points to the compiled asset location.
 * The hash (fd174c97) ensures proper cache busting.
 */
declare const assetPath: string;

export default assetPath;