/**
 * CSS Module type definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack's css-loader with modules enabled.
 */

/**
 * CSS module class names mapping
 * Maps semantic class name keys to generated scoped class name values
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader API for managing CSS injection
 */
export interface StyleLoaderAPI {
  /**
   * Transform and inject style tags into the document
   */
  styleTagTransform: () => void;

  /**
   * Set attributes on style elements (e.g., nonce, data attributes)
   */
  setAttributes: () => void;

  /**
   * Insert style element into specified DOM location
   * @param target - DOM insertion target (e.g., "head")
   */
  insert: (target: string) => void;

  /**
   * DOM manipulation API abstraction
   */
  domAPI: () => void;

  /**
   * Create and insert style element into the document
   */
  insertStyleElement: () => void;
}

/**
 * CSS module content structure
 */
export interface CSSModuleContent {
  /**
   * Scoped class name mappings for this CSS module
   */
  locals?: CSSModuleClasses;

  /**
   * Raw CSS content or style metadata
   */
  [key: string]: unknown;
}

/**
 * Default export: CSS module class names
 * Returns undefined if no local class names are defined
 */
declare const cssModuleClasses: CSSModuleClasses | undefined;

export default cssModuleClasses;

/**
 * Re-exported members from the CSS module content
 * Excludes the 'default' export to avoid duplication
 */
export * from './css-module-content';