/**
 * Asset module that exports the path to a save icon SVG file.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module SaveIconAsset
 */

/**
 * The public path to the save icon SVG asset.
 * Resolved at build time by the bundler to include the correct base path.
 * 
 * @example
 *