/**
 * Asset module that exports the URL path to the rule SVG icon.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static file imports.
 * 
 * @module RuleAsset
 */

/**
 * The public URL path to the rule.svg icon asset.
 * This path is resolved at build time and includes the content hash (713fac18)
 * for cache busting purposes.
 * 
 * @example
 *