/**
 * CSS Module Type Definition
 * 
 * This module represents a CSS module loader configuration with style injection utilities.
 * Typically generated by webpack css-loader with modules enabled.
 */

/**
 * CSS Module class names mapping
 * Maps the class names defined in the CSS file to their hashed/scoped equivalents
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style injection configuration options
 */
export interface StyleInjectionOptions {
  /**
   * Transform function to apply to style tags before insertion
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into the DOM
   * Bound to insert into specified container (e.g., "head")
   */
  insert: (container: string) => void;
  
  /**
   * DOM API utilities for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports
 * Contains the locally scoped class names or undefined if no locals exist
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-export all named exports from the CSS module
 * Allows importing specific class names: import { className } from './styles.css'
 */
export * from './styles.css';