/**
 * Asset module that exports the path to the user_selected SVG icon.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static file imports.
 * 
 * @module UserSelectedAsset
 */

/**
 * The file path to the user_selected SVG icon asset.
 * This path is resolved relative to the public/output directory and includes
 * a content hash for cache busting.
 * 
 * @example
 *