/**
 * CSS Module Type Definitions
 * 
 * This module provides CSS styles and their corresponding class name mappings.
 * It is typically auto-generated by webpack's css-loader with modules enabled.
 */

/**
 * Style injection configuration for webpack style-loader.
 * Handles how styles are inserted into the DOM.
 */
interface StyleLoaderOptions {
  /** Transforms style tags before insertion */
  styleTagTransform: (...args: unknown[]) => unknown;
  
  /** Sets attributes on style elements */
  setAttributes: (...args: unknown[]) => unknown;
  
  /** DOM insertion method (typically inserts into <head>) */
  insert: (target: string) => unknown;
  
  /** DOM manipulation API */
  domAPI: (...args: unknown[]) => unknown;
  
  /** Creates and inserts style elements */
  insertStyleElement: (...args: unknown[]) => unknown;
}

/**
 * CSS Module locals - maps CSS class names to their hashed equivalents.
 * The actual properties depend on the CSS file content.
 * 
 * @example
 *