/**
 * Asset module that exports the URL path to the pickmaterial SVG icon.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module PickMaterialAsset
 */

/**
 * The public URL path to the pickmaterial.svg asset file.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *