/**
 * Asset module that exports the URL path to the upload SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * for static file imports.
 * 
 * @module UploadAsset
 */

/**
 * The public URL path to the upload.svg icon asset.
 * This path includes the content hash (09e860f7) for cache busting.
 * 
 * @example
 *