/**
 * Asset module that exports the file path for the premium active feature point SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module PremiumActiveIcon
 */

/**
 * The resolved public path to the premium active feature point SVG asset.
 * This path is constructed by combining the Webpack public path with the hashed filename.
 * 
 * @example
 *