/**
 * Asset module that exports the URL path to the loading spinner GIF.
 * This module is typically generated by Webpack's asset/resource module type
 * for handling static assets like images.
 * 
 * @module LoadingAsset
 */

/**
 * The URL path to the loading spinner animation image.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *