/**
 * Asset module that exports the URL path to the info SVG icon.
 * This module is typically auto-generated by Webpack's asset/resource module type.
 * 
 * @module InfoSvgAsset
 */

/**
 * The public URL path to the info.svg asset file.
 * The hash (593d93e6) ensures cache busting when the file content changes.
 * 
 * @example
 *