/**
 * Asset module that exports the URL path to the noModel SVG asset.
 * This file is typically generated by bundlers (like Webpack) to handle static asset imports.
 * 
 * @module NoModelAsset
 */

/**
 * The public URL path to the noModel.svg asset.
 * This path is resolved relative to the application's public path.
 * 
 * @example
 *