/**
 * Asset module that exports the path to the left arrow SVG icon.
 * This module is typically generated by Webpack's asset/resource module type
 * for static file handling.
 * 
 * @module LeftArrowAsset
 */

/**
 * The public path to the left arrow SVG asset.
 * This path is resolved relative to the application's public URL.
 * 
 * @example
 *