/**
 * Asset module that exports the URL path to the cancel icon SVG file.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module CancelIconAsset
 */

/**
 * The public URL path to the cancel.svg icon asset.
 * This path is resolved by the bundler and points to the hashed asset file.
 * 
 * @example
 *