/**
 * Webpack asset module that exports the URL path to the modify icon SVG file.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module ModifyIconAsset
 */

/**
 * The public URL path to the modify.svg icon asset.
 * This path is resolved at build time by webpack and includes the content hash
 * for cache busting (cf3caa64).
 * 
 * @example
 *