/**
 * Asset module that exports the path to the noShop SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module NoShopAsset
 */

/**
 * The public path to the noShop SVG asset.
 * This path is resolved at build time and points to the hashed asset file.
 * 
 * @example
 *