/**
 * Asset module that exports the URL path to the bigsymbol SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module BigsymbolAsset
 */

/**
 * The public URL path to the bigsymbol.svg asset file.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *