/**
 * Asset module that exports the path to the "Failed to upload" SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module FailedToUploadAsset
 */

/**
 * The public path to the "Failed to upload" SVG asset.
 * This path is resolved at build time and points to the static asset location.
 * 
 * @example
 *