/**
 * SVG asset module that exports the path to the reflect icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module ReflectAsset
 */

/**
 * The file path to the reflect SVG icon asset.
 * Path is relative to the application's public asset directory.
 * 
 * @example
 *