/**
 * Webpack asset module that exports the URL path to a loading GIF image.
 * This module is typically generated by Webpack's asset/resource loader
 * for handling static image files.
 * 
 * @module LoadingAsset
 * @originalId 710673
 */

/**
 * The public URL path to the loading spinner GIF image.
 * This path is resolved at build time by the bundler and points to
 * the hashed asset file in the output directory.
 * 
 * @constant {string} LOADING_GIF_URL - Relative or absolute URL to loading.cce10830.gif
 * @example
 * import loadingGif from './loading-asset';
 * // loadingGif === "assets/loading.cce10830.gif"
 */
export declare const LOADING_GIF_URL: string;

/**
 * Default export: URL path to the loading animation GIF
 */
declare const loadingAssetUrl: string;
export default loadingAssetUrl;