/**
 * Asset module that exports the path to the question icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 */

/**
 * The public path to the question.svg icon asset.
 * 
 * @remarks
 * This path is resolved at build time by the bundler and points to the
 * compiled asset location in the distribution directory.
 * 
 * @example
 *