/**
 * Asset module that exports the URL path to the delete icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DeleteIconAsset
 */

/**
 * The public URL path to the delete icon SVG asset.
 * This path is resolved relative to the application's public path.
 * 
 * @example
 * import deleteIconUrl from './delete-icon';
 * // deleteIconUrl === "assets/delete.cd324da2.svg"
 */
declare const deleteIconUrl: string;

export default deleteIconUrl;