/**
 * Asset module that exports the URL path to the merge wall joint SVG asset.
 * This module is typically generated by Webpack's asset/resource module type,
 * which emits the file to the output directory and exports its URL.
 * 
 * @module MergeWallJointAsset
 */

/**
 * The public URL path to the merge_wall_joint.svg asset.
 * The actual file will be located at: /assets/merge_wall_joint.ead1468d.svg
 * where 'ead1468d' is the content hash for cache busting.
 */
declare const mergeWallJointAssetUrl: string;

export default mergeWallJointAssetUrl;