/**
 * Webpack asset module that exports the URL path to a right arrow SVG icon.
 * This module represents a static asset reference that would be processed by Webpack's asset/resource loader.
 * 
 * @module RightArrowAsset
 * @description Exports the public URL path to the right arrow SVG asset (right.77b40cea.svg)
 */

/**
 * The public URL path to the right arrow SVG icon asset.
 * The hash (77b40cea) in the filename is typically generated by Webpack for cache-busting purposes.
 * 
 * @example
 *