/**
 * Asset module that exports the path to a black styler icon SVG file.
 * This module is typically generated by Webpack's asset module system.
 * 
 * @module icon_styler_black
 * @packageDocumentation
 */

/**
 * The public path to the black styler icon SVG asset.
 * This path is resolved at build time and points to the compiled asset location.
 * 
 * @example
 *