/**
 * Asset module that exports the URL path to a lock SVG icon.
 * This module is typically generated by a bundler's asset management system.
 * 
 * @module LockAsset
 */

/**
 * The public URL path to the lock icon SVG file.
 * This path is resolved at build time and points to the compiled asset location.
 * 
 * @constant
 * @type {string}
 * @default "assets/lock.fddef3a2.svg"
 * 
 * @example
 *