/**
 * Asset module that exports the URL path to the upload icon image.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static assets like images.
 * 
 * @module UploadIconAsset
 */

/**
 * The URL path to the upload icon PNG image.
 * This path is resolved by the bundler and points to the hashed asset file.
 * 
 * @example
 *