/**
 * Asset module that exports the URL path to the replace icon SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module ReplaceIconAsset
 */

/**
 * The public URL path to the replace icon SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *