/**
 * Asset module that exports the URL path to the undo icon SVG file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static assets like images and SVGs.
 * 
 * @module UndoAsset
 */

/**
 * The URL path to the undo.svg icon asset.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *