/**
 * Webpack asset module that exports the URL path to a selected state icon SVG.
 * This module is typically auto-generated by Webpack's asset/resource module type.
 * 
 * @module SelectedIconAsset
 */

/**
 * The public URL path to the selected.svg icon asset.
 * This path is resolved at build time by Webpack and includes content hash for cache busting.
 * 
 * @example
 *