/**
 * CSS Module type definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack's style-loader + css-loader with modules enabled.
 */

/**
 * CSS Module class name mappings
 * 
 * Maps semantic class names to their hashed/scoped equivalents.
 * Example: { button: "Button_button__1a2b3", container: "Button_container__4c5d6" }
 */
export interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Style loader API for runtime style injection
 */
export interface StyleLoaderAPI {
  /**
   * Transforms and injects style tags into the document
   */
  styleTagTransform: () => void;
  
  /**
   * Sets attributes on style elements (e.g., nonce, data-attributes)
   */
  setAttributes: () => void;
  
  /**
   * Inserts style element into specified DOM location
   * @param target - DOM insertion point (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM manipulation API for style injection
   */
  domAPI: () => void;
  
  /**
   * Creates and inserts <style> element
   */
  insertStyleElement: () => void;
}

/**
 * Default export: CSS module class name mappings
 * 
 * Use this object to access scoped CSS class names in your components.
 * Returns undefined if no local class names are defined.
 * 
 * @example
 *