/**
 * CSS Module exports type definition
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * It uses style-loader utilities to dynamically insert styles into the document head.
 */

/**
 * CSS Module class name mappings
 * 
 * Contains the locally scoped CSS class names generated by css-loader.
 * Keys are the original class names from the CSS file, values are the hashed/scoped names.
 */
export interface CSSModuleLocals {
  [className: string]: string;
}

/**
 * Style loader API for managing style tags
 */
export interface StyleLoaderAPI {
  /**
   * Transform function to apply to style tag before insertion
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on the style element
   */
  setAttributes: () => void;
  
  /**
   * Function to insert the style element into the DOM
   * @param target - The DOM element to insert into (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM manipulation API
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert the style element
   */
  insertStyleElement: () => void;
}

/**
 * Default export: CSS Module locals (class name mappings)
 * 
 * Returns an object mapping original CSS class names to their scoped versions,
 * or undefined if no locals are available.
 */
declare const cssModuleExports: CSSModuleLocals | undefined;

export default cssModuleExports;

/**
 * Re-exported members from the underlying CSS module
 * 
 * All named exports from the source CSS module (excluding 'default')
 * are re-exported here for direct access.
 */
export * from './source-css-module';