/**
 * Webpack asset module that exports the URL path to the feedback close icon SVG.
 * This module is typically generated by Webpack's asset/resource loader.
 */

/**
 * The public URL path to the feedback close SVG asset.
 * This path is resolved at build time by Webpack and includes the public path prefix.
 * 
 * @example
 * import feedbackCloseIcon from './feedbackclose.svg';
 * // feedbackCloseIcon === "assets/feedbackclose.949ddc1a.svg"
 */
declare const feedbackCloseIconUrl: string;

export default feedbackCloseIconUrl;