/**
 * Asset module that exports the URL path to the customer service SVG icon.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module CustomerServiceAsset
 */

/**
 * The public URL path to the customer service SVG asset.
 * This path is resolved at build time and includes any configured public path prefix.
 * 
 * @example
 *