/**
 * Webpack asset module that exports the URL path to a user selection icon SVG.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module UserSelectedIconAsset
 */

/**
 * The public URL path to the user_selected SVG icon asset.
 * This path is resolved by the webpack bundler and points to the static asset location.
 * 
 * @example
 *