/**
 * Asset module that exports the URL path to the close icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module CloseIconAsset
 */

/**
 * The public URL path to the close icon SVG asset.
 * This path is resolved relative to the application's public path at build time.
 * 
 * @example
 *