/**
 * Asset module that exports the path to the guide background image.
 * This module is typically generated by Webpack's asset/resource module type,
 * which emits the file to the output directory and exports its URL.
 * 
 * @module GuideBgAsset
 */

/**
 * The public path to the guide background image asset.
 * Points to the processed and hashed PNG file in the assets directory.
 * 
 * @type {string}
 * @constant
 * @example
 *