/**
 * Asset module that exports the path to the recommendation arrow SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module RecommendationArrowAsset
 */

/**
 * The public URL path to the recommendation arrow SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *