/**
 * Asset module that exports the URL path to the molding SVG asset.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module MoldingSvgAsset
 */

/**
 * The URL path to the molding.svg asset file.
 * This path is resolved relative to the public path configured in the build system.
 * 
 * @example
 *