/**
 * CSS Module type definitions
 * 
 * This module handles CSS imports with CSS Modules support.
 * Exports style class names as a typed object when CSS Modules are enabled.
 */

/**
 * CSS Module class names mapping
 * 
 * Contains the locally scoped class names generated by CSS Modules.
 * Keys are the original class names, values are the transformed scoped names.
 */
export interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Default export - CSS Module locals object
 * 
 * Contains the mapping of class names when CSS Modules are enabled.
 * Returns `undefined` if CSS Modules are not used or no locals exist.
 * 
 * @example
 *