/**
 * Webpack asset URL export module
 * 
 * This module exports the public URL path for a dropdown SVG asset.
 * The asset is processed by Webpack's asset pipeline and gets a content hash
 * in its filename for cache busting purposes.
 * 
 * @module DropdownAsset
 */

/**
 * Public URL path to the dropdown SVG icon asset.
 * 
 * The filename includes a content hash (ff83ff43) generated by Webpack
 * to ensure proper cache invalidation when the file content changes.
 * 
 * @example
 *