/**
 * Asset module that exports the path to the active merchant model SVG icon.
 * This file is auto-generated by the build system and provides type-safe access to static assets.
 * 
 * @module MerchantModelActiveIcon
 */

/**
 * The public path to the active merchant model SVG asset.
 * This path is resolved at build time and includes cache-busting hash.
 * 
 * @example
 *