/**
 * Asset module export for corner image
 * 
 * This module exports the URL path to a corner image asset.
 * The image is processed by the bundler and includes a content hash
 * in its filename for cache busting purposes.
 * 
 * @module CornerAsset
 */

/**
 * The public URL path to the corner.png image asset
 * 
 * This path is automatically generated by the bundler and includes
 * a content hash (2c1df9e4) for optimal caching behavior.
 * 
 * @example
 *