export enum CustomizationParamKey {
  Size = "size",
  CornerSize = "cornerSize",
  Material = "materail",
  Length = "length",
  Height = "height",
  RoomId = "roomId",
  CustomizationType = "customType",
  DetailCardData = "detailCardData"
}

export enum CustomizationContentType {
  Other = "other",
  FloorCabinet = "floorCabinet",
  HightCabinet = "hightCabinet",
  WallCabinet = "wallCabinet",
  UpCabinet = "upCabinet",
  SlidingDoorSideBoard = "slidingDoorSideBoard",
  SideDecoration = "sideDecoration",
  FrontCloseBoard = "frontCloseBoard",
  TopCloseBoard = "topCloseBoard",
  CeilingCloseBoard = "ceilingCloseBoard",
  BackgroundBoard = "backgroundBoard",
  StorageBoard = "storageBoard",
  FrontCloseBoardWithFrame = "frontCloseBoardWithFrame",
  TopCloseBoardBetweenTwo = "topCloseBoardBetweenTwo",
  UpCloseBoard = "upCloseBoard",
  ProtectWallBoard = "protectWallBoard",
  Func_HorizontalBoard = "func_HorizontalBoard",
  Func_VerticalBoard = "func_VerticalBoard",
  Func_Drawer = "func_Drawer",
  Func_ClothesRail = "func_ClothesRail",
  Func_Unkown = "func_Unkown",
  Drawer_Fascias = "drawer_fascias",
  SlidingDoor = "SlidingDoor",
  SlidingDoorLeaf = "SlidingDoorLeaf",
  SideHungDoor = "SideHungDoor",
  TatamiDoor = "TatamiDoor",
  RoomDoor = "RoomDoor",
  RoomWindow = "RoomWindow",
  CeilingOrnament = "ceilingOrnament",
  WallOrnament = "wallOrnament",
  AboveOrnament = "aboveOrnament",
  Sink = "sink",
  TopLine = "topLine",
  Skirting = "skirting",
  LightLine = "lightLine",
  Countertop = "countertop",
  NoDripEdge = "noDripEdge",
  Backsplash = "backsplash",
  CabinetHandleType0 = "cbnt handle type 0",
  RangeCooktop = "range & cooktop"
}