/**
 * ModelClassName - HSCore 3D建模系统的类名常量定义
 * 
 * 该模块定义了HSCore建模系统中所有实体类的完全限定类名。
 * 用于序列化、反射和运行时类型识别。
 */

/**
 * HSCore建模系统类名映射表
 * 
 * 包含所有模型实体、几何元素、约束、材质等类的字符串标识符。
 * 键名为简化标识符，值为完整的命名空间路径。
 */
export declare const ModelClassName: {
  /** 关联关系基类 */
  readonly Association: "HSCore.Model.Association";
  /** 点在线上的关联关系 */
  readonly PointOnLineAssociation: "HSCore.Model.PointOnLineAssociation";
  /** 边在线上的关联关系 */
  readonly EdgeOnLineAssociation: "HSCore.Model.EdgeOnLineAssociation";
  /** 点对点关联关系 */
  readonly PointOnPointAssociation: "HSCore.Model.PointOnPointAssociation";
  /** 圆弧曲线 */
  readonly ArcCurve: "HSCore.Model.ArcCurve";
  /** 顶点实体 */
  readonly NgVertex: "HSCore.Model.Vertex";
  /** 墙体实体 */
  readonly NgWall: "HSCore.Model.Wall";
  /** 户型平面图 */
  readonly NgFloorplan: "HSCore.Model.Floorplan";
  /** 基础实体类 */
  readonly NgEntity: "HSCore.Model.Entity";
  /** 边实体 */
  readonly NgEdge: "HSCore.Model.Edge";
  /** 共边（边的使用实例） */
  readonly NgCoEdge: "HSCore.Model.CoEdge";
  /** 面实体 */
  readonly NgFace: "HSCore.Model.Face";
  /** 面的环（边界） */
  readonly NgLoop: "HSCore.Model.Loop";
  /** 孔洞 */
  readonly NgHole: "HSCore.Model.Hole";
  /** 门 */
  readonly NgDoor: "HSCore.Model.Door";
  /** 窗 */
  readonly NgWindow: "HSCore.Model.Window";
  /** 开口（门窗的抽象） */
  readonly NgOpening: "HSCore.Model.Opening";
  /** 内容物/家具 */
  readonly NgContent: "HSCore.Model.Content";
  /** 软装布艺 */
  readonly NgSoftCloth: "HSCore.Model.SoftCloth";
  /** 相机 */
  readonly NgCamera: "HSCore.Model.Camera";
  /** 板（地板/吊顶的基础） */
  readonly Slab: "HSCore.Model.Slab";
  /** 板面 */
  readonly SlabFace: "HSCore.Model.SlabFace";
  /** 基础轮廓 */
  readonly BaseProfile: "HSCore.Model.BaseProfile";
  /** 侧面 */
  readonly SideFace: "HSCore.Model.SideFace";
  /** 图层 */
  readonly Layer: "HSCore.Model.Layer";
  /** 场景 */
  readonly Scene: "HSCore.Model.Scene";
  /** 壁龛/凹槽 */
  readonly NgPocket: "HSCore.Model.Pocket";
  /** 自定义模型基类 */
  readonly NgCustomizedModel: "HSCore.Model.CustomizedModel";
  /** 自定义线条装饰 */
  readonly CustomizedModelMolding: "HSCore.Model.CustomizedModelMolding";
  /** 自定义灯槽 */
  readonly CustomizedModelLightSlot: "HSCore.Model.CustomizedModelLightSlot";
  /** 自定义灯带 */
  readonly CustomizedModelLightBand: "HSCore.Model.CustomizedModelLightBand";
  /** 自定义参数化模型 */
  readonly CustomizedPMModel: "HSCore.Model.CustomizedPMModel";
  /** 自定义参数化实例模型 */
  readonly CustomizedPMInstanceModel: "HSCore.Model.CustomizedPMInstanceModel";
  /** 新版自定义线条装饰 */
  readonly NCustomizedModelMolding: "HSCore.Model.NCustomizedModelMolding";
  /** 新版自定义灯槽 */
  readonly NCustomizedModelLightSlot: "HSCore.Model.NCustomizedModelLightSlot";
  /** 新版自定义灯带 */
  readonly NCustomizedModelLightBand: "HSCore.Model.NCustomizedModelLightBand";
  /** 线条装饰基类 */
  readonly NgMolding: "HSCore.Model.Molding";
  /** 墙面线条 */
  readonly NgWallMolding: "HSCore.Model.WallMolding";
  /** 顶角线 */
  readonly NgCornice: "HSCore.Model.Cornice";
  /** 踢脚线 */
  readonly NgBaseboard: "HSCore.Model.Baseboard";
  /** 地板 */
  readonly NgFloor: "HSCore.Model.Floor";
  /** 吊顶 */
  readonly NgCeiling: "HSCore.Model.Ceiling";
  /** 材质 */
  readonly NgMaterial: "HSCore.Model.Material";
  /** 组/群组 */
  readonly NgGroup: "HSCore.Model.Group";
  /** 参数化模型基类 */
  readonly NgPModel: "HSCore.Model.PModel";
  /** 参数化盒体 */
  readonly NgPBox: "HSCore.Model.PBox";
  /** 参数化拉伸体 */
  readonly NgPExtruding: "HSCore.Model.PExtruding";
  /** 参数化内容物 */
  readonly NgPContent: "HSCore.Model.PContent";
  /** 参数化线条 */
  readonly NgPMolding: "HSCore.Model.PMolding";
  /** 动态扫掠 */
  readonly DSweep: "HSCore.Model.DSweep";
  /** 参数化装配体 */
  readonly NgPAssembly: "HSCore.Model.PAssembly";
  /** 参数化分段放样 */
  readonly NgPSegmentLoft: "HSCore.Model.PSegmentLoft";
  /** 参数化推拉门 */
  readonly NgPSlidingDoor: "HSCore.Model.PSlidingDoor";
  /** 推拉门扇 */
  readonly NgPSlidingDoorLeaf: "HSCore.Model.PSlidingDoorLeaf";
  /** 转角窗 */
  readonly NgCornerWindow: "HSCore.Model.CornerWindow";
  /** 飘窗 */
  readonly NgBayWindow: "HSCore.Model.BayWindow";
  /** 转角平窗 */
  readonly NgCornerFlatWindow: "HSCore.Model.CornerFlatWindow";
  /** 参数化普通窗 */
  readonly NgPOrdinaryWindow: "HSCore.Model.POrdinaryWindow";
  /** 参数化开口 */
  readonly ParametricOpening: "HSCore.Model.ParametricOpening";
  /** 参数化模型 */
  readonly NgParametricModel: "HSCore.Model.ParametricModel";
  /** 参数化拉伸体 */
  readonly NgParametricExtrudedBody: "HSCore.Model.Parametrization.ExtrudedBody";
  /** 参数化墙体 */
  readonly NgParametricWall: "HSCore.Model.Parametrization.Wall";
  /** 参数化窗 */
  readonly NgParametricWindow: "HSCore.Model.Parametrization.Window";
  /** 参数化窗顶 */
  readonly NgParametricWindowCeiling: "HSCore.Model.Parametrization.WindowCeiling";
  /** 参数化窗台 */
  readonly NgParametricWindowSill: "HSCore.Model.Parametrization.WindowSill";
  /** 参数化窗洞 */
  readonly NgParametricWindowHole: "HSCore.Model.Parametrization.WindowHole";
  /** 参数化窗套 */
  readonly NgParametricWindowPocket: "HSCore.Model.Parametrization.WindowPocket";
  /** 梁 */
  readonly NgBeam: "HSCore.Model.Beam";
  /** 障碍物 */
  readonly NgObstacle: "HSCore.Model.Obstacle";
  /** 柱 */
  readonly NgColumn: "HSCore.Model.Column";
  /** 烟道 */
  readonly NgFlue: "HSCore.Model.Flue";
  /** 窗帘 */
  readonly NgCurtain: "HSCore.Model.Curtain";
  /** 灯光基类 */
  readonly NgLight: "HSCore.Model.Light";
  /** 网格 */
  readonly NgGrid: "HSCore.Model.Grid";
  /** 方向光 */
  readonly NgDirectionLight: "HSCore.Model.DirectionLight";
  /** 平面光 */
  readonly NgFlatLight: "HSCore.Model.FlatLight";
  /** 点光源 */
  readonly NgPointLight: "HSCore.Model.PointLight";
  /** 聚光灯 */
  readonly NgSpotLight: "HSCore.Model.SpotLight";
  /** 网格光源 */
  readonly NgMeshLight: "HSCore.Model.MeshLight";
  /** 物理光源 */
  readonly NgPhysicalLight: "HSCore.Model.PhysicalLight";
  /** 聚光物理光源 */
  readonly NgSpotPhysicalLight: "HSCore.Model.SpotPhysicalLight";
  /** 衰减聚光灯 */
  readonly NgAttenuatedSpotLight: "HSCore.Model.AttenuatedSpotLight";
  /** 灯光组 */
  readonly NgLightGroup: "HSCore.Model.LightGroup";
  /** 灯光子组 */
  readonly NgLightSubGroup: "HSCore.Model.NgLightSubGroup";
  /** 装配体物理光源 */
  readonly NgAsmPhysicalLight: "HSCore.Model.AsmPhysicalLight";
  /** 装配体灯光子组 */
  readonly NgAsmLightSubGroup: "HSCore.Model.NgAsmLightSubGroup";
  /** 下水管 */
  readonly NgSewerPipe: "HSCore.Model.SewerPipe";
  /** 底图 */
  readonly NgUnderlay: "HSCore.Model.Underlay";
  /** 墙板踢脚线 */
  readonly NgWallBoardBaseboard: "HSCore.Model.WallBoardBaseboard";
  /** 墙板腰线 */
  readonly NgWallBoardWaistLine: "HSCore.Model.WallBoardWaistLine";
  /** 图案 */
  readonly NgPattern: "HSCore.Model.Pattern";
  /** 块 */
  readonly NgBlock: "HSCore.Model.Block";
  /** 二维点 */
  readonly Point2D: "HSCore.Model.Point2D";
  /** 二维曲线基类 */
  readonly Curve2d: "HSCore.Model.Curve2d";
  /** 二维直线 */
  readonly Line2d: "HSCore.Model.Line2d";
  /** 二维面 */
  readonly Face2d: "HSCore.Model.Face2d";
  /** 二维草图 */
  readonly Sketch2d: "HSCore.Model.Sketch2d";
  /** 二维圆 */
  readonly Circle2d: "HSCore.Model.Circle2d";
  /** 二维圆弧 */
  readonly CircleArc2d: "HSCore.Model.CircleArc2d";
  /** 形状 */
  readonly Shape: "HSCore.Model.Shape";
  /** 区域 */
  readonly Region: "HSCore.Model.Region";
  /** 腰线 */
  readonly Waistline: "HSCore.Model.Waistline";
  /** 多边形 */
  readonly Polygon: "HSCore.Model.Polygon";
  /** 线框 */
  readonly Wire: "HScore.Model.Wire";
  /** 混合涂料 */
  readonly MixPaint: "HSCore.Model.Mixpaint";
  /** 边界 */
  readonly Boundary: "HSCore.Model.Boundary";
  /** 网格（重复） */
  readonly Grid: "HSCore.Model.Grid";
  /** 混合网格 */
  readonly MixGrid: "HSCore.Model.MixGrid";
  /** 混合块 */
  readonly MixBlock: "HSCore.Model.MixBlock";
  /** 边界块 */
  readonly BoundaryBlock: "HSCore.Model.BoundaryBlock";
  /** 图案网格 */
  readonly PatternGrid: "HSCore.Model.PatternGrid";
  /** 图案块 */
  readonly PatternBlock: "HSCore.Model.PatternBlock";
  /** 自由图案网格 */
  readonly FreePatternGrid: "HSCore.Model.FreePatternGrid";
  /** 自由图案块 */
  readonly FreePatternBlock: "HSCore.Model.FreePatternBlock";
  /** 角撑块 */
  readonly GussetBlock: "HSCore.Model.GussetBlock";
  /** 角撑面 */
  readonly GussetSurface: "HSCore.Model.GussetSurface";
  /** 角撑组 */
  readonly GussetGroup: "HSCore.Model.GussetGroup";
  /** 水刀拼花瓷砖 */
  readonly WaterJetTile: "HSCore.Model.WaterJetTile";
  /** 装饰草图 */
  readonly DecorateSketch2d: "HSCore.Model.DecorateSketch2d";
  /** 自定义特征模型 */
  readonly CustomizedFeatureModel: "HSCore.Model.CustomizedFeatureModel";
  /** 自定义吊顶模型 */
  readonly CustomizedCeilingModel: "HSCore.Model.CustomizedCeilingModel";
  /** 自定义背景墙 */
  readonly CustomizedBackgroundWall: "HSCore.Model.CustomizedBackgroundWall";
  /** 自定义地台 */
  readonly CustomizedPlatform: "HSCore.Model.CustomizedPlatform";
  /** 新版自定义参数化吊顶 */
  readonly NCustomizedParametricCeiling: "HSCore.Model.NCustomizedParametricCeiling";
  /** 新版自定义特征模型 */
  readonly NCustomizedFeatureModel: "HSCore.Model.NCustomizedFeatureModel";
  /** 新版自定义吊顶模型 */
  readonly NCustomizedCeilingModel: "HSCore.Model.NCustomizedCeilingModel";
  /** 新版自定义背景墙 */
  readonly NCustomizedBackgroundWall: "HSCore.Model.NCustomizedBackgroundWall";
  /** 新版自定义地台 */
  readonly NCustomizedPlatform: "HSCore.Model.NCustomizedPlatform";
  /** 动态装配体 */
  readonly DAssembly: "HSCore.Model.DAssembly";
  /** 动态拉伸 */
  readonly DExtruding: "HSCore.Model.DExtruding";
  /** 动态线条 */
  readonly DMolding: "HSCore.Model.DMolding";
  /** 动态内容物 */
  readonly DContent: "HSCore.Model.DContent";
  /** 动态孔洞 */
  readonly DHole: "HSCore.Model.DHole";
  /** 天空盒 */
  readonly Skybox: "HSCore.Model.Skybox";
  /** 材质数据 */
  readonly MaterialData: "HSCore.Material.MaterialData";
  /** 状态基类 */
  readonly State: "HSCore.State";
  /** 点状态 */
  readonly PointState: "HSCore.State.PointState";
  /** 二维点状态 */
  readonly Point2DState: "HSCore.State.Point2DState";
  /** 数组状态 */
  readonly ArrayState: "HSCore.State.ArrayState";
  /** 二维圆弧状态 */
  readonly Arc2DState: "HSCore.State.Arc2DState";
  /** 约束基类 */
  readonly Constraint: "HSCore.Constraint";
  /** 方程约束 */
  readonly EquationConstraint: "HSCore.Constraint.EquationConstraint";
  /** 位置约束 */
  readonly PositionConstraint: "HSCore.Constraint.PositionConstraint";
  /** 隐蔽工程 */
  readonly ConcealedWork: "HSCore.Model.ConcealedWork";
  /** 隐蔽工程节点 */
  readonly ConcealedWorkNode: "HSCore.Model.ConcealedWorkNode";
  /** 隐蔽工程树 */
  readonly ConcealedWorkTree: "HSCore.Model.ConcealedWorkTree";
  /** 隐蔽工程照明树 */
  readonly ConcealedWorkLightTree: "HSCore.Model.ConcealedWorkLightTree";
  /** 隐蔽工程管道树 */
  readonly ConcealedWorkTubeTree: "HSCore.Model.ConcealedWorkTubeTree";
  /** 隐蔽工程电线 */
  readonly ConcealedWorkLightWire: "HSCore.Model.ConcealedWorkLightWire";
  /** 隐蔽工程管道 */
  readonly ConcealedWorkTube: "HSCore.Model.ConcealedWorkTube";
  /** 房间 */
  readonly Room: "HSCore.Model.Room";
};

/**
 * 类名关联映射表
 * 
 * 用于反向查找和类型别名解析。
 * 键为完整类名字符串，值为规范类名。
 * 
 * @remarks
 * - 大部分映射为恒等映射（键值相同）
 * - 特殊情况：Room映射到NgFloor（房间继承自地板）
 */
export declare const relatedClass: Record<string, string>;