/**
 * CSS Module Exports
 * This file represents CSS module class names exported as a typed object.
 * Generated from a webpack CSS loader chain with CSS Modules enabled.
 */

/**
 * CSS Module class names mapping
 * Keys are the original class names defined in the CSS file,
 * values are the hashed/scoped class names generated by CSS Modules.
 */
interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Default export containing all CSS class names from the module.
 * Returns undefined if no local classes are defined.
 * 
 * @example
 * import styles from './styles.module.css';
 * <div className={styles.container}>Content</div>
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-export all named exports from the original CSS module.
 * Each export corresponds to a CSS class name that can be imported directly.
 * 
 * @example
 * import { container, button } from './styles.module.css';
 */
export * from './original-css-module';