/**
 * Webpack asset module that exports the URL path to a toolbar folder icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type,
 * which processes static assets and returns their public URL.
 * 
 * @module ToolbarFolderIcon
 */

/**
 * The public URL path to the toolbar folder SVG icon asset.
 * This path is resolved by the bundler and points to the optimized asset location.
 * 
 * File: toolbarfoldier.72043530.svg
 * Hash: 72043530 (content-based hash for cache busting)
 */
declare const toolbarFolderIconPath: string;

export default toolbarFolderIconPath;