/**
 * BOM Description Asset Module
 * 
 * This module exports the path to a static BOM (Bill of Materials) description GIF image.
 * The image is processed by webpack's asset pipeline and made available at runtime.
 * 
 * @module bom_description
 * @author Original Module ID: 279565
 */

/**
 * The resolved public path to the BOM description GIF asset.
 * 
 * This string contains the full URL path where the image can be accessed,
 * typically in the format: `/assets/bom_description.d7c02312.gif`
 * 
 * The hash suffix (d7c02312) is generated by webpack for cache busting purposes
 * and will change when the asset content changes.
 * 
 * @example
 *