/**
 * Asset module that exports the file path for the wall opacity SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module WallOpacitySvg
 */

/**
 * The public URL path to the wall opacity SVG asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *