/**
 * CSS Module definition for module_197538
 * This module handles CSS-in-JS style injection and exports CSS module class names
 */

/**
 * CSS Module class names mapping
 * Contains locally scoped class names generated by CSS Modules
 */
interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Style injection configuration options
 */
interface StyleInjectionOptions {
  /**
   * Function to transform and inject style tags into the DOM
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * Function to insert style elements into a specific DOM location
   * Bound to insert into 'head' element
   */
  insert: (target: string) => void;
  
  /**
   * DOM API interface for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports
 * Provides access to all named exports from the CSS module except 'default'
 */
export * from './styles.module.css';

/**
 * Default export containing CSS Module class names
 * Returns the locally scoped class name mappings, or undefined if not available
 */
declare const cssModuleLocals: CSSModuleClasses | undefined;

export default cssModuleLocals;