/**
 * Webpack asset module that exports the URL path to an SVG info icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module InfoIconAsset
 */

/**
 * The public URL path to the info.svg asset file.
 * The hash (593d93e6) is generated by webpack for cache-busting purposes.
 * 
 * @example
 *