/**
 * 模型类名映射模块
 * 提供短类名与长类名之间的双向映射关系
 */

/**
 * 模型类的完整命名空间路径（长名称）
 * 使用 Readonly 确保枚举值不可变
 */
export const enum ModelClass {
  Association = "HSCore.Model.Association",
  PointOnLineAssociation = "HSCore.Model.PointOnLineAssociation",
  EdgeOnLineAssociation = "HSCore.Model.EdgeOnLineAssociation",
  PointOnPointAssociation = "HSCore.Model.PointOnPointAssociation",
  ArcCurve = "HSCore.Model.ArcCurve",
  AuxiliaryLine = "HSCore.Model.AuxiliaryLine",
  NgVertex = "HSCore.Model.Vertex",
  NgWall = "HSCore.Model.Wall",
  NgFloorplan = "HSCore.Model.Floorplan",
  NgEntity = "HSCore.Model.Entity",
  NgEdge = "HSCore.Model.Edge",
  NgCoEdge = "HSCore.Model.CoEdge",
  NgFace = "HSCore.Model.Face",
  NgLoop = "HSCore.Model.Loop",
  NgHole = "HSCore.Model.Hole",
  NgDoor = "HSCore.Model.Door",
  NgWindow = "HSCore.Model.Window",
  NgOpening = "HSCore.Model.Opening",
  NgContent = "HSCore.Model.Content",
  NgSoftCloth = "HSCore.Model.SoftCloth",
  NgCamera = "HSCore.Model.Camera",
  Slab = "HSCore.Model.Slab",
  SlabFace = "HSCore.Model.SlabFace",
  BaseProfile = "HSCore.Model.BaseProfile",
  SideFace = "HSCore.Model.SideFace",
  Layer = "HSCore.Model.Layer",
  Scene = "HSCore.Model.Scene",
  NgPocket = "HSCore.Model.Pocket",
  NgCustomizedModel = "HSCore.Model.CustomizedModel",
  CustomizedModelMolding = "HSCore.Model.CustomizedModelMolding",
  CustomizedModelLightSlot = "HSCore.Model.CustomizedModelLightSlot",
  CustomizedModelLightBand = "HSCore.Model.CustomizedModelLightBand",
  CustomizedPMModel = "HSCore.Model.CustomizedPMModel",
  CustomizedPMInstanceModel = "HSCore.Model.CustomizedPMInstanceModel",
  NCustomizedModelMolding = "HSCore.Model.NCustomizedModelMolding",
  NCustomizedModelLightSlot = "HSCore.Model.NCustomizedModelLightSlot",
  NCustomizedModelLightBand = "HSCore.Model.NCustomizedModelLightBand",
  NCustomizedStructure = "HSCore.Model.NCustomizedStructure",
  NCustomizedSquareColumn = "HSCore.Model.NCustomizedSquareColumn",
  NCustomizedCircleColumn = "HSCore.Model.NCustomizedCircleColumn",
  NCustomizedFlue = "HSCore.Model.NCustomizedFlue",
  NCustomizedRiser = "HSCore.Model.NCustomizedRiser",
  NCustomizedOutlet = "HSCore.Model.NCustomizedOutlet",
  NCustomizedBeam = "HSCore.Model.NCustomizedBeam",
  NgMolding = "HSCore.Model.Molding",
  NgWallMolding = "HSCore.Model.WallMolding",
  NgCornice = "HSCore.Model.Cornice",
  NgBaseboard = "HSCore.Model.Baseboard",
  Mitre = "HSCore.Model.Mitre",
  NgFloor = "HSCore.Model.Floor",
  NgCeiling = "HSCore.Model.Ceiling",
  NgMaterial = "HSCore.Model.Material",
  NgGroup = "HSCore.Model.Group",
  NgPModel = "HSCore.Model.PModel",
  NgPBox = "HSCore.Model.PBox",
  NgPExtruding = "HSCore.Model.PExtruding",
  NgPContent = "HSCore.Model.PContent",
  NgPMolding = "HSCore.Model.PMolding",
  DSweep = "HSCore.Model.DSweep",
  NgPAssembly = "HSCore.Model.PAssembly",
  NgPSegmentLoft = "HSCore.Model.PSegmentLoft",
  NgPSlidingDoor = "HSCore.Model.PSlidingDoor",
  NgPSlidingDoorLeaf = "HSCore.Model.PSlidingDoorLeaf",
  NgCornerWindow = "HSCore.Model.CornerWindow",
  NgBayWindow = "HSCore.Model.BayWindow",
  NgCornerFlatWindow = "HSCore.Model.CornerFlatWindow",
  NgPOrdinaryWindow = "HSCore.Model.POrdinaryWindow",
  NgParametricModel = "HSCore.Model.ParametricModel",
  NgParametricExtrudedBody = "HSCore.Model.Parametrization.ExtrudedBody",
  NgParametricWall = "HSCore.Model.Parametrization.Wall",
  NgParametricWindow = "HSCore.Model.Parametrization.Window",
  NgParametricWindowCeiling = "HSCore.Model.Parametrization.WindowCeiling",
  NgParametricWindowSill = "HSCore.Model.Parametrization.WindowSill",
  NgParametricWindowHole = "HSCore.Model.Parametrization.WindowHole",
  NgParametricWindowPocket = "HSCore.Model.Parametrization.WindowPocket",
  NgBeam = "HSCore.Model.Beam",
  NgObstacle = "HSCore.Model.Obstacle",
  NgColumn = "HSCore.Model.Column",
  NgFlue = "HSCore.Model.Flue",
  NgCurtain = "HSCore.Model.Curtain",
  NgLight = "HSCore.Model.Light",
  NgGrid = "HSCore.Model.Grid",
  NgDirectionLight = "HSCore.Model.DirectionLight",
  NgVirtualAreaLight = "HSCore.Model.VirtualAreaLight",
  NgFlatLight = "HSCore.Model.FlatLight",
  NgEllipseLight = "HSCore.Model.EllipseLight",
  NgPointLight = "HSCore.Model.PointLight",
  NgSpotLight = "HSCore.Model.SpotLight",
  NgAttenuatedSpotLight = "HSCore.Model.AttenuatedSpotLight",
  NgMeshLight = "HSCore.Model.MeshLight",
  NgPhysicalLight = "HSCore.Model.PhysicalLight",
  NgAsmPhysicalLight = "HSCore.Model.AsmPhysicalLight",
  NgSpotPhysicalLight = "HSCore.Model.SpotPhysicalLight",
  NgLightSubGroup = "HSCore.Model.NgLightSubGroup",
  NgAsmLightSubGroup = "HSCore.Model.NgAsmLightSubGroup",
  NgLightGroup = "HSCore.Model.LightGroup",
  NgSewerPipe = "HSCore.Model.SewerPipe",
  NgUnderlay = "HSCore.Model.Underlay",
  NgWallBoardBaseboard = "HSCore.Model.WallBoardBaseboard",
  NgWallBoardWaistLine = "HSCore.Model.WallBoardWaistLine",
  NgPattern = "HSCore.Model.Pattern",
  NgBlock = "HSCore.Model.Block",
  Point2D = "HSCore.Model.Point2D",
  Curve2d = "HSCore.Model.Curve2d",
  Line2d = "HSCore.Model.Line2d",
  Face2d = "HSCore.Model.Face2d",
  GuideLine2d = "HSCore.Model.GuideLine2d",
  Sketch2d = "HSCore.Model.Sketch2d",
  Circle2d = "HSCore.Model.Circle2d",
  CircleArc2d = "HSCore.Model.CircleArc2d",
  Shape = "HSCore.Model.Shape",
  Region = "HSCore.Model.Region",
  Waistline = "HSCore.Model.Waistline",
  Polygon = "HSCore.Model.Polygon",
  Wire = "HScore.Model.Wire",
  MixPaint = "HSCore.Model.Mixpaint",
  MixPaintDecorator = "HSCore.Model.MixPaintDecorator",
  Boundary = "HSCore.Model.Boundary",
  Grid = "HSCore.Model.Grid",
  MixGrid = "HSCore.Model.MixGrid",
  MixBlock = "HSCore.Model.MixBlock",
  BoundaryBlock = "HSCore.Model.BoundaryBlock",
  PatternGrid = "HSCore.Model.PatternGrid",
  PatternBlock = "HSCore.Model.PatternBlock",
  FreePatternGrid = "HSCore.Model.FreePatternGrid",
  FreePatternBlock = "HSCore.Model.FreePatternBlock",
  GussetBlock = "HSCore.Model.GussetBlock",
  GussetSurface = "HSCore.Model.GussetSurface",
  GussetGroup = "HSCore.Model.GussetGroup",
  WaterJetTile = "HSCore.Model.WaterJetTile",
  MixSketch2d = "HSCore.Model.MixSketch2d",
  DecorateSketch2d = "HSCore.Model.DecorateSketch2d",
  CustomizedFeatureModel = "HSCore.Model.CustomizedFeatureModel",
  CustomizedCeilingModel = "HSCore.Model.CustomizedCeilingModel",
  CustomizedBackgroundWall = "HSCore.Model.CustomizedBackgroundWall",
  CustomizedPlatform = "HSCore.Model.CustomizedPlatform",
  NCustomizedFeatureModel = "HSCore.Model.NCustomizedFeatureModel",
  NCustomizedSketchModel = "HSCore.Model.NCustomizedSketchModel",
  NCustomizedCeilingModel = "HSCore.Model.NCustomizedCeilingModel",
  NCustomizedBackgroundWall = "HSCore.Model.NCustomizedBackgroundWall",
  NCustomizedPlatform = "HSCore.Model.NCustomizedPlatform",
  NCustomizedParametricModel = "HSCore.Model.NCustomizedParametricModel",
  NCustomizedParametricCeiling = "HSCore.Model.NCustomizedParametricCeiling",
  NCustomizedParametricRoof = "HSCore.Model.NCustomizedParametricRoof",
  NCustomizedParametricStairs = "HSCore.Model.NCustomizedParametricStairs",
  ParametricOpening = "HSCore.Model.ParametricOpening",
  NCPBackgroundWallBase = "HSCore.Model.NCPBackgroundWallBase",
  ParametricContentBase = "HSCore.Model.ParametricContentBase",
  ParametricCurtain = "HSCore.Model.ParametricCurtain",
  ParametricBathroomCabinet = "HSCore.Model.ParametricBathroomCabinet",
  ParametricDoor = "HSCore.Model.ParametricDoor",
  ParametricModelArray = "HSCore.Model.ParametricModelArray",
  ParametricContentSubpart = "HSCore.Model.ParametricContentSubpart",
  NCustomizedParametricBackgroundWall = "HSCore.Model.NCustomizedParametricBackgroundWall",
  NCPBackgroundWallUnit = "HSCore.Model.NCPBackgroundWallUnit",
  NCPBackgroundWallSubpart = "HSCore.Model.NCPBackgroundWallSubpart",
  NCPBackgroundWallContent = "HSCore.Model.NCPBackgroundWallContent",
  ParametricModelContent = "HSCore.Model.ParametricModelContent",
  NCPBackgroundWallArray = "HSCore.Model.NCPBackgroundWallArray",
  DAssembly = "HSCore.Model.DAssembly",
  DOpening = "HSCore.Model.DOpening",
  DExtruding = "HSCore.Model.DExtruding",
  SpaceHole = "HSCore.Model.SpaceHole",
  DMolding = "HSCore.Model.DMolding",
  DContent = "HSCore.Model.DContent",
  DHole = "HSCore.Model.DHole",
  DWindow = "HSCore.Model.DWindow",
  Skybox = "HSCore.Model.Skybox",
  MaterialData = "HSCore.Material.MaterialData",
  State = "HSCore.State",
  PointState = "HSCore.State.PointState",
  Point2DState = "HSCore.State.Point2DState",
  ArrayState = "HSCore.State.ArrayState",
  Arc2DState = "HSCore.State.Arc2DState",
  Constraint = "HSCore.Constraint",
  EquationConstraint = "HSCore.Constraint.EquationConstraint",
  PositionConstraint = "HSCore.Constraint.PositionConstraint",
  ConcealedWork = "HSCore.Model.ConcealedWork",
  ConcealedWorkCompEntity = "HSCore.Model.ConcealedWorkCompEntity",
  ConcealedWorkNode = "HSCore.Model.ConcealedWorkNode",
  ConcealedWorkTree = "HSCore.Model.ConcealedWorkTree",
  ConcealedWorkLightTree = "HSCore.Model.ConcealedWorkLightTree",
  ConcealedWorkTubeTree = "HSCore.Model.ConcealedWorkTubeTree",
  ConcealedWorkLightWire = "HSCore.Model.ConcealedWorkLightWire",
  ConcealedWorkTube = "HSCore.Model.ConcealedWorkTube",
  ConcealedWorkPowerSys = "HSCore.Model.ConcealedWorkPowerSys",
  ConcealedWorkCircuit = "HSCore.Model.ConcealedWorkCircuit",
  ConcealedWorkLightControlSys = "HSCore.Model.ConcealedWorkLightControlSys",
  ConcealedWorkLightLogic = "HSCore.Model.ConcealedWorkLightLogic",
  MeshContent = "HSCore.Model.MeshContent",
  WallFaceAssembly = "HSCore.Model.WallFaceAssembly",
  RoofsDrawing = "HSCore.Model.RoofsDrawing",
  RoofDrawingRegion = "HSCore.Model.RoofDrawingRegion"
}

/**
 * 长类名到短类名的映射表
 * 用于序列化时压缩类名以减少数据体积
 */
export declare const ClassLNameToSName: ReadonlyMap<string, string>;

/**
 * 短类名到长类名的映射表
 * 用于反序列化时还原完整的类名路径
 */
export declare const ClassSNameToLName: ReadonlyMap<string, string>;