/**
 * Iterator cleanup helper function
 * Ensures proper cleanup of iterators in try-finally blocks
 * Typically used in for-of loops and iterator consumption patterns
 * 
 * @remarks
 * This function is commonly generated by TypeScript/Babel when transpiling
 * code that uses iterators with proper resource cleanup semantics.
 */

/**
 * Cleans up an iterator by calling its return method if available
 * @param hasError - Whether an error occurred during iteration
 * @param iterator - The iterator object to clean up, may have an optional return method
 * @throws Re-throws the error if hasError is true after cleanup
 */
declare function cleanupIterator(
  hasError: boolean,
  iterator: Iterator<unknown> | AsyncIterator<unknown> | null | undefined
): void;

/**
 * Extended iterator interface that includes optional return method
 */
interface IteratorWithReturn<T = unknown> extends Iterator<T> {
  /**
   * Optional method called when iteration is terminated early
   * @returns An iterator result indicating completion
   */
  return?(): IteratorResult<T>;
}

/**
 * Async iterator interface with optional return method
 */
interface AsyncIteratorWithReturn<T = unknown> extends AsyncIterator<T> {
  /**
   * Optional method called when async iteration is terminated early
   * @returns A promise resolving to an iterator result
   */
  return?(): Promise<IteratorResult<T>>;
}