export interface HdrDatabase {
  UID: {
    LJZ_DAY: string;
    PEOPLES_SQUARE: string;
    PEOPLES_SQUARE_DAWN: string;
    NORTH_EURO_CITY: string;
    BAY_TOUR: string;
    VENICE_DAWN: string;
    UMHLANGA_SUNRISE: string;
    SEA_SKY: string;
    NORTHERN_SNOW: string;
    EURO_GARDEN: string;
    CITY_PARK: string;
    RURAL_SPRING_SCENE: string;
    MORNING: string;
    SUNNY_VONDELPARK: string;
    FALLEN_LEAVES: string;
    AUTUMN_SCENE: string;
    MOUNTAIN_LEDGE: string;
    NOOUTDOORSCENE: string;
    SMALL_HARBOR_NIGHT: string;
    KONIGSALLEE_NIGHT: string;
    VENICE_DAWN_NIGHT: string;
    BELL_PARK_DAWN_NIGHT: string;
    KIARA_DUSK_NIGHT: string;
    LJZ_NIGHT: string;
    WUHAN_NIGHT: string;
    SHENZHEN_NIGHT: string;
    PEOPLES_SQUARE_NIGHT: string;
    MOONLIT_GLOF: string;
    O_EILENRIEDE_PARK: string;
    O_BERGEN: string;
    O_CITY_PARK: string;
    O_LILIENSTEIN: string;
    O_FELSENLABYRINTH: string;
    O_SEA_SKY: string;
    O_RED_HILL_CURVE: string;
    O_RAILWAY_BRIDGES: string;
    O_QWANTANI: string;
    O_HILLTOP: string;
    O_RUSTIG: string;
    O_SNOWY_PARK: string;
    O_BLANK: string;
    G_VRSKY: string;
    G_CANARY_WHARF: string;
    G_KONIGSALLEE: string;
    G_PORTLAND: string;
    G_AUTUMN_PARK: string;
    G_BANK: string;
    G_LJZ_DAY: string;
    G_PEOPLES_SQUARE: string;
    G_PEOPLES_SQUARE_DAWN: string;
    G_NORTH_EURO_CITY: string;
    G_CITY_PARK: string;
    G_RURAL_SPRING_SCENE: string;
    G_EURO_GARDEN: string;
    G_MORNING: string;
    G_SUNNY_VONDELPARK: string;
    G_BAY_TOUR: string;
    G_VENICE_DAWN: string;
    G_SEA_SKY: string;
    G_UMHLANGA_SUNRISE: string;
    G_NORTHERN_SNOW: string;
    G_LILIENSTEIN: string;
    G_FALLEN_LEAVES: string;
    G_AUTUMN_SCENE: string;
    G_MOUNTAIN_LEDGE: string;
    G_QWANTANI: string;
    G_RAILWAY_BRIDGES: string;
    G_RED_HILL_CURVE: string;
    G_HILLTOP: string;
    G_NOOUTDOORSCENE: string;
    V_LYTH_WOOD_FIELD: string;
    V_SHUDULAKE: string;
    V_SIMONS_TOWN: string;
    V_DREIFALT: string;
    V_LAKE: string;
    V_FOREST_PARK: string;
    C_LJZ_DAY: string;
    C_PEOPLES_SQUARE: string;
    C_PEOPLES_SQUARE_DAWN: string;
    C_NORTH_EURO_CITY: string;
    C_BAY_TOUR: string;
    C_VENICE_DAWN: string;
    C_UMHLANGA_SUNRISE: string;
    C_SEA_SKY: string;
    C_NORTHERN_SNOW: string;
    C_EURO_GARDEN: string;
    C_CITY_PARK: string;
    C_RURAL_SPRING_SCENE: string;
    C_MORNING: string;
    C_SUNNY_VONDELPARK: string;
    C_FALLEN_LEAVES: string;
    C_AUTUMN_SCENE: string;
    C_MOUNTAIN_LEDGE: string;
    C_NOOUTDOORSCENE: string;
    VD_COASTAL_DUSK: string;
    VD_GATA_DUSK: string;
    VD_ELLE_DUSK: string;
    VD_SIMONS_TOWN: string;
    VD_DREIFALT: string;
    VD_FOREST_PARK: string;
    VN_LYTH_WOOD_FIELD: string;
    VN_SHUDULAKE: string;
    VN_SIMONS_TOWN: string;
    VN_DREIFALT: string;
    VN_LAKE: string;
    VN_FOREST_PARK: string;
  };
}

export const HDR_DATABASE: HdrDatabase = {
  UID: {
    LJZ_DAY: "ljz_day",
    PEOPLES_SQUARE: "peoples_square",
    PEOPLES_SQUARE_DAWN: "peoples_square_dawn",
    NORTH_EURO_CITY: "north_euro_city",
    BAY_TOUR: "bay_tour",
    VENICE_DAWN: "venice_dawn",
    UMHLANGA_SUNRISE: "umhlanga_sunrise",
    SEA_SKY: "sea_sky",
    NORTHERN_SNOW: "northern_snow",
    EURO_GARDEN: "euro_garden",
    CITY_PARK: "city_park",
    RURAL_SPRING_SCENE: "rural_spring_scene",
    MORNING: "morning",
    SUNNY_VONDELPARK: "sunny_vondelpark",
    FALLEN_LEAVES: "fallen_leaves",
    AUTUMN_SCENE: "autumn_scene",
    MOUNTAIN_LEDGE: "mountain_ledge",
    NOOUTDOORSCENE: "nooutdoor",
    SMALL_HARBOR_NIGHT: "small_harbor_night",
    KONIGSALLEE_NIGHT: "konigsallee_night",
    VENICE_DAWN_NIGHT: "venice_dawn_night",
    BELL_PARK_DAWN_NIGHT: "bell_park_dawn_night",
    KIARA_DUSK_NIGHT: "kiara_dusk_night",
    LJZ_NIGHT: "ljz_night",
    WUHAN_NIGHT: "wuhan_night",
    SHENZHEN_NIGHT: "shenzhen_night",
    PEOPLES_SQUARE_NIGHT: "peoples_square_night",
    MOONLIT_GLOF: "moonlit_golf",
    O_EILENRIEDE_PARK: "eilenriede_park",
    O_BERGEN: "bergen",
    O_CITY_PARK: "o_city_park",
    O_LILIENSTEIN: "lilienstein",
    O_FELSENLABYRINTH: "felsenlabyrinth",
    O_SEA_SKY: "o_sea_sky",
    O_RED_HILL_CURVE: "red_hill_curve",
    O_RAILWAY_BRIDGES: "railway_bridges",
    O_QWANTANI: "qwantani",
    O_HILLTOP: "hilltop",
    O_RUSTIG: "rustig",
    O_SNOWY_PARK: "snowy_park",
    O_BLANK: "o_blank",
    G_VRSKY: "g_vrsky",
    G_CANARY_WHARF: "g_canary_wharf",
    G_KONIGSALLEE: "g_konigsallee",
    G_PORTLAND: "g_portland",
    G_AUTUMN_PARK: "g_autumn_park",
    G_BANK: "g_bank",
    G_LJZ_DAY: "g_ljz_day",
    G_PEOPLES_SQUARE: "g_peoples_square",
    G_PEOPLES_SQUARE_DAWN: "g_peoples_square_dawn",
    G_NORTH_EURO_CITY: "g_north_euro_city",
    G_CITY_PARK: "g_city_park",
    G_RURAL_SPRING_SCENE: "g_rural_spring_scene",
    G_EURO_GARDEN: "g_euro_garden",
    G_MORNING: "g_morning",
    G_SUNNY_VONDELPARK: "g_sunny_vondelpark",
    G_BAY_TOUR: "g_bay_tour",
    G_VENICE_DAWN: "g_venice_dawn",
    G_SEA_SKY: "g_sea_sky",
    G_UMHLANGA_SUNRISE: "g_umhlanga_sunrise",
    G_NORTHERN_SNOW: "g_northern_snow",
    G_LILIENSTEIN: "g_lilienstein",
    G_FALLEN_LEAVES: "g_fallen_leaves",
    G_AUTUMN_SCENE: "g_autumn_scene",
    G_MOUNTAIN_LEDGE: "g_mountain_ledge",
    G_QWANTANI: "g_qwantani",
    G_RAILWAY_BRIDGES: "g_railway_bridges",
    G_RED_HILL_CURVE: "g_red_hill_curve",
    G_HILLTOP: "g_hilltop",
    G_NOOUTDOORSCENE: "g_nooutdoor",
    V_LYTH_WOOD_FIELD: "v_lyth_wood_field",
    V_SHUDULAKE: "v_shudulake",
    V_SIMONS_TOWN: "v_simons_town_rocks",
    V_DREIFALT: "v_dreifaltigkeitsberg",
    V_LAKE: "v_lake",
    V_FOREST_PARK: "v_forest_park",
    C_LJZ_DAY: "c_ljz_day",
    C_PEOPLES_SQUARE: "c_peoples_square",
    C_PEOPLES_SQUARE_DAWN: "c_peoples_square_dawn",
    C_NORTH_EURO_CITY: "c_north_euro_city",
    C_BAY_TOUR: "c_bay_tour",
    C_VENICE_DAWN: "c_venice_dawn",
    C_UMHLANGA_SUNRISE: "c_umhlanga_sunrise",
    C_SEA_SKY: "c_sea_sky",
    C_NORTHERN_SNOW: "c_northern_snow",
    C_EURO_GARDEN: "c_euro_garden",
    C_CITY_PARK: "c_city_park",
    C_RURAL_SPRING_SCENE: "c_rural_spring_scene",
    C_MORNING: "c_morning",
    C_SUNNY_VONDELPARK: "c_sunny_vondelpark",
    C_FALLEN_LEAVES: "c_fallen_leaves",
    C_AUTUMN_SCENE: "c_autumn_scene",
    C_MOUNTAIN_LEDGE: "c_mountain_ledge",
    C_NOOUTDOORSCENE: "c_nooutdoor",
    VD_COASTAL_DUSK: "vd_coastal_dusk",
    VD_GATA_DUSK: "vd_gata_dusk",
    VD_ELLE_DUSK: "vd_elle_dusk",
    VD_SIMONS_TOWN: "vd_simons_town_rocks",
    VD_DREIFALT: "vd_dreifaltigkeitsberg",
    VD_FOREST_PARK: "vd_forest_park",
    VN_LYTH_WOOD_FIELD: "vn_lyth_wood_field",
    VN_SHUDULAKE: "vn_shudulake",
    VN_SIMONS_TOWN: "vn_simons_town_rocks",
    VN_DREIFALT: "vn_dreifaltigkeitsberg",
    VN_LAKE: "vn_lake",
    VN_FOREST_PARK: "vn_forest_park"
  }
};

export const HdrNameList: ReadonlyArray<string> = Object.freeze(
  Object.values(HDR_DATABASE.UID)
);