/**
 * Webpack asset module that exports the URL path to the duplicate icon SVG file.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 * 
 * @module DuplicateIconAsset
 */

/**
 * The file path/URL to the duplicate.svg icon asset.
 * This path is resolved by the bundler and includes content hash for cache busting.
 * 
 * @example
 *