/**
 * Asset module that exports the path to the lightband flip SVG image.
 * This is typically generated by webpack's asset/resource module loader.
 */

/**
 * The public URL path to the lightband_flip.svg asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *