/**
 * Asset module that exports the path to the right_delete SVG icon.
 * This is typically generated by webpack's asset/resource loader.
 * 
 * @module RightDeleteIcon
 */

/**
 * The public path to the right_delete.svg icon asset.
 * This path is resolved by the build tool and points to the bundled SVG file.
 * 
 * @example
 *