/**
 * Asset module that exports the path to the baseline SVG icon.
 * This module is typically generated by Webpack's asset/resource module
 * to handle static file imports with content hashing for cache busting.
 */

/**
 * The public path to the baseline.svg asset file.
 * The filename includes a content hash (875b89da) for cache invalidation.
 * 
 * @example
 *