/**
 * Asset path declaration for material select outline active SVG icon.
 * 
 * This module exports the webpack-generated URL path to the material select
 * material outline active icon asset. The path is automatically resolved
 * by the build system and includes content hash for cache busting.
 * 
 * @module MaterialSelectOutlineActiveAsset
 */

/**
 * The resolved URL path to the material_select_material_outline_active SVG icon.
 * 
 * This path is dynamically generated by webpack during the build process and
 * includes the public path prefix and content hash (3622c2f9) for optimal
 * browser caching.
 * 
 * @example
 *