/**
 * Asset module that exports the URL path to the cone shape image asset.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module ConeShapeAsset
 */

/**
 * The public URL path to the cone_shape.jpg image asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *