/**
 * Asset module that exports the URL path to a red SVG icon.
 * This module is typically generated by Webpack's asset module system
 * for handling static file imports.
 * 
 * @module RedIconAsset
 */

/**
 * The public URL path to the red.svg asset file.
 * The hash in the filename (46e89af3) is used for cache busting.
 * 
 * @example
 *