/**
 * Asset module that exports the file path for an up arrow SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module UpArrowAsset
 */

/**
 * The public URL path to the up arrow SVG asset.
 * Points to the compiled/hashed asset file in the build output.
 * 
 * @example
 *