/**
 * Asset module that exports the path to the snap_from SVG icon.
 * This module is typically generated by Webpack's asset/resource loader
 * to handle static file imports in the bundle.
 * 
 * @module snap_from_asset
 */

/**
 * The public path to the snap_from.svg asset file.
 * This path is resolved relative to the application's public URL base.
 * 
 * @example
 *