/**
 * CSS Module type definitions
 * 
 * This module handles CSS/style injection and exports CSS module class names.
 * Typically generated by webpack css-loader with modules enabled.
 */

/**
 * CSS Module class names mapping
 * Maps semantic class names to their hashed/scoped equivalents
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style injection options configuration
 */
export interface StyleInjectionOptions {
  /** Transform function to apply to style tags before insertion */
  styleTagTransform?: StyleTagTransformFunction;
  
  /** Function to set attributes on style elements */
  setAttributes?: SetAttributesFunction;
  
  /** Function to insert style elements into the DOM */
  insert?: InsertFunction;
  
  /** DOM manipulation API */
  domAPI?: DOMAPIFunction;
  
  /** Function to create and insert style elements */
  insertStyleElement?: InsertStyleElementFunction;
}

/**
 * Transforms style content before injection
 */
export type StyleTagTransformFunction = (css: string, style: HTMLStyleElement) => void;

/**
 * Sets attributes on style elements
 */
export type SetAttributesFunction = (style: HTMLStyleElement) => void;

/**
 * Inserts style elements into the DOM at a specific location
 */
export type InsertFunction = (style: HTMLStyleElement) => void;

/**
 * DOM API for style manipulation
 */
export type DOMAPIFunction = (options: StyleInjectionOptions) => void;

/**
 * Creates and inserts style elements
 */
export type InsertStyleElementFunction = (options: StyleInjectionOptions) => HTMLStyleElement;

/**
 * CSS Module with metadata
 */
export interface CSSModule {
  /** The CSS module class names */
  locals?: CSSModuleClasses;
  
  /** Raw CSS content */
  toString(): string;
  
  /** Additional module metadata */
  [key: string]: unknown;
}

/**
 * Default export: CSS module class names mapping
 * Returns undefined if no local class names are defined
 */
declare const cssModuleLocals: CSSModuleClasses | undefined;

export default cssModuleLocals;

/**
 * Re-exported members from the CSS module
 * All named exports from the original module (excluding 'default')
 */
export * from './css-module-source';