/**
 * Webpack asset module that exports the public URL path for the perspective SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module PerspectiveAsset
 */

/**
 * The public URL path to the perspective.svg asset file.
 * The actual path is determined at build time by Webpack and includes
 * a content hash (ee7c8dec) for cache busting.
 * 
 * @example
 *