/**
 * Asset module that exports the path to a clear guideline SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for static file imports.
 * 
 * @module ClearGuidelineAsset
 */

/**
 * The public URL path to the clear_guideline.svg asset.
 * This path is resolved relative to the application's public path
 * and includes a content hash for cache busting.
 * 
 * @example
 *