/**
 * Asset module that exports the URL path to a green SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module GreenSvgAsset
 */

/**
 * The public URL path to the green.svg asset file.
 * This path is resolved by the build tool and includes content hash for cache busting.
 * 
 * @example
 * import greenIconUrl from './green-svg-asset';
 * // greenIconUrl = "assets/green.20e68f85.svg"
 */
declare const greenSvgAssetUrl: string;

export default greenSvgAssetUrl;