/**
 * Asset module that exports the path to the m2 PNG image.
 * This module is generated by Webpack's asset/resource loader.
 */

/**
 * The public path URL to the m2.png asset file.
 * This path is resolved at build time by Webpack and includes the configured public path prefix.
 * 
 * @example
 *