/**
 * Asset module that exports the path to a selected jiheti SVG icon.
 * This is typically generated by a bundler's asset management system.
 */

/**
 * The file path to the jiheti selected state SVG icon asset.
 * This path is resolved relative to the application's public asset directory.
 * 
 * @type {string}
 * @constant
 * @example
 * // Usage in an application
 * import jihetiSelectedIcon from './jiheti-selected-asset';
 * <img src={jihetiSelectedIcon} alt="Jiheti Selected" />
 */
declare const jihetiSelectedIconPath: string;

export default jihetiSelectedIconPath;