/**
 * Asset module that exports the URL path to the offset SVG file.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module OffsetAsset
 */

/**
 * The public URL path to the offset.svg asset file.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *