/**
 * Asset module that exports the URL path to the draw_arc SVG file.
 * This module is typically generated by webpack's asset/resource module type.
 */

/**
 * The public URL path to the draw_arc.e75195f4.svg asset file.
 * This path is resolved relative to the webpack public path configuration.
 * 
 * @example
 *