/**
 * Asset module that exports the URL path to the delete icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module DeleteIconAsset
 * @description Provides the public URL path for the delete.svg icon asset
 */

/**
 * The public URL path to the delete icon SVG asset.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *