/**
 * Webpack asset module that exports the path to a popup light slot GIF image.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module PopupLightSlotAsset
 */

/**
 * The file path to the popup light slot animated GIF asset.
 * This path is resolved relative to the public path configured in Webpack.
 * 
 * @example
 *