/**
 * Asset module that exports the URL path to the perspective hover SVG icon.
 * This file is typically auto-generated by a bundler's asset loading system.
 * 
 * @module PerspectiveHoverAsset
 */

/**
 * The public URL path to the perspective_hover.svg asset file.
 * This path is resolved at build time and points to the bundled asset location.
 * 
 * @example
 *