/**
 * Asset module that exports the file path for a right arrow icon image.
 * This module represents a static asset reference typically generated by Webpack's asset/resource module.
 */

/**
 * The public path URL to the right arrow icon image asset.
 * This path is resolved at build time and points to the hashed image file in the assets directory.
 * 
 * @example
 *