/**
 * Asset module that exports the URL path to the wireframe SVG file.
 * This module is typically generated by a bundler's asset handling system.
 * 
 * @module wireframe-asset
 */

/**
 * The public URL path to the wireframe.svg asset file.
 * This path is resolved at build time and includes content hash for cache busting.
 * 
 * @example
 *