/**
 * Asset module that exports the path to the 'show_all' SVG icon.
 * This file is typically generated by a bundler to handle static asset imports.
 * 
 * @module ShowAllAsset
 */

/**
 * The public URL path to the show_all.svg icon asset.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @example
 *