/**
 * Asset module that exports the path to the lightslot_up SVG image.
 * This is typically used for importing static assets in a web application.
 * 
 * @module AssetModule
 */

/**
 * The relative or absolute URL path to the lightslot_up.svg asset.
 * The hash in the filename (96423acd) is typically generated by the build tool
 * for cache busting purposes.
 * 
 * @type {string}
 * @example
 * // Usage in a component:
 * import lightslotUpImage from './path/to/module';
 * // lightslotUpImage === "assets/lightslot_up.96423acd.svg"
 */
declare const assetPath: string;

export default assetPath;