/**
 * Webpack asset module that exports the URL path to a spinner animation GIF.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module SpinnerAsset
 */

/**
 * The public URL path to the spinner animation asset.
 * This path is resolved at build time by the bundler and points to the
 * optimized/hashed asset file in the output directory.
 * 
 * @example
 *