/**
 * Asset module that exports the URL path to the m6 image asset.
 * This module is typically generated by Webpack's asset/resource module type.
 */

/**
 * The public URL path to the m6.png image asset.
 * The hash (8ba1edae) ensures cache busting when the file content changes.
 * 
 * @example
 *