/**
 * Webpack asset module that exports the URL path to a cancel icon SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module CancelIconAsset
 * @example
 *