/**
 * Webpack asset module that exports the URL path to a question icon SVG file.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module QuestionIconAsset
 */

/**
 * The public URL path to the question icon SVG asset.
 * This path is resolved by the build system and points to the compiled asset location.
 * 
 * @example
 *