/**
 * Webpack asset module that exports the URL path to a lock SVG icon.
 * This module represents a static asset reference that Webpack processes
 * and injects the public path URL for the lock.svg file.
 */

/**
 * The public URL path to the lock SVG icon asset.
 * This path is generated by Webpack during the build process and includes
 * the configured public path plus the hashed filename.
 * 
 * @example
 *