/**
 * Webpack asset module that exports the path to the yakouleft SVG file.
 * This module represents a static asset reference that gets resolved during the build process.
 */

/**
 * The public path to the yakouleft SVG asset.
 * This path is automatically generated by webpack during the build process
 * and includes a content hash (dc1b7cc7) for cache busting.
 * 
 * @example
 *