/**
 * Asset module that exports the path to the view_options SVG icon.
 * This file is typically auto-generated by bundlers like Webpack to handle static assets.
 * 
 * @module ViewOptionsAsset
 */

/**
 * The public path to the view_options.svg icon asset.
 * This path is resolved at build time and points to the optimized SVG file
 * with content hash (c65ff426) for cache busting.
 * 
 * @example
 *