/**
 * Ceiling asset module
 * Exports the URL path to the ceiling image asset.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 */

/**
 * The public URL path to the ceiling PNG image asset.
 * This path is resolved at build time by the bundler and includes content hash for cache busting.
 * 
 * @example
 *