/**
 * Webpack asset module that exports the URL path to a content SVG file.
 * This module is typically generated by Webpack's asset/resource loader
 * to handle static assets like images, fonts, and SVG files.
 * 
 * @module ContentAsset
 */

/**
 * The public URL path to the content SVG asset.
 * This path is resolved at build time by Webpack and includes the public path prefix.
 * 
 * @example
 *