/**
 * Asset module that exports the URL path to a member avatar image.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static image files.
 * 
 * @module MemberAsset
 */

/**
 * The public URL path to the member image asset.
 * Points to the hashed static asset file for cache-busting purposes.
 * 
 * @example
 *