/**
 * CSS Module Exports
 * Type definitions for CSS module with style injection
 */

/**
 * CSS module class names mapping
 * Contains the hashed class names generated by CSS modules
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader configuration options
 */
interface StyleLoaderOptions {
  /**
   * Function to transform and inject style tags into the DOM
   */
  styleTagTransform: () => void;

  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;

  /**
   * Function to insert style elements into specified target
   * @param target - DOM insertion point (e.g., "head")
   */
  insert: (target: string) => void;

  /**
   * DOM API implementation for style manipulation
   */
  domAPI: () => void;

  /**
   * Function to create and insert style elements
   */
  insertStyleElement: () => void;
}

/**
 * Default export: CSS module class names
 * Returns the locally scoped class names or undefined if not available
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-exported members from the CSS module
 * All named exports from the original CSS module are re-exported here
 */
export * from './630154';