/**
 * Webpack asset module that exports the URL path to the team icon SVG file.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module TeamIconAsset
 */

/**
 * The public URL path to the team icon SVG asset.
 * This path is resolved by webpack based on the publicPath configuration.
 * 
 * @example
 *