/**
 * Webpack asset module that exports the URL path to a case icon SVG file.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module CaseIconAsset
 */

/**
 * The public URL path to the case.svg icon asset.
 * The hash (96ea9b07) in the filename is used for cache busting.
 * 
 * @example
 * import caseIconUrl from './case-icon-asset';
 * // caseIconUrl === "assets/case.96ea9b07.svg"
 */
declare const caseIconAssetUrl: string;

export default caseIconAssetUrl;