/**
 * CSS Module Loader Type Definitions
 * 
 * This module handles CSS-in-JS style injection and exports CSS module class names.
 * Typically generated by webpack's style-loader and css-loader with modules enabled.
 */

/**
 * CSS Modules class name mapping
 * Maps CSS class names to their hashed/scoped equivalents
 */
export interface CSSModuleClasses {
  readonly [className: string]: string;
}

/**
 * Style loader API for managing injected styles
 */
export interface StyleLoaderAPI {
  /**
   * Transforms and injects style tags into the document
   */
  styleTagTransform: () => void;
  
  /**
   * Sets attributes on generated style elements
   */
  setAttributes: () => void;
  
  /**
   * Inserts style elements into a specific DOM location
   * @param target - Target selector (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM manipulation API for style injection
   */
  domAPI: () => void;
  
  /**
   * Creates and inserts style elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS module exports containing class name mappings
 */
export interface CSSModuleExports {
  /**
   * Local class name mappings for this CSS module
   * undefined if no class names are defined
   */
  locals?: CSSModuleClasses;
}

/**
 * Default export: CSS module class names
 * Returns an object mapping original class names to their scoped versions,
 * or undefined if the module has no exported classes
 */
declare const cssModuleClasses: CSSModuleClasses | undefined;

export default cssModuleClasses;

/**
 * Re-exported members from the CSS module
 * Allows direct access to any named exports from the CSS file
 */
export * from './style-module';