/**
 * Asset module that exports the URL path to the 'new' SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * to handle static file imports.
 * 
 * @module NewIconAsset
 */

/**
 * The public URL path to the new.svg icon asset.
 * This path is resolved by the bundler and points to the hashed asset file
 * in the output directory (e.g., "assets/new.7e58a92c.svg").
 * 
 * @type {string}
 * @example
 *