/**
 * Iterator cleanup utility function
 * Safely closes an iterator when exiting a loop (break, return, or exception)
 * This is typically generated by TypeScript/Babel for for-of loop cleanup
 */

/**
 * Iterator with optional return method (ES2015 iteration protocol)
 */
interface IteratorWithReturn<T = unknown> {
  /** Returns the next value in the iteration */
  next(): IteratorResult<T>;
  
  /** Optional method called when iterator is exited prematurely */
  return?(): IteratorResult<T> | void;
  
  /** Optional method for handling errors */
  throw?(error?: unknown): IteratorResult<T>;
}

/**
 * Safely closes an iterator by calling its return method if present
 * 
 * @param iterator - The iterator to clean up
 * @param shouldFinalize - Whether to execute the return/cleanup (typically on break/return)
 * @param hasError - Whether an exception occurred during iteration
 * @param error - The error object if hasError is true
 * 
 * @throws Re-throws the error if hasError is true after cleanup
 * 
 * @example
 *