/**
 * Asset module that exports the path to a question icon SVG file.
 * This is typically generated by webpack's asset/resource module loader.
 * 
 * @module question2-asset
 */

/**
 * The public URL path to the question2.svg asset file.
 * This path is resolved relative to the webpack public path configuration.
 * 
 * @example
 *