/**
 * Asset module that exports the URL path to a public SVG icon.
 * This module is typically generated by webpack's asset/resource loader
 * for static file imports.
 * 
 * @module PublicAssetModule
 */

/**
 * The public SVG asset URL path.
 * Points to the hashed static asset file served from the assets directory.
 * 
 * @constant {string} PUBLIC_ASSET_URL - Resolved path: "assets/public.584fded6.svg"
 */
export declare const PUBLIC_ASSET_URL: string;

export default PUBLIC_ASSET_URL;