/**
 * Webpack asset module that exports the URL path to the master badge SVG image.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module BadgeMasterAsset
 */

/**
 * The public URL path to the master badge SVG asset.
 * This path is resolved by webpack's publicPath configuration at build time.
 * 
 * @example
 *