/**
 * SVG asset module export
 * Provides the public URL path for the master icon asset
 * 
 * @module AssetIconMaster
 * @description This module exports the resolved public path to the master icon SVG file.
 * The path is dynamically generated by the build system and includes a content hash
 * for cache busting (236b4aca).
 */

/**
 * The public URL path to the master icon SVG asset.
 * This path is resolved at build time and includes the asset hash for versioning.
 * 
 * @example
 *