/**
 * CSS Module exports for module_553609
 * 
 * This module represents a CSS Modules file that exports class name mappings.
 * The actual styles are injected into the DOM via style-loader at runtime.
 */

/**
 * CSS class name mappings exported by the CSS Module.
 * Keys are the original class names from the CSS file,
 * values are the hashed/scoped class names generated by CSS Modules.
 * 
 * @example
 * // If the CSS file contains: .button { color: red; }
 * // The export might be: { button: "module_553609__button__a1b2c" }
 */
declare const cssModuleExports: Readonly<Record<string, string>> | undefined;

export default cssModuleExports;

/**
 * Re-export all named exports from the underlying CSS module.
 * Typically CSS Modules export a default object, but can also include named exports.
 */
export * from './styles.module.css';