/**
 * Asset module that exports the URL path to the applypocket SVG image.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module ApplyPocketAsset
 */

/**
 * The public URL path to the applypocket.e2d3d92c.svg asset file.
 * This path is relative to the application's public path and can be used
 * directly in img src attributes or CSS background-image properties.
 * 
 * @example
 *