/**
 * Asset module that exports the file path to the door pocket SVG asset.
 * This module is typically generated by webpack's asset/resource module type.
 */

/**
 * The public path to the door pocket SVG asset.
 * This path is resolved at build time by the bundler.
 */
declare const doorPocketAssetPath: string;

export default doorPocketAssetPath;