/**
 * Asset module that exports the path to the model_ysjj SVG file.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 * 
 * @module AssetModule
 */

/**
 * The public URL path to the SVG asset file.
 * This path is resolved by the bundler and points to the compiled asset location.
 * 
 * @type {string}
 * @example
 * // Usage in application code:
 * import modelYsjjPath from './assets/model_ysjj.svg';
 * // modelYsjjPath === "assets/model_ysjj.15db8856.svg"
 */
declare const assetPath: string;

export default assetPath;