/**
 * Webpack asset module that exports the URL path to a new icon SVG file.
 * This module is typically auto-generated by Webpack's asset/resource loader.
 * 
 * @module AssetModule
 */

/**
 * The public URL path to the "new" icon SVG asset.
 * This path is resolved by the Webpack bundler and points to the
 * hashed asset file in the output directory.
 * 
 * @example
 *