/**
 * CSS Module type definitions
 * 
 * This module represents a CSS-in-JS module that exports typed class name mappings.
 * It uses style-loader or similar webpack loaders to inject styles and provide
 * typed access to CSS class names.
 */

/**
 * CSS Module class name mappings
 * 
 * An object containing the mapping between exported CSS class names
 * and their hashed/scoped versions generated by css-loader.
 * 
 * @example
 *