/**
 * Asset module that exports the URL path to a mark image file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling image imports.
 */

/**
 * The public URL path to the mark.png image asset.
 * This path is resolved relative to the webpack public path configuration.
 * 
 * @example
 *