/**
 * Video asset module
 * Exports the public URL path for the video.svg icon asset
 * 
 * This module provides access to a statically imported SVG file that is processed
 * by the build system and made available at a hashed URL for cache busting.
 */

/**
 * The public URL path to the video SVG icon asset.
 * This path is generated by the bundler and includes a content hash for cache invalidation.
 * 
 * @example
 *