/**
 * Asset module that exports the path to a model SVG file.
 * This module is typically generated by webpack's asset/resource module type
 * for handling static file imports.
 */

/**
 * The public path to the model SVG asset.
 * Points to the compiled/hashed SVG file in the assets directory.
 * 
 * @example
 *