// Type Definitions for Decompiled Webpack Bundle (Human Readable)
// Generated by tsgo dewebpack

declare module "0" {
}

declare module "1" {
    export const lastIndex: any;
}

declare module "1010" {
    export enum GBBreakerTypeEnum {
        C65K_15_1P = 50,
        C65K_20_1P = 51,
        C65K_25_1P = 52,
        C65K_32_1P = 53,
        C65N_20_2P = 30,
        C65N_25_2P = 31,
        C65N_40_2P = 32,
        C65N_63_2P = 33,
        DPN_20_1P = 11,
        DPN_25_1P = 12,
        DPN_32_1P = 13,
    }
    export enum GBCircuitTypeEnum {
        WP = 4,
        WP_K = 3,
        WX = 2,
    }
    export enum GBHouseHoldCableTypeEnum {
        BV750_2X10_E10PVC25 = 2,
        BV750_2X16_E16PVC32 = 3,
    }
    export enum GBTotalBreakerTypeEnum {
        C65N_25_2P = 31,
        C65N_40_2P = 32,
        C65N_63_2P = 33,
    }
    export enum GBTubeTypeEnum {
        PVC20 = 2,
        PVC25 = 3,
        PVC32 = 4,
        PVC40 = 5,
    }
    export enum GBWireTypeEnum {
        BVR_2X2D5 = 11,
        BVR_2X2D5_E2D5 = 14,
        BVR_2X4 = 12,
        BVR_2X4_E2D5 = 17,
        BVR_2X4_E4 = 15,
        BVR_2X6 = 13,
        BVR_2X6_E6 = 16,
    }
    export const BV750_2X10P_E10PVC25: any;
    export const BV750_2X10_E10PVC25: any;
    export const BV750_2X16_E16PVC32: any;
    export const C65N_20_2P: any;
    export const C65N_25_2P: any;
    export const C65N_40_2P: any;
    export const C65N_63_2P: any;
    export const DPN_16_1P: any;
    export const DPN_20_1P: any;
    export const DPN_25_1P: any;
    export const DPN_32_1P: any;
    export const C65K_15_1P: any;
    export const C65K_20_1P: any;
    export const C65K_25_1P: any;
    export const C65K_32_1P: any;
    export const PVC16: any;
    export const PVC20: any;
    export const PVC25: any;
    export const PVC32: any;
    export const PVC40: any;
    export const BVR_2X1D5: any;
    export const BVR_2X2D5: any;
    export const BVR_2X4: any;
    export const BVR_2X6: any;
    export const BVR_2X2D5_E2D5: any;
    export const BVR_2X4_E4: any;
    export const BVR_2X6_E6: any;
    export const BVR_2X4_E2D5: any;
    export const WL: any;
    export const WX: any;
    export const WP_K: any;
    export const WP: any;
}

declare module "10501" {
    export const cause: any;
}

declare module "10629" {
    export const getDocManager: any;
    export const DocumentManager: any;
    // Original Name: c
    export class DocumentManager {
        constructor();
        static instance(): DocumentManager;
        setActiveDocumentSilent(floorplan: Floorplan): void;
        init(): void;
        openDocument(designId: string, version: string, region: string, productsMap?: any): Promise<{floorplan: Floorplan; context: unknown}>;
        newDocument(designId: string, version: string, region: string, setAsActive?: boolean, productsMap?: any): Promise<{floorplan: Floorplan; context: unknown}>;
        private _newDocument(designId: string, version: string, region: string, setAsActive: boolean, productsMap?: any): Promise<{floorplan: Floorplan; context: unknown}>;
        clearActiveDocument(): void;
        private _registerPaveDependency(): void;
        registerPTInstance(ptInstance: any): void;
    }
    export const logger: any;
    export const _activeDocument: any;
    export const transManager: any;
    export const signalDocumentActivated: any;
    export const signalDocumentDeactivated: any;
    export const signalMetadataChanged: any;
    export const signalMigrateStatus: any;
    export const _signalHook: any;
    export const _instance: any;
    export const _lastSavedTransRequest: any;
    export const designMetadata: any;
    export const activeDocument: any;
}

declare module "10653" {
    export const CustomizedFeatureModel_IO: any;
    export const CustomizedFeatureModel: any;
    // Original Name: d
    export class CustomizedFeatureModel_IO extends import("43113").CustomizedModel_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const sketch: any;
    export const _sketch: any;
    export const duringRestore: any;
    export const _webCADDocument: any;
    // Original Name: h
    export class CustomizedFeatureModel extends import("43113").CustomizedModel {
        constructor(module: any, exports: any, ...args: any[]);
        _setHost(module: any): any;
        rebuildAfterLoad(): any;
        _onCopyFace2d(module: any): any;
        onChildDirty(module: any, exports: any): any;
        _onAddFace2d(module: any): any;
        bindSketchSignal(): any;
        onSketchDirty(module: any): any;
        rebuildDoc(module: any): any;
        _updateNewFaceMaterials(module: any, exports: any): any;
        _to3dPointArray(module: any, exports: any): any;
        _to3dPoint(module: any, exports: any): any;
        _getExtrudePlane(module: any): any;
        _connectArcPoints(module: any, exports: any): any;
        _splitPoints(module: any): any;
        _getExtrudePaths(module: any, exports: any): any;
        i: any;
    }
    export const signalSketchDirty: any;
    export const _sketchSignalHook: any;
    export const webCADDocument: any;
    export const type: any;
    export const Geometry: any;
    export const _matMap: any;
    export const x: any;
    export const y: any;
    export const z: any;
    export const length: any;
    export const id: any;
    export const const: any;
    export const : any;
    export const top: any;
    export const left: any;
    export const XLength: any;
    export const YLength: any;
    export const ZLength: any;
    export const xRay: any;
    export const isUpdated: any;
    export const reconstructedIds: any;
    export const error: any;
    export const options: any;
    export const reconstrucFailedIds: any;
    export const updatedSketchFaceIds: any;
    export const faceGroupId: any;
    export const faceId: any;
}

declare module "10726" {
    export const WallProfile: any;
    export const entity: any;
    export const _dirty: any;
    export const database: any;
    export const partialWalls: any;
    export const _borderGeometry: any;
    export const arcInfo: any;
    export const param: any;
    export const length: any;
    export const arcGeom: any;
    export const _profile: any;
    export const _indices: any;
    export const height3d: any;
    export const left: any;
    export const right: any;
    export const from: any;
    export const wall: any;
    export const id: any;
    export const intersect: any;
    export const inners: any;
    export const sourceGeom: any;
    export const targetGeom: any;
    export const sourceNeighbor: any;
    export const curve: any;
    export const includeUnshelvered: any;
}

declare module "1081" {
    export const DiscretePolygon2d: any;
    export const isDiscretePolygon2dArrayData: any;
    export const isDiscretePolygon2dData: any;
    // Original Name: l
    export class DiscretePolygon2d {
        constructor(module: any, exports: any, ...args: any[]);
        create(module: any, exports: any): any;
        assign(module: any, exports: any): any;
        getArea(): any;
        getBound(): any;
        isSamePolygon(module: any, exports: any): any;
        isSamePolygons(module: any, exports: any): any;
        getArea(module: any): any;
        getBound(module: any): any;
        verify(module: any): any;
    }
    export const outer: any;
    export const holes: any;
}

declare module "10850" {
    export const CustomizedPMModel: any;
    export const CustomizedPMModel_IO: any;
    // Original Name: s
    export class CustomizedPMModel_IO extends import("24567").Entity_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const creator: any;
    export const unit: any;
    export const webCADDocument: any;
    export const _faceMaterials: any;
    export const duringRestore: any;
    // Original Name: l
    export class CustomizedPMModel extends import("24567").Entity {
        constructor(module: any, ...args: any[]);
        isDiyDocOpened(): any;
        _setWebCADDocument(module: any): any;
        destroy(): any;
        getFaceCount(): any;
        openDiyDocument(module: any, exports: any): any;
        initByData(module: any): any;
        updateByData(module: any): any;
        getIO(): any;
        getChildrenByClass(module: any): any;
        getAllChildren(): any;
        removeInstanceEntity(module: any): any;
    }
    export const _faceTmpMaterials: any;
    export const height: any;
    export const _webCADDocument: any;
    export const _modelingDocId: any;
    export const faceCount: any;
    export const data: any;
    export const __creator: any;
    export const __unit: any;
    export const _curMixPaintFaceInfo: any;
    export const length: any;
    export const instanceId: any;
    export const faceEntity: any;
    export const faceGroup: any;
    export const faceGroupId: any;
    export const paveTo3dMatrix: any;
}

declare module "10932" {
    export const SlabDataProvider: any;
    // Original Name: m
    export class SlabDataProvider extends import("76563").IDataProvider {
        constructor(module: any, ...args: any[]);
        clearCacheGeometryData(module: any): any;
        _validFaces(module: any): any;
        getFacePath(module: any): any;
        getFacesPath(module: any): any;
        _getHoles(): any;
        getFaceHoles(module: any): any;
        isLineOnProfileOuter(module: any, exports: any): any;
        getSideFaceGeometry(module: any): any;
        _getInnerProfile(): any;
        getFaceGeometry(module: any): any;
        _calcTopBottomFaceRawGeometry(module: any, exports: any): any;
        isValidFaceGeometry(module: any): any;
        _getTopBottomFaceRawGeometry(module: any, exports: any): any;
        _getTopBottomFaceGeometry(module: any, exports: any, require: any): any;
        getTopFaceGeometry(module: any): any;
        getBottomFaceGeometry(module: any): any;
        getCustomizedModelsOnFace(module: any): any;
    }
    export const _insideProfilePath: any;
    export const slab: any;
    export const topFaceGeometry: any;
    export const bottomFaceGeometry: any;
    export const thickness: any;
    export const x: any;
    export const y: any;
    export const bottom: any;
    export const length: any;
    export const z: any;
    export const surface: any;
    export const height3d: any;
    export const count: any;
    export const outer: any;
    export const holes: any;
    export const height: any;
}

declare module "10973" {
    // Original Name: n
    export class default extends import("42288").default {
        _compute(module: any, exports: any, require: any, i: any): any;
        _oneLightCase(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _twoLights2to2Point5(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _twoLights2Point5to3(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _manyLightsLargerThan3(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _oneLight4L(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _oneLight4SmallL(module: any, exports: any, require: any, i: any, n: any, r: any): any;
        _manyLights4L(module: any, exports: any, require: any, i: any, r: any, a: any): any;
        _twoSymmetricLights(module: any, exports: any, require: any, i: any, n: any, r: any, a: any, s: any): any;
        _manySymmetricLights(module: any, exports: any, require: any, i: any, n: any, r: any, a: any, s: any, l: any): any;
    }
    export const templateKey: any;
    export const REALISTIC: any;
    export const CHILLY_3: any;
    export const NATURE_3: any;
    export const z: any;
    export const y: any;
    export const position: any;
    export const intensity: any;
    export const temperature: any;
    export const ies: any;
    export const x: any;
    export const offset: any;
    export const lShape: any;
    export const lwidth: any;
}

declare module "10993" {
    export const reduce: any;
    export const length: any;
}

declare module "11122" {
    export const NCPCeilingDecorator: any;
    export const entity: any;
}

declare module "1121" {
    export const Cache: any;
    export const logger: any;
    export const _name: any;
    export const _cache: any;
    export const tag: any;
}

declare module "11256" {
    export const writable: any;
}

declare module "11291" {
    export const GBCircuitComp: any;
    // Original Name: a
    export class GBCircuitComp extends import("84600").CircuitComp {
        constructor(...args: any[]);
        clone(): any;
        dump(): any;
        load(module: any, exports: any): any;
    }
    export const circuitType: any;
    export const circuitTypeNumber: any;
    export const breakerType: any;
    export const tubeType: any;
    export const wireType: any;
    export const roomRange: any;
    export const _referObject: any;
    export const Type: any;
}

declare module "11420" {
    export const length: any;
    export const RoofDrawingRegion: any;
    // Original Name: c
    export class RoofDrawingRegion extends import("24567").Entity {
        constructor(...args: any[]);
        needDump(): any;
        destroy(): any;
        getBuilder(): any;
        clearBuilder(): any;
        getSketch(): any;
        setSketch(module: any): any;
        updateSketch(module: any): any;
        initByRoof(module: any): any;
        isValid(): any;
    }
    export const _roofId: any;
    export const _sketchBuilder: any;
    export const _sketchData: any;
}

declare module "11440" {
    export enum AnimationType {
    }
    export const rotation: any;
    export const translation: any;
}

declare module "11502" {
    export const length: any;
    export const Loop_IO: any;
    export const Loop: any;
    // Original Name: h
    export class Loop_IO extends import("24567").Entity_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
        migrateLoad(module: any, exports: any, require: any): any;
    }
    export const root: any;
    export const __root: any;
    // Original Name: u
    export class Loop extends import("24567").Entity {
        constructor(module: any, exports: any, ...args: any[]);
        createFromPoints(module: any, exports: any): any;
        createFromCurves(module: any): any;
        initData(module: any, exports: any): any;
        appendCoEdge(module: any, exports: any): any;
        removeCoEdge(module: any, exports: any, require: any): any;
        onChildDirty(module: any, exports: any): any;
        forEachCoEdge(module: any, exports: any): any;
        forEachVertex(module: any, exports: any): any;
        forEachOwnedVertex(module: any, exports: any): any;
        getCoEdges(): any;
        getLoopEdges(): any;
        getLoopCurves(): any;
        getLoopCurves2d(): any;
        getLoopVertices(): any;
        findCoEdge(module: any, exports: any): any;
        findCoEdgeToVertex(module: any): any;
        toPolygon(module: any): any;
        toDiscretePolygon(): any;
        invert(): any;
        clear(): any;
        getMassProps(): any;
        getIO(): any;
        verify(): any;
        validate(module: any): any;
    }
    export const prev: any;
    export const next: any;
    export const id: any;
    export const coedge: any;
    export const partner: any;
    export const parent: any;
    export const to: any;
    export const reversed: any;
    export const curve: any;
}

declare module "11577" {
    export const NCPBackgroundWallBaseUtil: any;
    export const x: any;
    export const y: any;
    export const z: any;
    export const XLength: any;
    export const YLength: any;
    export const ZLength: any;
    export const host: any;
}

declare module "11667" {
    export const exports: any;
}

declare module "11732" {
    export const Curve_IO: any;
    export const Curve: any;
    // Original Name: i
    export class Curve_IO {
        instance(): any;
        dump(e: any, t: any, o: any, i: any): any;
        load(e: any, t: any, o: any): any;
        constructor(...args: any[]);
    }
    export const _instance: any;
    export const Class: any;
}

declare module "1187" {
    export const exports: any;
}

declare module "1190" {
    export const exports: any;
}

declare module "12039" {
    export const MigrateFacegroup: any;
    export const surface: any;
    export const OVERLAP: any;
    export const length: any;
    export const sameDirWithSurface: any;
    export const pre: any;
    export const next: any;
    export const planePath: any;
    export const geometryMap: any;
    export const worldToBaseLocal: any;
    export const faceGroupId: any;
    export const faceGroupBoundMap: any;
    export const connectMode: any;
    export const faceEntity: any;
}

declare module "12137" {
    export const OpeningSnapHelper: any;
    export const _opening: any;
    export const _layer: any;
    export const _isDisableLeftRightSnap: any;
    export const _isMigration: any;
    export const length: any;
    export const multiSnapInfos: any;
    export const snapPos: any;
    export const dis: any;
    export const x: any;
    export const XSize: any;
    export const y: any;
    export const YSize: any;
    export const PI: any;
    export const width: any;
    export const host: any;
    export const id: any;
    export const Arc2d: any;
    export const jointCurve: any;
    export const chordHeight: any;
    export const ZRotation: any;
    export const thickness: any;
    export const min: any;
    export const const: any;
    export const instanceof: any;
    export const : any;
    export const max: any;
    export const angle: any;
    export const linerAngle: any;
}

declare module "12139" {
    export const SplitHelper: any;
    export const _layer: any;
    export const roomRegionList: any;
    export const const: any;
    export const : any;
    export const material: any;
    export const faceEntity: any;
    export const type: any;
    export const length: any;
    export const size: any;
    export const id: any;
    export const curve: any;
    export const endData: any;
    export const splitCurves: any;
    export const startData: any;
    export const OUT: any;
    export const oldId: any;
}

declare module "12220" {
    export const WallIntersectResolver: any;
    // Original Name: n
    export class WallIntersectResolver {
        constructor(module: any, exports: any, require: any, i: any, n: any, r: any, ...args: any[]);
        _getInnerConnectVertices(module: any): any;
        _calcBisectorIntersection(): any;
        else: any;
        for(let: any, module: any, exports: any, module: any, : any, exports: any, module: any): any;
    }
    export const sourceWall: any;
    export const sourceLeft: any;
    export const sourcePoint: any;
    export const targetWall: any;
    export const targetLeft: any;
    export const connectPoints: any;
    export const sourceGeom: any;
    export const targetGeom: any;
    export const sourceNeighbor: any;
    export const targetPoint: any;
    export const length: any;
    export const sourceParam: any;
    export const targetParam: any;
    export const ID: any;
    export const arcParams: any;
    export const arcInfo: any;
    export const from: any;
    export const PI: any;
    export const overlapAngle: any;
}

declare module "12239" {
    export const openingNotChildOfLayer: any;
    export const OpeningHelper: any;
    // Original Name: _
    export class OpeningHelper {
        constructor(module: any, ...args: any[]);
        getCurvesBySvg(module: any): any;
        getSvgByCurves(module: any, exports: any): any;
        getFixMetaProfile(module: any): any;
        validRotation(): any;
        validPosition(): any;
        getBottomProfile(module: any): any;
        getRealFrontProfile(module: any): any;
        getFinalFrontProfile(module: any): any;
    }
    export const _opening: any;
    export const x: any;
    export const y: any;
    export const length: any;
    export const id: any;
    export const extraId: any;
    export const holes: any;
}

declare module "12399" {
    export const length: any;
    export const Arc2DState: any;
    // Original Name: a
    export class Arc2DState extends import("18439").State {
        constructor(module: any, exports: any, ...args: any[]);
        init(module: any, exports: any): any;
        getDiscretePoints(module: any, exports: any): any;
        verify(): any;
        verifyBeforeDump(): any;
        dump(module: any, exports: any): any;
        load(module: any, exports: any): any;
    }
    export const localId: any;
    export const name: any;
    export const isEditable: any;
    export const centerAngle: any;
    export const x: any;
    export const y: any;
    export const id: any;
    export const Class: any;
}

declare module "12551" {
    export const exports: any;
}

declare module "12563" {
    export const Flue: any;
    // Original Name: r
    export class Flue extends import("998").Obstacle {
        constructor(module: any, exports: any, ...args: any[]);
        initByMeta(module: any): any;
    }
    export const webCADDocument: any;
}

declare module "12573" {
    export enum SpaceHoleType {
        Groove = 3,
        Shank = 4,
        ThreeInOne = 2,
    }
    export const SpaceHole: any;
    export const Hinge: any;
    export const ThreeInOne: any;
    export const Groove: any;
    export const Shank: any;
    // Original Name: r
    export class SpaceHole extends import("24567").Entity {
        constructor(...args: any[]);
        clearSpaceHoles(): any;
        needDump(): any;
        canTransact(): any;
    }
    export const _spaceHoles: any;
    export const length: any;
}

declare module "1276" {
    export const PAssemblyProcessor: any;
}

declare module "1280" {
    export const RoofsDrawingSketch2dBuilder: any;
    // Original Name: a
    export class RoofsDrawingSketch2dBuilder extends import("77756").ExtraordinarySketch2dBuilder {
        updateAppendix(): any;
        _completeUpdate(): any;
        createSuperLargeBackground(): any;
    }
    export const _sketch2d: any;
    export const faces: any;
    export const RegionTopoTag: any;
}

declare module "12812" {
    export const CurtainHandler: any;
    export const content: any;
    export const max_vertex: any;
    export const min_vertex: any;
    export const x: any;
    export const y: any;
    export const z: any;
    export const curtain_rail: any;
    export const index: any;
    export const modelTrans: any;
    export const localTrans: any;
    export const globalTrans: any;
    export const curtain_rail_tip_L: any;
    export const curtain_rail_tip_R: any;
    export const curtain_screen_glass: any;
    export const curtain_side: any;
    export const curtain_loop: any;
    export const userDefined: any;
    export const Screen: any;
    export const ZLength: any;
    export const boundArea: any;
    export const offset: any;
}

declare module "1288" {
    export const length: any;
    export const MixGrid: any;
    export const MixGrid_IO: any;
    // Original Name: c
    export class seamMaterial extends import("29884").Grid_IO {
        instance(): any;
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const _MixGrid_IO_instance: any;
    export const polygons: any;
    export const seamColor: any;
    export const seamWidth: any;
    export const tileSizeX: any;
    export const tileSizeY: any;
    export const materials: any;
    export const type: any;
    export const __blocks: any;
    export const __seamColor: any;
    export const __seamWidth: any;
    export const useColor: any;
    export const colorMode: any;
    export const __seamMaterial: any;
    // Original Name: d
    export class MixGrid extends import("29884").Grid {
        constructor(module: any, exports: any, ...args: any[]);
        create(module: any, exports: any, require: any, i: any, n: any, r: any, a: any, s: any): any;
        getIO(): any;
        _setBlocks(module: any): any;
        update(module: any, exports: any, require: any, i: any, n: any, a: any, s: any, c: any, d: any): any;
        updataPolygonIdInMaterials(module: any): any;
        updateBlockMaterialMap(module: any): any;
        getChildMaterials(): any;
        isMixType(): any;
        update(): any;
        setFlagOn(module: any, exports: any): any;
        setFlagOff(module: any, exports: any): any;
        isValid(): any;
        checkClonedResult(module: any): any;
    }
    export const blocks: any;
    export const seekId: any;
    export const extSeekIds: any;
    export const x: any;
    export const y: any;
}

declare module "12883" {
    export const g: any;
    export const writable: any;
    export const initMetaManager: any;
    export const exports: any;
}

declare module "12944" {
    export const isSubsetOf: any;
}

declare module "13113" {
    // Original Name: r
    export class default extends import("42288").default {
        _compute(module: any, exports: any, require: any, i: any): any;
    }
    export const templateKey: any;
    export const z: any;
    export const x: any;
    export const y: any;
}

declare module "1315" {
    export const NCPBackgroundWallArray: any;
    export const NCPBackgroundWallArray_IO: any;
    // Original Name: u
    export class NCPBackgroundWallArray_IO extends import("28309").ParametricModelArray_IO {
    }
    // Original Name: g
    export class NCPBackgroundWallArray extends import("28309").ParametricModelArray {
        constructor(module: any, exports: any, ...args: any[]);
        destroy(): any;
        _createArrayContent(): any;
        initArray(module: any): any;
        _enableClip(): any;
        dirtyClipGeometry(module: any): any;
        getUnClippedGraphicsData(): any;
        a: any;
        a: any;
        faces: any;
        forEach(): any;
    }
    export const _dirtyClip: any;
    export const signalArrayChanged: any;
    export const _signalHook: any;
    export const signalClipDirty: any;
    export const _graphicsData: any;
    export const _boundDirty: any;
    export const _clipTask: any;
    export const meshKey: any;
    export const srcModel: any;
    export const getGraphicsData: any;
}

declare module "1316" {
    export const Scene: any;
    // Original Name: n
    export class Scene extends import("75312").BaseObject {
        constructor(module: any, exports: any, require: any, ...args: any[]);
        onInit(): any;
    }
}

declare module "13264" {
    export const Hole: any;
    // Original Name: c
    export class Hole extends import("50265").Content {
        constructor(module: any, exports: any, require: any, ...args: any[]);
        onChildAdded(module: any): any;
        createFaceObject(module: any): any;
        createPocketObject(module: any): any;
        onInit(): any;
        onEntityDirty(module: any): any;
        getClipAidCSGs(module: any): any;
        _createClipAidCSGs(module: any): any;
        getOpeningLoop(module: any, exports: any): any;
        onCleanup(): any;
        onParentReplaced(module: any): any;
        getModelMatrix(): any;
        _computeLocalMatrix(module: any): any;
        onUpdatePosition(): any;
    }
    export const childNodes: any;
    export const _dataProvider: any;
    export const geometryDirty: any;
    export const positionDirty: any;
    export const _clipAidCSGs: any;
    export const entity: any;
    export const vertices: any;
    export const y: any;
    export const ZSize: any;
    export const length: any;
    export const parent: any;
    export const outerThickness: any;
    export const thickness: any;
    export const x: any;
    export const z: any;
    export const _modelMatrixLocal: any;
    export const XScale: any;
    export const YScale: any;
    export const ZScale: any;
    export const ZLength: any;
    export const _matrixLocal: any;
}

declare module "13270" {
    export const length: any;
    export const exports: any;
}

declare module "13327" {
    export const exports: any;
}

declare module "13818" {
    export const exports: any;
}

declare module "14269" {
    export const length: any;
    export const Ceiling_IO: any;
    export const Ceiling: any;
    // Original Name: h
    export class Ceiling_IO extends import("82625").Face_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
        migrateLoad(module: any, exports: any, require: any): any;
    }
    export const isSplitCeiling: any;
    export const divideInfo: any;
    export const __divideInfo: any;
    // Original Name: u
    export class Ceiling extends import("82625").Face {
        constructor(module: any, exports: any, ...args: any[]);
        create(module: any, exports: any, require: any, i: any): any;
        getIO(): any;
        forEachWall(module: any, exports: any): any;
        forEachSurface(module: any, exports: any): any;
        forEachStructureFace(module: any, exports: any): any;
    }
    export const signalContentAdded: any;
    export const signalContentRemoved: any;
}

declare module "1438" {
    export const PowerSysComp: any;
    export const PowerSysCompEnum: any;
    export const GBPowerSys: any;
    // Original Name: n
    export class PowerSysComp extends import("8467").Component {
    }
}

declare module "14502" {
    export const length: any;
    export const Molding_IO: any;
    export const MoldingTypeEnum: any;
    export const Molding: any;
    export const Mitre: any;
    export const Baseboard: any;
    export const Cornice: any;
    export const Pocket: any;
    export const WallBoardBaseboard: any;
    export const WallBoardWaistLine: any;
    export const CustomizedModelMolding: any;
    export const NCustomizedModelMolding: any;
    // Original Name: h
    export class Molding_IO extends import("24567").Entity_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const productsMap: any;
    export const data: any;
    export const seekId: any;
    export const XSize: any;
    export const YSize: any;
    export const material: any;
    export const _seekId: any;
    export const __XSize: any;
    export const __YSize: any;
    // Original Name: u
    export class Molding extends import("24567").Entity {
        constructor(module: any, exports: any, ...args: any[]);
        initByMeta(module: any): any;
        getMetadataFilterKeys(): any;
        getHost(): any;
        assignTo(module: any): any;
        getMaterial(): any;
        setMaterial(module: any): any;
        _onSizeChanged(module: any, exports: any): any;
        _onMaterialChanged(module: any, exports: any): any;
        getPaths(): any;
        getWholePaths(): any;
        getIO(): any;
        refreshBoundInternal(): any;
        _copyFrom(module: any): any;
        isSameMolding(module: any): any;
        verify(): any;
        destroy(): any;
        canSelect(): any;
    }
    export const _host: any;
    export const _materialSignalHook: any;
    export const metadata: any;
    export const host: any;
    export const rotation: any;
    export const _disposed: any;
}

declare module "14516" {
    export const length: any;
    export const LightSubGroup_IO: any;
    export const LightSubGroup: any;
    // Original Name: c
    export class LightSubGroup_IO extends import("3577").Light_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const members: any;
    export const memberPropertiesConfig: any;
    export const groupInteractionMode: any;
    export const contentID: any;
    export const group: any;
    // Original Name: d
    export class LightSubGroup extends import("3577").Light {
        constructor(module: any, ...args: any[]);
        create(module: any, exports: any): any;
        clone(): any;
        createMemberPropertiesConfig(module: any): any;
        toFlatMemberList(): any;
        dirtyPosition(module: any): any;
        dirtyGeometry(module: any): any;
        onFieldChanged(module: any, exports: any, require: any): any;
        addMember(module: any): any;
        removeMember(module: any): any;
        isVirtual(): any;
        hasAreaSize(): any;
        _setMembers(module: any): any;
        _addMember(module: any): any;
        _removeMember(module: any): any;
        forEachMember(module: any, exports: any): any;
        hasMember(module: any, exports: any): any;
        _rotate(module: any, exports: any): any;
        setFlagOn(module: any, exports: any, require: any): any;
        setFlagOff(module: any, exports: any, require: any): any;
        getIO(): any;
        refreshBoundInternal(): any;
        _onXYZChanged(module: any, exports: any): any;
        _move(module: any): any;
        verify(): any;
        isValid(): any;
        onFlagChanged(module: any): any;
    }
    export const __members: any;
    export const __x: any;
    export const __y: any;
    export const __z: any;
    export const XRotation: any;
    export const YRotation: any;
    export const ZRotation: any;
    export const _memberProxy: any;
    export const type: any;
    export const targetEnabled: any;
    export const rotation: any;
    export const x: any;
    export const y: any;
    export const outline: any;
    export const ZSize: any;
    export const left: any;
    export const top: any;
    export const XSize: any;
    export const YSize: any;
    export const z: any;
    export const removed: any;
    export const flag: any;
    export const MemberProxyMethod: any;
    export const SubGroup: any;
}

declare module "1460" {
    export const EdgeUtil: any;
    export const length: any;
    export const z: any;
    export const lerp: any;
}

declare module "14623" {
    export const exports: any;
}

declare module "14672" {
    export const AssemblyMeta: any;
    export const MetadataEnum: any;
    export const DocumentStatus: any;
    export const FloorplanVersion: any;
    export const FloorplanMeta: any;
    export const Metadata: any;
    export const designName: any;
    export const description: any;
    export const documentStatus: any;
    export const attributes: any;
    export const designId: any;
    export const threeDThumbnail: any;
    export const userId: any;
    export const meta: any;
    export const image3d: any;
    export const image2d: any;
    export const versionId: any;
    export const assetType: any;
    export const mainAssetId: any;
    export const originalAccessoryAssetId: any;
    export const newAccessoryAssetId: any;
    export const removedAccessoryAssetId: any;
    export const designVersion: any;
    export const address: any;
    export const basicAttributes: any;
    export const originApartmentId: any;
    export const Private: any;
    export const Public: any;
    export const Deleted: any;
    export const Readonly: any;
    export const magic: any;
    export const version: any;
    export const unit: any;
    export const keywords: any;
    export const customizationVersion: any;
    export const origin: any;
    // Original Name: s
    export class Metadata {
        constructor(...args: any[]);
        init(): any;
        reset(): any;
        get(e: any): any;
        delete(e: any, t: any): any;
        set(e: any, t: any): any;
        setValue(e: any, t: any): any;
        setAttribute(e: any, t: any): any;
        toObject(): any;
        fromObject(e: any): any;
        load(e: any): any;
        flush(): any;
        registerFlushCallback(e: any): any;
        unregisterFlushCallback(e: any): any;
        getDesignMeta(e: any, t: any): any;
    }
    export const _metadataMap: any;
    export const _attributes: any;
    export const _changedValues: any;
    export const _changedAttributes: any;
    export const _flushCallbacks: any;
    export const size: any;
    export const bom: any;
}

declare module "14771" {
    export const VERSION: any;
}

declare module "14803" {
    export const AsmLightSubGroup_IO: any;
    export const AsmLightSubGroup: any;
    // Original Name: l
    export class AsmLightSubGroup_IO extends import("14516").LightSubGroup_IO {
        load(module: any, exports: any, require: any): any;
    }
    export const groupInteractionMode: any;
    // Original Name: c
    export class AsmLightSubGroup extends import("14516").LightSubGroup {
        constructor(module: any, ...args: any[]);
        create(module: any, exports: any): any;
        createByAssembly(module: any, exports: any, require: any): any;
        attachRealLight(): any;
        getIO(): any;
        refreshBoundInternal(): any;
        verify(): any;
        isValid(): any;
        getBoundingData(): any;
    }
    export const type: any;
    export const memberPropertiesConfig: any;
    export const contentID: any;
    export const content: any;
    export const boundInternal: any;
    export const outline: any;
    export const members: any;
    export const length: any;
    export const removed: any;
}

declare module "14805" {
    export const exports: any;
}

declare module "14890" {
    export const exports: any;
}

declare module "14908" {
    export const Migration: any;
    export const LogObject: any;
    export const VERSION: any;
    export const Stat: any;
    export const Math: any;
    export const Paint: any;
    export const LogLevelEnum: any;
    export const Logger: any;
    export const Transaction: any;
    export const Constraint: any;
    export const State: any;
    export const Material: any;
    export const Util: any;
    export const Geometry: any;
    export const Model: any;
    export const Doc: any;
}

declare module "15150" {
    export const EntityUtil: any;
    // Original Name: s
    export class EntityUtil {
        cloneEntityFromJSON(module: any): any;
        isValidSeekId(module: any): any;
        getMetaToDump(module: any, exports: any): any;
        deepSaveMeta(module: any): any;
        saveMetadata(module: any, exports: any, require: any, i: any, n: any): any;
        createIDGeneratorForClone(module: any, exports: any): any;
        getAllEntities(module: any): any;
        getRootEntity(module: any): any;
        getParentPAssembly(module: any): any;
        isChildOf(module: any, exports: any): any;
        getParentByContentType(module: any, exports: any): any;
        traverseApplyFuncForEntity(module: any, exports: any): any;
        traverseApplyFuncForEntities(module: any, exports: any): any;
        traverseGetEntitiesByContentType(module: any, exports: any, require: any, i: any): any;
        traverseGetEntitiesByContentTypeFromEntities(module: any, exports: any, require: any, i: any): any;
        traverseGetPContentByContentType(module: any, exports: any, require: any, i: any): any;
        traverseGetPContentByContentTypeFromEntities(module: any, exports: any, require: any, i: any): any;
        hasLightStrip(module: any): any;
        getLightStrips(module: any): any;
        getChildLights(module: any): any;
        isStructureBody(module: any): any;
        constructor(...args: any[]);
    }
    export const meta: any;
    export const data: any;
    export const materials: any;
    export const products: any;
    export const states: any;
    export const constraints: any;
    export const length: any;
    export const shallowSaveMeta: any;
    export const metadata: any;
    export const getMetadataFilterKeys: any;
    export const filter: any;
    export const contentType: any;
    export const forEachChild: any;
    export const forEachContent: any;
    export const forEachMember: any;
    export const localId: any;
}

declare module "15342" {
    export const GraphicsObjectType: any;
}

declare module "1540" {
    export const exports: any;
    export const enable: any;
    export const length: any;
    export const f: any;
    export const getOwnPropertyNames: any;
}

declare module "15602" {
    export const NCustomizedSquareColumn: any;
    export const NCustomizedSquareColumn_IO: any;
    // Original Name: a
    export class NCustomizedSquareColumn_IO extends import("73858").NCustomizedStructre_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    // Original Name: s
    export class NCustomizedSquareColumn extends import("73858").NCustomizedStructure {
        constructor(module: any, ...args: any[]);
        initByMeta(module: any): any;
        calcProfile(module: any): any;
        newSelf(): any;
        getIO(): any;
    }
    export const ZLength: any;
    export const XSize: any;
    export const userData: any;
    export const YSize: any;
    export const length: any;
}

declare module "15770" {
    export enum TreeCompEnum {
    }
    export const TreeComp: any;
    export const StrongElec: any;
    export const WeakElec: any;
    export const HotWater: any;
    export const ColdWater: any;
    // Original Name: r
    export class TreeComp extends import("8467").Component {
    }
}

declare module "15975" {
    export const BeamFaceInfo: any;
    // Original Name: n
    export class BeamFaceInfo extends import("24616").FaceInfo {
        constructor(module: any, exports: any, ...args: any[]);
    }
    export const isAux: any;
    export const curve: any;
}

declare module "16257" {
    export const forEach: any;
    export const prototype: any;
    export const constructor: any;
    export const exports: any;
}

declare module "16294" {
    export enum RelationshipType {
    }
    export enum SupportedSignalTypes {
    }
    export const SweepPath: any;
    export const FaceVisible: any;
    export const IsContentInRoom: any;
    export const Dirty: any;
    export const ChildAdded: any;
    export const ChildRemoved: any;
    export const HostChanged: any;
    export const FieldChanged: any;
}

declare module "16481" {
    export const length: any;
    export const DAssembly: any;
    export const DAssembly_IO: any;
    // Original Name: g
    export class DAssembly_IO extends import("20551").Content_IO {
        dump(module: any, exports: any, require: any, i: any): any;
        load(module: any, exports: any, require: any): any;
    }
    export const masterId: any;
    export const hiddenByConstrain: any;
    export const customizationContentType: any;
    export const isFunctionComponent: any;
    export const imodelParentId: any;
    export const fixK: any;
    export const fixS: any;
    export const materialId: any;
    export const animationMatrix4: any;
    export const __masterId: any;
    export const __hiddenByConstrain: any;
    export const __customizationContentType: any;
    export const __isFunctionComponent: any;
    export const __imodelParentId: any;
    export const __fixK: any;
    export const __fixS: any;
    export const __materialId: any;
    export const __isOpened: any;
    export const __animationMatrix4: any;
    // Original Name: p
    export class DAssembly extends import("20551").Content {
        constructor(module: any, exports: any, ...args: any[]);
        isContentInLoop(module: any, exports: any): any;
        isContentInRoom(module: any, exports: any): any;
        dirtyNotFloorChildren(): any;
        dirtyRecursive(): any;
        dirtyPosition(): any;
        getElementPaths(module: any, exports: any): any;
        getGlobalBound3dPoints(): any;
        getGlobalBoundingBox3d(): any;
        getBoundingBox3d(): any;
        getChild(module: any): any;
        getBound3dPoints(): any;
        getLocalBound3dPoints(): any;
        getLocalBoundBox3d(): any;
        getLocalOutline(): any;
        getOutline(): any;
        refreshBoundInternal(): any;
        onAddedToParent(module: any): any;
        getIO(): any;
        getViewPaths(): any;
        canTransactField(): any;
        getUniqueParent(): any;
        getProxyId(): any;
        getCorniceCutterInfo(module: any): any;
        getBaseboardCutterInfo(module: any): any;
        migrateLoad(module: any, exports: any): any;
        getProxyObject(): any;
    }
    export const __translation: any;
    export const __localId: any;
    export const contentType: any;
    export const followParentAnimation: any;
    export const Class: any;
    export const x: any;
    export const y: any;
    export const hidden: any;
    export const z: any;
    export const localId: any;
    export const cutPath: any;
}

declare module "16574" {
    export const LayerUtil: any;
    export const ceilingLayer: any;
    export const getUnderLayer: any;
}

declare module "16728" {
    export const length: any;
    export const Wire: any;
    export const Wire_IO: any;
    // Original Name: d
    export class Wire_IO extends import("24567").Entity_IO {
        instance(): any;
        dump(module: any, exports: any, require: any, i: any): any;
    }
    export const _Wire_IO_instance: any;
    export const curves: any;
    export const __curves: any;
    export const reverseFlags: any;
    export const __reverseFlags: any;
    export const idGenerator: any;
    // Original Name: h
    export class Wire extends import("24567").Entity {
        constructor(module: any, exports: any, ...args: any[]);
        create(module: any): any;
        setCurves(module: any, exports: any): any;
        setReverse(module: any, exports: any): any;
        isReversedCurve(module: any): any;
        isReversed(module: any): any;
        _isReversedCurveByIndex(module: any): any;
        getIO(): any;
        verify(): any;
        onFieldChanged(module: any, exports: any, require: any): any;
        onChildDirty(module: any, exports: any): any;
        onChildRemoved(module: any): any;
        isOuter(): any;
        refreshBoundInternal(): any;
        replaceCurveByCurves(module: any, exports: any, require: any): any;
        getDiscretePoints(): any;
        getPath(): any;
        _getPoints(): any;
        isIncludeNonLinearCurve(): any;
        fixReverse(): any;
        addChild(module: any, exports: any): any;
    }
    export const id: any;
    export const outerLoop: any;
    export const from: any;
    export const to: any;
    export const x: any;
    export const y: any;
    export const leftPoint: any;
    export const rightPoint: any;
    export const topPoint: any;
    export const bottomPoint: any;
}

declare module "16950" {
    export const parseFloat: any;
}

declare module "17004" {
    export const NCPContent: any;
    // Original Name: c
    export class NCPContent extends import("50265").Content {
        constructor(module: any, exports: any, require: any, ...args: any[]);
        getParent(module: any): any;
        dirtyCache(module: any): any;
        clipGraphicsData(module: any, exports: any): any;
        toGraphicsData(module: any): any;
    }
    export const clipper: any;
    export const ncpcontent: any;
    export const parent: any;
    export const geometryDirty: any;
    export const type: any;
    export const Geometry: any;
    export const y: any;
    export const clipMeshes: any;
    export const cutPlanes: any;
    export const cutObstacles: any;
    export const clipInfo: any;
    export const bounding: any;
    export const host: any;
}

declare module "17029" {
    export const exports: any;
}

declare module "17113" {
    export class l {
        constructor(...args: any[]);
        init(module: any, exports: any): any;
        layout(module: any, exports: any, require: any): any;
        _postProcess1(module: any): any;
    }
    export const _roomInfo: any;
    export const _parameter: any;
    export const const: any;
    export const return: any;
    export const : any;
    export const SpotLight: any;
    export const SPOT_LIGHT_NUM_5: any;
    export const ies: any;
    export const type: any;
    export const length: any;
    export const ruleType: any;
    export class c extends l {
    }
    export class d extends l {