/**
 * Iterator cleanup utility function
 * Safely closes an iterator and handles cleanup errors
 * 
 * @remarks
 * This function is typically generated by TypeScript/Babel when compiling
 * for-of loops or destructuring assignments to ensure proper resource cleanup.
 * 
 * @param o - Flag indicating if cleanup should be performed
 * @param n - The iterator object that may have a return method
 * @param s - Flag indicating if an error should be thrown
 * @param r - The error to throw if s is true
 * 
 * @throws {Error} Throws the error `r` if `s` is true after cleanup
 * 
 * @example
 *