/**
 * Asset module that exports the path to a small "poor" animated GIF.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module assets/poor-small
 */

/**
 * The public path to the poor-small.gif asset file.
 * This path is resolved at build time by the bundler and includes the assets directory
 * and content hash for cache busting.
 * 
 * @example
 *