/**
 * Asset module that exports the path to a normal state SVG icon.
 * This module is typically generated by Webpack's asset/resource loader.
 * 
 * @module NormalIconAsset
 */

/**
 * The public path to the normal.svg asset file.
 * This path is resolved at build time and includes the content hash for cache busting.
 * 
 * @type {string}
 * @example "assets/normal.7f96d113.svg"
 */
declare const normalIconPath: string;

export default normalIconPath;