/**
 * Asset module that exports the path to the Copilot background image.
 * This module is typically generated by Webpack's asset/resource module type.
 */

/**
 * The public URL path to the copilot background PNG image asset.
 * 
 * @remarks
 * This path is resolved at build time by the bundler and includes:
 * - The public path prefix configured in the build tool
 * - The hashed filename for cache busting (322e7477)
 * 
 * @example
 *