/**
 * CSS Module Declaration
 * 
 * This module exports CSS class name mappings and style injection utilities.
 * Typically generated by style-loader + css-loader with modules enabled.
 */

/**
 * CSS class name mappings exported by this module.
 * Keys are the original class names, values are the hashed/scoped class names.
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style loader configuration options
 */
export interface StyleLoaderOptions {
  /** Function to transform and inject style tags into the DOM */
  styleTagTransform: () => void;
  
  /** Function to set attributes on style elements */
  setAttributes: () => void;
  
  /** Function to insert style elements into a target container */
  insert: (target: string) => void;
  
  /** DOM API utilities for style manipulation */
  domAPI: () => void;
  
  /** Function to create and insert style elements */
  insertStyleElement: () => void;
}

/**
 * CSS Module content structure
 */
export interface CSSModuleContent {
  /** CSS class name mappings (may be undefined if not using CSS modules) */
  locals?: CSSModuleClasses;
  
  /** Raw CSS content or other metadata */
  [key: string]: unknown;
}

/**
 * Default export: CSS class name mappings
 * 
 * @remarks
 * - Returns the `locals` object containing scoped CSS class names
 * - Returns `undefined` if CSS modules are not enabled
 * 
 * @example
 *