/**
 * Asset module that exports the path to the bubble SVG icon.
 * This module is typically generated by Webpack's asset/resource module type.
 * 
 * @module BubbleAsset
 * @description Provides the public URL path to the bubble.svg asset
 */

/**
 * The public URL path to the bubble SVG asset.
 * This path is resolved relative to the webpack public path configuration.
 * 
 * @example
 *