/**
 * Asset module that exports the path to a design PNG image.
 * This module is typically generated by webpack's asset/resource module type.
 * 
 * @module DesignAsset
 */

/**
 * The public path to the design image asset.
 * This path is resolved by the bundler and points to the compiled asset location.
 * 
 * @example
 *