/**
 * CSS Module type definitions
 * Handles CSS-in-JS style injection and provides typed class name exports
 */

/**
 * CSS Module class names mapping
 * Contains the hashed class names generated by CSS Modules
 */
export interface CSSModuleClasses {
  [className: string]: string;
}

/**
 * Style injection options configuration
 */
export interface StyleLoaderOptions {
  /**
   * Transform function to manipulate style tags before insertion
   */
  styleTagTransform: () => void;
  
  /**
   * Function to set attributes on style elements
   */
  setAttributes: () => void;
  
  /**
   * DOM insertion strategy bound to target element
   * @param target - The DOM element to insert styles into (e.g., "head")
   */
  insert: (target: string) => void;
  
  /**
   * DOM API implementation for style manipulation
   */
  domAPI: () => void;
  
  /**
   * Factory function to create style elements
   */
  insertStyleElement: () => void;
}

/**
 * CSS Module exports
 * Provides the locally scoped class names from the stylesheet
 */
declare const cssModuleExports: CSSModuleClasses | undefined;

export default cssModuleExports;

/**
 * Re-export all named exports from the original CSS module
 * This allows importing specific class names directly
 */
export * from 'original-css-module';