/**
 * Asset module that exports the resolved URL path to the city SVG icon.
 * This module is typically generated by webpack's asset/resource loader.
 * 
 * @module CityAsset
 */

/**
 * The resolved public URL path to the city.svg asset.
 * The hash (f9587438) in the filename ensures cache busting when the file changes.
 * 
 * @example
 *