/**
 * Asset module for membership banner background image
 * 
 * This module exports the URL path to the membership banner background image asset.
 * The image is processed by the build system and includes a content hash for cache busting.
 * 
 * @module MembershipBannerBackground
 */

/**
 * URL path to the membership banner background image
 * 
 * The path is automatically generated by the build system and includes:
 * - Base public path from the bundler configuration
 * - Asset filename with content hash (e.g., bg_qijianhuiyuan.e83f6fd8.png)
 * 
 * @example
 *